<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Service;

use Rafflesia\Resource\EnvelopeDatabaseJoinDriftData;

class DatabaseJoinDrifts
{
    public function __construct(
        private readonly \Rafflesia\HttpClient $client,
    ) {
    }

    /**
     * @param string $baselineFromRelease
     * @param string $baselineToRelease
     * @param \Rafflesia\Resource\QueryBudget|null $budget
     * @param string $candidateFromRelease
     * @param string $candidateToRelease
     * @param string|null $datasetName
     * @param string|null $datasetVersion
     * @param string $fromDatabase
     * @param string|null $ontologyDigest
     * @param \Rafflesia\Resource\DatabaseJoinsSafety|null $safety
     * @param string $toDatabase
     * @return \Rafflesia\Resource\EnvelopeDatabaseJoinDriftData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function create(
        string $baselineFromRelease,
        string $baselineToRelease,
        string $candidateFromRelease,
        string $candidateToRelease,
        string $fromDatabase,
        string $toDatabase,
        ?\Rafflesia\Resource\QueryBudget $budget = null,
        ?string $datasetName = null,
        ?string $datasetVersion = null,
        ?string $ontologyDigest = null,
        ?\Rafflesia\Resource\DatabaseJoinsSafety $safety = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeDatabaseJoinDriftData {
        $body = array_filter([
            'baseline_from_release' => $baselineFromRelease,
            'baseline_to_release' => $baselineToRelease,
            'budget' => $budget,
            'candidate_from_release' => $candidateFromRelease,
            'candidate_to_release' => $candidateToRelease,
            'dataset_name' => $datasetName,
            'dataset_version' => $datasetVersion,
            'from_database' => $fromDatabase,
            'ontology_digest' => $ontologyDigest,
            'safety' => $safety?->value,
            'to_database' => $toDatabase,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/database_join_drifts',
            body: $body,
            options: $options,
        );
        return EnvelopeDatabaseJoinDriftData::fromArray($response);
    }
}
