<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Service;

use Rafflesia\Resource\EnvelopeDatabaseJoinNeighborListData;

class DatabaseJoinNeighbors
{
    public function __construct(
        private readonly \Rafflesia\HttpClient $client,
    ) {
    }

    /**
     * @param string $database
     * @param string $release
     * @param string|null $relation
     * @param string|null $targetDatabase
     * @param \Rafflesia\Resource\DatabaseJoinsSafety $safety Defaults to "strict".
     * @param \Rafflesia\Resource\OntologyEvidence $evidence Defaults to "cardinality_consistent".
     * @param \Rafflesia\Resource\DatabaseJoinNeighborsAvailability $availability Defaults to "all".
     * @param bool|null $includeSameDatabase Defaults to false.
     * @param int|null $limit Defaults to 100.
     * @param string|null $cursor
     * @return \Rafflesia\PaginatedResponse<\Rafflesia\Resource\EnvelopeDatabaseJoinNeighborListData>
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function list(
        string $database,
        string $release,
        ?string $relation = null,
        ?string $targetDatabase = null,
        \Rafflesia\Resource\DatabaseJoinsSafety $safety = \Rafflesia\Resource\DatabaseJoinsSafety::Strict,
        \Rafflesia\Resource\OntologyEvidence $evidence = \Rafflesia\Resource\OntologyEvidence::CardinalityConsistent,
        \Rafflesia\Resource\DatabaseJoinNeighborsAvailability $availability = \Rafflesia\Resource\DatabaseJoinNeighborsAvailability::All,
        ?bool $includeSameDatabase = null,
        ?int $limit = null,
        ?string $cursor = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\PaginatedResponse {
        $query = array_filter([
            'database' => $database,
            'release' => $release,
            'relation' => $relation,
            'target_database' => $targetDatabase,
            'safety' => $safety->value,
            'evidence' => $evidence->value,
            'availability' => $availability->value,
            'include_same_database' => $includeSameDatabase,
            'limit' => $limit,
            'cursor' => $cursor,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/database_join_neighbors',
            query: $query,
            modelClass: EnvelopeDatabaseJoinNeighborListData::class,
            options: $options,
        );
    }
}
