<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Service;

use Rafflesia\Resource\EnvelopeEnvironmentTask;
use Rafflesia\Resource\EnvelopeListEnvironmentTask;

class EnvironmentTasks
{
    public function __construct(
        private readonly \Rafflesia\HttpClient $client,
    ) {
    }

    /**
     * @param string|null $environmentId
     * @param string|null $environmentReleaseId
     * @param int|null $limit Defaults to 25.
     * @param string|null $startingAfter
     * @return \Rafflesia\PaginatedResponse<\Rafflesia\Resource\EnvelopeListEnvironmentTask>
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function list(
        ?string $environmentId = null,
        ?string $environmentReleaseId = null,
        ?int $limit = null,
        ?string $startingAfter = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\PaginatedResponse {
        $query = array_filter([
            'environment_id' => $environmentId,
            'environment_release_id' => $environmentReleaseId,
            'limit' => $limit,
            'starting_after' => $startingAfter,
        ], fn ($v) => $v !== null);
        return $this->client->requestPage(
            method: 'GET',
            path: 'v1/environment_tasks',
            query: $query,
            modelClass: EnvelopeListEnvironmentTask::class,
            options: $options,
        );
    }

    /**
     * @param string $environmentTaskId
     * @return \Rafflesia\Resource\EnvelopeEnvironmentTask
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function get(
        string $environmentTaskId,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeEnvironmentTask {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/environment_tasks/' . rawurlencode($environmentTaskId),
            options: $options,
        );
        return EnvelopeEnvironmentTask::fromArray($response);
    }
}
