<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Service;

use Rafflesia\Resource\EnvelopeArtifactListData;
use Rafflesia\Resource\EnvelopeCatalogViewData;
use Rafflesia\Resource\EnvelopeJoinApproval;
use Rafflesia\Resource\EnvelopeJoinApprovalListData;
use Rafflesia\Resource\EnvelopeJoinEvidence;
use Rafflesia\Resource\EnvelopeJoinEvidenceListData;
use Rafflesia\Resource\EnvelopeMountListData;
use Rafflesia\Resource\EnvelopeMountUpsertData;
use Rafflesia\Resource\EnvelopeOnboardingStatusListData;
use Rafflesia\Resource\EnvelopePartnerArtifact;
use Rafflesia\Resource\EnvelopeRegistryRebuildDrillReceiptData;
use Rafflesia\Resource\EnvelopeRegistryReconciliationReceiptData;
use Rafflesia\Resource\EnvelopeRegistryReleaseDetailData;
use Rafflesia\Resource\EnvelopeRegistryReleaseListData;
use Rafflesia\Resource\EnvelopeRegistrySnapshotData;
use Rafflesia\Resource\EnvelopeRuntimeReconciliationListData;
use Rafflesia\Resource\EnvelopeRuntimeReconciliationReceipt;
use Rafflesia\Resource\EnvelopeSigningKeyListData;
use Rafflesia\Resource\EnvelopeTrustedSigningKey;

class Registry
{
    public function __construct(
        private readonly \Rafflesia\HttpClient $client,
    ) {
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeArtifactListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function artifactsList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeArtifactListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/artifacts',
            options: $options,
        );
        return EnvelopeArtifactListData::fromArray($response);
    }

    /**
     * @param string $artifactId
     * @param string $bindingId
     * @param string|null $contentBase64
     * @param string $filename
     * @param string $resourceGroupId
     * @param string|null $sourceUri
     * @return \Rafflesia\Resource\EnvelopePartnerArtifact
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function artifactsCreate(
        string $artifactId,
        string $bindingId,
        string $filename,
        string $resourceGroupId,
        ?string $contentBase64 = null,
        ?string $sourceUri = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopePartnerArtifact {
        $body = array_filter([
            'artifact_id' => $artifactId,
            'binding_id' => $bindingId,
            'content_base64' => $contentBase64,
            'filename' => $filename,
            'resource_group_id' => $resourceGroupId,
            'source_uri' => $sourceUri,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/registry/artifacts',
            body: $body,
            options: $options,
        );
        return EnvelopePartnerArtifact::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeCatalogViewData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function catalogViewGet(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeCatalogViewData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/catalog-view',
            options: $options,
        );
        return EnvelopeCatalogViewData::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeJoinApprovalListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function joinApprovalsList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeJoinApprovalListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/join-approvals',
            options: $options,
        );
        return EnvelopeJoinApprovalListData::fromArray($response);
    }

    /**
     * @param string $evidenceId
     * @param string $reason
     * @return \Rafflesia\Resource\EnvelopeJoinApproval
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function joinApprovalsCreate(
        string $evidenceId,
        string $reason,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeJoinApproval {
        $body = [
            'evidence_id' => $evidenceId,
            'reason' => $reason,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/registry/join-approvals',
            body: $body,
            options: $options,
        );
        return EnvelopeJoinApproval::fromArray($response);
    }

    /**
     * @param string $approvalId
     * @return \Rafflesia\Resource\EnvelopeJoinApproval
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function joinApprovalsGet(
        string $approvalId,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeJoinApproval {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/join-approvals/' . rawurlencode($approvalId),
            options: $options,
        );
        return EnvelopeJoinApproval::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeJoinEvidenceListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function joinEvidenceList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeJoinEvidenceListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/join-evidence',
            options: $options,
        );
        return EnvelopeJoinEvidenceListData::fromArray($response);
    }

    /**
     * @param \Rafflesia\Resource\JoinSide $from
     * @param \Rafflesia\Resource\OntologyKeyVariant|null $keyVariant
     * @param string $measurementArtifactId
     * @param string $measurementDigest
     * @param \Rafflesia\Resource\JoinMeasurements $measurements
     * @param string $observedAt
     * @param string $ontologyDigest
     * @param string $ontologyModuleReleaseId
     * @param string $relationshipId
     * @param string $resourceGroupId
     * @param \Rafflesia\Resource\JoinSide $to
     * @param string $tool
     * @param string $toolVersion
     * @return \Rafflesia\Resource\EnvelopeJoinEvidence
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function joinEvidenceCreate(
        \Rafflesia\Resource\JoinSide $from,
        string $measurementArtifactId,
        string $measurementDigest,
        \Rafflesia\Resource\JoinMeasurements $measurements,
        string $observedAt,
        string $ontologyDigest,
        string $ontologyModuleReleaseId,
        string $relationshipId,
        string $resourceGroupId,
        \Rafflesia\Resource\JoinSide $to,
        string $tool,
        string $toolVersion,
        ?\Rafflesia\Resource\OntologyKeyVariant $keyVariant = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeJoinEvidence {
        $body = array_filter([
            'from' => $from,
            'key_variant' => $keyVariant?->value,
            'measurement_artifact_id' => $measurementArtifactId,
            'measurement_digest' => $measurementDigest,
            'measurements' => $measurements,
            'observed_at' => $observedAt,
            'ontology_digest' => $ontologyDigest,
            'ontology_module_release_id' => $ontologyModuleReleaseId,
            'relationship_id' => $relationshipId,
            'resource_group_id' => $resourceGroupId,
            'to' => $to,
            'tool' => $tool,
            'tool_version' => $toolVersion,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/registry/join-evidence',
            body: $body,
            options: $options,
        );
        return EnvelopeJoinEvidence::fromArray($response);
    }

    /**
     * @param string $fromDatabase
     * @param string $fromRelease
     * @param \Rafflesia\Resource\OntologyKeyVariant|null $keyVariant
     * @param string $relationshipId
     * @param string $resourceGroupId
     * @param string $toDatabase
     * @param string $toRelease
     * @return \Rafflesia\Resource\EnvelopeJoinEvidence
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function joinProfilesCreate(
        string $fromDatabase,
        string $fromRelease,
        string $relationshipId,
        string $resourceGroupId,
        string $toDatabase,
        string $toRelease,
        ?\Rafflesia\Resource\OntologyKeyVariant $keyVariant = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeJoinEvidence {
        $body = array_filter([
            'from_database' => $fromDatabase,
            'from_release' => $fromRelease,
            'key_variant' => $keyVariant?->value,
            'relationship_id' => $relationshipId,
            'resource_group_id' => $resourceGroupId,
            'to_database' => $toDatabase,
            'to_release' => $toRelease,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/registry/join-profiles',
            body: $body,
            options: $options,
        );
        return EnvelopeJoinEvidence::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeMountListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function mountsList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeMountListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/mounts',
            options: $options,
        );
        return EnvelopeMountListData::fromArray($response);
    }

    /**
     * @param string $mountId
     * @param string $signature
     * @param string $signingKeyId
     * @param string $signingPublicKey
     * @param \Rafflesia\Resource\Snapshot $snapshot
     * @return \Rafflesia\Resource\EnvelopeMountUpsertData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function mountsUpsert(
        string $mountId,
        string $signature,
        string $signingKeyId,
        string $signingPublicKey,
        \Rafflesia\Resource\Snapshot $snapshot,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeMountUpsertData {
        $body = [
            'signature' => $signature,
            'signing_key_id' => $signingKeyId,
            'signing_public_key' => $signingPublicKey,
            'snapshot' => $snapshot,
        ];
        $response = $this->client->request(
            method: 'PUT',
            path: 'v1/registry/mounts/' . rawurlencode($mountId),
            body: $body,
            options: $options,
        );
        return EnvelopeMountUpsertData::fromArray($response);
    }

    /**
     * @param string $mountId
     * @param \Rafflesia\Resource\RegistryMountStatus $status
     * @return \Rafflesia\Resource\EnvelopeMountUpsertData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function mountsStatusUpdate(
        string $mountId,
        \Rafflesia\Resource\RegistryMountStatus $status,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeMountUpsertData {
        $body = [
            'status' => $status->value,
        ];
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v1/registry/mounts/' . rawurlencode($mountId),
            body: $body,
            options: $options,
        );
        return EnvelopeMountUpsertData::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeOnboardingStatusListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function onboardingStatusesList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeOnboardingStatusListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/onboarding-statuses',
            options: $options,
        );
        return EnvelopeOnboardingStatusListData::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeRegistryRebuildDrillReceiptData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function rebuildDrillsLatest(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRegistryRebuildDrillReceiptData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/rebuild-drills/latest',
            options: $options,
        );
        return EnvelopeRegistryRebuildDrillReceiptData::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeRegistryReconciliationReceiptData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function reconciliationReceiptsLatest(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRegistryReconciliationReceiptData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/reconciliation-receipts/latest',
            options: $options,
        );
        return EnvelopeRegistryReconciliationReceiptData::fromArray($response);
    }

    /**
     * @param string|null $selector
     * @param \Rafflesia\Resource\RegistryKind|null $kind
     * @return \Rafflesia\Resource\EnvelopeRegistryReleaseDetailData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function releaseGet(
        ?string $selector = null,
        ?\Rafflesia\Resource\RegistryKind $kind = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRegistryReleaseDetailData {
        $query = array_filter([
            'selector' => $selector,
            'kind' => $kind?->value,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/release',
            query: $query,
            options: $options,
        );
        return EnvelopeRegistryReleaseDetailData::fromArray($response);
    }

    /**
     * @param \Rafflesia\Resource\RegistryKind|null $kind
     * @param string|null $selector
     * @return \Rafflesia\Resource\EnvelopeRegistryReleaseListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function releasesList(
        ?\Rafflesia\Resource\RegistryKind $kind = null,
        ?string $selector = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRegistryReleaseListData {
        $query = array_filter([
            'kind' => $kind?->value,
            'selector' => $selector,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/releases',
            query: $query,
            options: $options,
        );
        return EnvelopeRegistryReleaseListData::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeRuntimeReconciliationListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function runtimeReconciliationsList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRuntimeReconciliationListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/runtime-reconciliations',
            options: $options,
        );
        return EnvelopeRuntimeReconciliationListData::fromArray($response);
    }

    /**
     * @param array<\Rafflesia\Resource\RuntimeObservation>|null $observations
     * @param string $resourceGroupId
     * @return \Rafflesia\Resource\EnvelopeRuntimeReconciliationReceipt
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function runtimeReconciliationsCreate(
        ?array $observations,
        string $resourceGroupId,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRuntimeReconciliationReceipt {
        $body = [
            'observations' => $observations,
            'resource_group_id' => $resourceGroupId,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/registry/runtime-reconciliations',
            body: $body,
            options: $options,
        );
        return EnvelopeRuntimeReconciliationReceipt::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeSigningKeyListData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function signingKeysList(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeSigningKeyListData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/signing-keys',
            options: $options,
        );
        return EnvelopeSigningKeyListData::fromArray($response);
    }

    /**
     * @param string $id
     * @param string $publicKey
     * @return \Rafflesia\Resource\EnvelopeTrustedSigningKey
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function signingKeysCreate(
        string $id,
        string $publicKey,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeTrustedSigningKey {
        $body = [
            'id' => $id,
            'public_key' => $publicKey,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/registry/signing-keys',
            body: $body,
            options: $options,
        );
        return EnvelopeTrustedSigningKey::fromArray($response);
    }

    /**
     * @param string $keyId
     * @param \Rafflesia\Resource\TrustedSigningKeyStatus $status
     * @return \Rafflesia\Resource\EnvelopeTrustedSigningKey
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function signingKeysStatusUpdate(
        string $keyId,
        \Rafflesia\Resource\TrustedSigningKeyStatus $status,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeTrustedSigningKey {
        $body = [
            'status' => $status->value,
        ];
        $response = $this->client->request(
            method: 'PATCH',
            path: 'v1/registry/signing-keys/' . rawurlencode($keyId),
            body: $body,
            options: $options,
        );
        return EnvelopeTrustedSigningKey::fromArray($response);
    }

    /**
     * @return \Rafflesia\Resource\EnvelopeRegistrySnapshotData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function snapshotGet(
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRegistrySnapshotData {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/registry/snapshot',
            options: $options,
        );
        return EnvelopeRegistrySnapshotData::fromArray($response);
    }
}
