<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Service;

use Rafflesia\Resource\EnvelopeRqlFormatData;

class RqlFormats
{
    public function __construct(
        private readonly \Rafflesia\HttpClient $client,
    ) {
    }

    /**
     * @param string $sourceText
     * @return \Rafflesia\Resource\EnvelopeRqlFormatData
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function create(
        string $sourceText,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\EnvelopeRqlFormatData {
        $body = [
            'source_text' => $sourceText,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/rql_formats',
            body: $body,
            options: $options,
        );
        return EnvelopeRqlFormatData::fromArray($response);
    }
}
