<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Service;

use Rafflesia\Resource\ExecutionEnvelopeWebhookDelivery;
use Rafflesia\Resource\ExecutionEnvelopeWebhookDeliveryList;

class WebhookDeliveries
{
    public function __construct(
        private readonly \Rafflesia\HttpClient $client,
    ) {
    }

    /**
     * List webhook deliveries
     * @param string|null $endpointId
     * @param string|null $eventId
     * @param \Rafflesia\Resource\WebhookDeliveryStatus|null $status
     * @param int|null $limit Defaults to 20.
     * @param string|null $startingAfter
     * @return \Rafflesia\Resource\ExecutionEnvelopeWebhookDeliveryList
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function list(
        ?string $endpointId = null,
        ?string $eventId = null,
        ?\Rafflesia\Resource\WebhookDeliveryStatus $status = null,
        ?int $limit = null,
        ?string $startingAfter = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\ExecutionEnvelopeWebhookDeliveryList {
        $query = array_filter([
            'endpoint_id' => $endpointId,
            'event_id' => $eventId,
            'status' => $status?->value,
            'limit' => $limit,
            'starting_after' => $startingAfter,
        ], fn ($v) => $v !== null);
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/webhooks/deliveries',
            query: $query,
            options: $options,
        );
        return ExecutionEnvelopeWebhookDeliveryList::fromArray($response);
    }

    /**
     * Create a webhook delivery
     *
     * Creates a new delivery for an existing immutable event and endpoint. Repeating this operation is an explicit manual replay.
     * @param string|null $idempotencyKey Retry identity for this exact manual event delivery.
     * @param string $endpointId
     * @param string $eventId
     * @return \Rafflesia\Resource\ExecutionEnvelopeWebhookDelivery
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function create(
        string $endpointId,
        string $eventId,
        ?string $idempotencyKey = null,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\ExecutionEnvelopeWebhookDelivery {
        $headers = array_filter([
            'Idempotency-Key' => $idempotencyKey,
        ], fn ($v) => $v !== null);
        $body = [
            'endpoint_id' => $endpointId,
            'event_id' => $eventId,
        ];
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/webhooks/deliveries',
            body: $body,
            headers: $headers,
            options: $options,
        );
        return ExecutionEnvelopeWebhookDelivery::fromArray($response);
    }

    /**
     * Retrieve a webhook delivery
     * @param string $deliveryId
     * @return \Rafflesia\Resource\ExecutionEnvelopeWebhookDelivery
     * @throws \Rafflesia\Exception\RafflesiaException
     */
    public function retrieve(
        string $deliveryId,
        ?\Rafflesia\RequestOptions $options = null,
    ): \Rafflesia\Resource\ExecutionEnvelopeWebhookDelivery {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/webhooks/deliveries/' . rawurlencode((string) $deliveryId),
            options: $options,
        );
        return ExecutionEnvelopeWebhookDelivery::fromArray($response);
    }
}
