<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum ApiErrorBodyType: string
{
    case InvalidRequestError = 'invalid_request_error';
    case ResourceMissing = 'resource_missing';
    case ResourceExpired = 'resource_expired';
    case ConflictError = 'conflict_error';
    case RateLimitError = 'rate_limit_error';
    case AuthenticationError = 'authentication_error';
    case PermissionError = 'permission_error';
    case BillingError = 'billing_error';
    case ApiError = 'api_error';
}
