<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ApiKeyListData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\ApiKeyInfo>|null */
        public ?array $apiKeys,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'api_keys',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ApiKeyListData::fromArray()");
            }
        }
        return new self(
            apiKeys: isset($data['api_keys']) ? array_map(fn ($item) => ApiKeyInfo::fromArray($item), $data['api_keys']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'api_keys' => $this->apiKeys !== null ? array_map(fn ($item) => $item->toArray(), $this->apiKeys) : null,
        ];
    }
}
