<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class AromaticStackingDetectData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public float $maxCentroid,
        /** @var array<\Rafflesia\Resource\AromaticPairRecord>|null */
        public ?array $pairs,
        public string $structureId,
        public AromaticStackingSummaryData $summary,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'max_centroid',
            'pairs',
            'structure_id',
            'summary',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for AromaticStackingDetectData::fromArray()");
            }
        }
        return new self(
            maxCentroid: $data['max_centroid'],
            pairs: isset($data['pairs']) ? array_map(fn ($item) => AromaticPairRecord::fromArray($item), $data['pairs']) : null,
            structureId: $data['structure_id'],
            summary: AromaticStackingSummaryData::fromArray($data['summary']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'max_centroid' => $this->maxCentroid,
            'pairs' => $this->pairs !== null ? array_map(fn ($item) => $item->toArray(), $this->pairs) : null,
            'structure_id' => $this->structureId,
            'summary' => $this->summary->toArray(),
        ];
    }
}
