<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ArtifactManifest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $manifestId,
        public int $manifestVersion,
        /** @var array<\Rafflesia\Resource\ArtifactPaper>|null */
        public ?array $papers,
        public ?string $createdAt = null,
        public ?string $description = null,
        public ?string $label = null,
        public ?string $source = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'manifest_id',
            'manifest_version',
            'papers',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ArtifactManifest::fromArray()");
            }
        }
        return new self(
            manifestId: $data['manifest_id'],
            manifestVersion: $data['manifest_version'],
            papers: isset($data['papers']) ? array_map(fn ($item) => ArtifactPaper::fromArray($item), $data['papers']) : null,
            createdAt: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            label: $data['label'] ?? null,
            source: $data['source'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'manifest_id' => $this->manifestId,
            'manifest_version' => $this->manifestVersion,
            'papers' => $this->papers !== null ? array_map(fn ($item) => $item->toArray(), $this->papers) : null,
            'created_at' => $this->createdAt,
            'description' => $this->description,
            'label' => $this->label,
            'source' => $this->source,
        ];
    }
}
