<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ArtifactUploadRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $artifactId,
        public string $bindingId,
        public string $filename,
        public string $resourceGroupId,
        public ?string $contentBase64 = null,
        public ?string $sourceUri = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'artifact_id',
            'binding_id',
            'filename',
            'resource_group_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ArtifactUploadRequest::fromArray()");
            }
        }
        return new self(
            artifactId: $data['artifact_id'],
            bindingId: $data['binding_id'],
            filename: $data['filename'],
            resourceGroupId: $data['resource_group_id'],
            contentBase64: $data['content_base64'] ?? null,
            sourceUri: $data['source_uri'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'artifact_id' => $this->artifactId,
            'binding_id' => $this->bindingId,
            'filename' => $this->filename,
            'resource_group_id' => $this->resourceGroupId,
            'content_base64' => $this->contentBase64,
            'source_uri' => $this->sourceUri,
        ];
    }
}
