<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class AuditLogActor implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $apiKeyId = null,
        public ?string $authMethod = null,
        public ?string $credentialId = null,
        public ?string $email = null,
        public ?string $environmentId = null,
        public ?string $environmentName = null,
        public ?string $environmentType = null,
        public ?string $keyName = null,
        public ?string $keyPrefix = null,
        public ?string $organizationId = null,
        public ?string $userId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            apiKeyId: $data['api_key_id'] ?? null,
            authMethod: $data['auth_method'] ?? null,
            credentialId: $data['credential_id'] ?? null,
            email: $data['email'] ?? null,
            environmentId: $data['environment_id'] ?? null,
            environmentName: $data['environment_name'] ?? null,
            environmentType: $data['environment_type'] ?? null,
            keyName: $data['key_name'] ?? null,
            keyPrefix: $data['key_prefix'] ?? null,
            organizationId: $data['organization_id'] ?? null,
            userId: $data['user_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'api_key_id' => $this->apiKeyId,
            'auth_method' => $this->authMethod,
            'credential_id' => $this->credentialId,
            'email' => $this->email,
            'environment_id' => $this->environmentId,
            'environment_name' => $this->environmentName,
            'environment_type' => $this->environmentType,
            'key_name' => $this->keyName,
            'key_prefix' => $this->keyPrefix,
            'organization_id' => $this->organizationId,
            'user_id' => $this->userId,
        ];
    }
}
