<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class AuthUser implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $email,
        public bool $emailVerified,
        public string $id,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?string $name = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'email',
            'email_verified',
            'id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for AuthUser::fromArray()");
            }
        }
        return new self(
            email: $data['email'],
            emailVerified: $data['email_verified'],
            id: $data['id'],
            firstName: $data['first_name'] ?? null,
            lastName: $data['last_name'] ?? null,
            name: $data['name'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'email_verified' => $this->emailVerified,
            'id' => $this->id,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'name' => $this->name,
        ];
    }
}
