<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class BillingCheckoutSessionRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $organizationId,
        public ?string $email = null,
        public ?string $plan = null,
        public ?string $planId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'organization_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for BillingCheckoutSessionRequest::fromArray()");
            }
        }
        return new self(
            organizationId: $data['organization_id'],
            email: $data['email'] ?? null,
            plan: $data['plan'] ?? null,
            planId: $data['plan_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'email' => $this->email,
            'plan' => $this->plan,
            'plan_id' => $this->planId,
        ];
    }
}
