<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum BlastDbBuildRequestMolecule: string
{
    case Nucl = 'nucl';
    case Prot = 'prot';
}
