<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class BlastSearchProfile implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Materializing BLAST DB artifacts into the local cache (S3 download on a cold cache). */
        public int $materializeDbMs,
        /** Resolving the query path or cached sequence id. */
        public int $resolveQueryMs,
        /** Wall-clock spent running BLAST, or sharded BLAST scatter-gather subprocesses. */
        public int $searchMs,
        /** Storing normalized/raw output objects. */
        public int $storeOutputMs,
        /** Total handler wall-clock. */
        public int $totalMs,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'materialize_db_ms',
            'resolve_query_ms',
            'search_ms',
            'store_output_ms',
            'total_ms',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for BlastSearchProfile::fromArray()");
            }
        }
        return new self(
            materializeDbMs: $data['materialize_db_ms'],
            resolveQueryMs: $data['resolve_query_ms'],
            searchMs: $data['search_ms'],
            storeOutputMs: $data['store_output_ms'],
            totalMs: $data['total_ms'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'materialize_db_ms' => $this->materializeDbMs,
            'resolve_query_ms' => $this->resolveQueryMs,
            'search_ms' => $this->searchMs,
            'store_output_ms' => $this->storeOutputMs,
            'total_ms' => $this->totalMs,
        ];
    }
}
