<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class BlastSearchShardData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $db,
        public int $hitCount,
        public string $shardId,
        public bool $wasExecuted,
        /** @var array<string>|null */
        public ?array $command = null,
        public ?string $dbPrefix = null,
        public ?int $elapsedMs = null,
        public ?string $indexFormat = null,
        public ?string $manifestId = null,
        public ?BlastDbMaterializeData $materialization = null,
        public ?string $outputPath = null,
        public ?ObjectRef $rawOutputObject = null,
        public ?int $warningCount = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'db',
            'hit_count',
            'shard_id',
            'was_executed',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for BlastSearchShardData::fromArray()");
            }
        }
        return new self(
            db: $data['db'],
            hitCount: $data['hit_count'],
            shardId: $data['shard_id'],
            wasExecuted: $data['was_executed'],
            command: $data['command'] ?? null,
            dbPrefix: $data['db_prefix'] ?? null,
            elapsedMs: $data['elapsed_ms'] ?? null,
            indexFormat: $data['index_format'] ?? null,
            manifestId: $data['manifest_id'] ?? null,
            materialization: isset($data['materialization']) ? BlastDbMaterializeData::fromArray($data['materialization']) : null,
            outputPath: $data['output_path'] ?? null,
            rawOutputObject: isset($data['raw_output_object']) ? ObjectRef::fromArray($data['raw_output_object']) : null,
            warningCount: $data['warning_count'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'db' => $this->db,
            'hit_count' => $this->hitCount,
            'shard_id' => $this->shardId,
            'was_executed' => $this->wasExecuted,
            'command' => $this->command,
            'db_prefix' => $this->dbPrefix,
            'elapsed_ms' => $this->elapsedMs,
            'index_format' => $this->indexFormat,
            'manifest_id' => $this->manifestId,
            'materialization' => $this->materialization?->toArray(),
            'output_path' => $this->outputPath,
            'raw_output_object' => $this->rawOutputObject?->toArray(),
            'warning_count' => $this->warningCount,
        ];
    }
}
