<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CacheMaterializationMetrics implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?bool $allCacheHits = null,
        public ?int $cacheHitBytes = null,
        public ?int $cacheHitCount = null,
        public ?int $cacheMissBytes = null,
        public ?int $cacheMissCount = null,
        /** Wall-clock spent in the materialization call. */
        public ?int $elapsedMs = null,
        public ?int $fileCount = null,
        /** Aggregate time spent waiting for per-file materialization locks. */
        public ?int $lockWaitMs = null,
        /** Whether this request acquired the materialization claim. */
        public ?bool $materializationAcquired = null,
        /** Control-plane cache materialization key. */
        public ?string $materializationKey = null,
        /** Process id that claimed the materialization key. */
        public ?string $materializationOwnerId = null,
        /** Whether this request observed another active or ready materialization for the same key. */
        public ?bool $materializationShared = null,
        /** Control-plane cache materialization status. */
        public ?string $materializationStatus = null,
        /** Time spent waiting for another materialization claim. */
        public ?int $materializationWaitMs = null,
        /** Observed bytes opened from Store.OpenObject while materializing cold or stale cache files. */
        public ?int $objectReadBytes = null,
        /** Observed Store.OpenObject reads performed while materializing cold or stale cache files. */
        public ?int $objectReadCount = null,
        /** @var array<string>|null */
        public ?array $objectStorageBackends = null,
        public ?int $totalSizeBytes = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            allCacheHits: $data['all_cache_hits'] ?? null,
            cacheHitBytes: $data['cache_hit_bytes'] ?? null,
            cacheHitCount: $data['cache_hit_count'] ?? null,
            cacheMissBytes: $data['cache_miss_bytes'] ?? null,
            cacheMissCount: $data['cache_miss_count'] ?? null,
            elapsedMs: $data['elapsed_ms'] ?? null,
            fileCount: $data['file_count'] ?? null,
            lockWaitMs: $data['lock_wait_ms'] ?? null,
            materializationAcquired: $data['materialization_acquired'] ?? null,
            materializationKey: $data['materialization_key'] ?? null,
            materializationOwnerId: $data['materialization_owner_id'] ?? null,
            materializationShared: $data['materialization_shared'] ?? null,
            materializationStatus: $data['materialization_status'] ?? null,
            materializationWaitMs: $data['materialization_wait_ms'] ?? null,
            objectReadBytes: $data['object_read_bytes'] ?? null,
            objectReadCount: $data['object_read_count'] ?? null,
            objectStorageBackends: $data['object_storage_backends'] ?? null,
            totalSizeBytes: $data['total_size_bytes'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'all_cache_hits' => $this->allCacheHits,
            'cache_hit_bytes' => $this->cacheHitBytes,
            'cache_hit_count' => $this->cacheHitCount,
            'cache_miss_bytes' => $this->cacheMissBytes,
            'cache_miss_count' => $this->cacheMissCount,
            'elapsed_ms' => $this->elapsedMs,
            'file_count' => $this->fileCount,
            'lock_wait_ms' => $this->lockWaitMs,
            'materialization_acquired' => $this->materializationAcquired,
            'materialization_key' => $this->materializationKey,
            'materialization_owner_id' => $this->materializationOwnerId,
            'materialization_shared' => $this->materializationShared,
            'materialization_status' => $this->materializationStatus,
            'materialization_wait_ms' => $this->materializationWaitMs,
            'object_read_bytes' => $this->objectReadBytes,
            'object_read_count' => $this->objectReadCount,
            'object_storage_backends' => $this->objectStorageBackends,
            'total_size_bytes' => $this->totalSizeBytes,
        ];
    }
}
