<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CacheWarmWorkloadRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Cache workload to materialize. */
        public CacheWarmWorkloadRequestWorkload $workload,
        /** Manifest object id for object_artifact or fold_index workloads. */
        public ?string $manifestObjectId = null,
        /** Local manifest path for object_artifact, blast, diamond, or fold_index workloads. */
        public ?string $manifestPath = null,
        /** Published BLAST DB, DIAMOND DB, or Foldseek index ref. */
        public ?string $ref = null,
        /**
         * Optional Foldseek segment roles for fold_index workloads: search_index, routing_index.
         * @var array<string>|null
         */
        public ?array $segmentRoles = null,
        /**
         * Optional shard ids for object_artifact and fold_index workloads.
         * @var array<string>|null
         */
        public ?array $shards = null,
        /** Local cache root used for this workload; defaults to request target_dir. */
        public ?string $targetDir = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'workload',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CacheWarmWorkloadRequest::fromArray()");
            }
        }
        return new self(
            workload: CacheWarmWorkloadRequestWorkload::from($data['workload']),
            manifestObjectId: $data['manifest_object_id'] ?? null,
            manifestPath: $data['manifest_path'] ?? null,
            ref: $data['ref'] ?? null,
            segmentRoles: $data['segment_roles'] ?? null,
            shards: $data['shards'] ?? null,
            targetDir: $data['target_dir'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'workload' => $this->workload->value,
            'manifest_object_id' => $this->manifestObjectId,
            'manifest_path' => $this->manifestPath,
            'ref' => $this->ref,
            'segment_roles' => $this->segmentRoles,
            'shards' => $this->shards,
            'target_dir' => $this->targetDir,
        ];
    }
}
