<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ChainSummary implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $atomCount,
        public string $chainId,
        public int $residueCount,
        /** @var array<string>|null */
        public ?array $assemblyIds = null,
        /** @var array<string>|null */
        public ?array $authChainIds = null,
        public ?CartesianBounds $bounds = null,
        /** @var array<float>|null */
        public ?array $centroid = null,
        public ?int $end = null,
        /** @var array<string>|null */
        public ?array $entityIds = null,
        /** @var array<string>|null */
        public ?array $labelChainIds = null,
        /** @var array<string>|null */
        public ?array $modelIds = null,
        public ?string $polymerType = null,
        public ?string $sequence = null,
        public ?string $sequenceSha256 = null,
        public ?int $start = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'atom_count',
            'chain_id',
            'residue_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ChainSummary::fromArray()");
            }
        }
        return new self(
            atomCount: $data['atom_count'],
            chainId: $data['chain_id'],
            residueCount: $data['residue_count'],
            assemblyIds: $data['assembly_ids'] ?? null,
            authChainIds: $data['auth_chain_ids'] ?? null,
            bounds: isset($data['bounds']) ? CartesianBounds::fromArray($data['bounds']) : null,
            centroid: $data['centroid'] ?? null,
            end: $data['end'] ?? null,
            entityIds: $data['entity_ids'] ?? null,
            labelChainIds: $data['label_chain_ids'] ?? null,
            modelIds: $data['model_ids'] ?? null,
            polymerType: $data['polymer_type'] ?? null,
            sequence: $data['sequence'] ?? null,
            sequenceSha256: $data['sequence_sha256'] ?? null,
            start: $data['start'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'atom_count' => $this->atomCount,
            'chain_id' => $this->chainId,
            'residue_count' => $this->residueCount,
            'assembly_ids' => $this->assemblyIds,
            'auth_chain_ids' => $this->authChainIds,
            'bounds' => $this->bounds?->toArray(),
            'centroid' => $this->centroid,
            'end' => $this->end,
            'entity_ids' => $this->entityIds,
            'label_chain_ids' => $this->labelChainIds,
            'model_ids' => $this->modelIds,
            'polymer_type' => $this->polymerType,
            'sequence' => $this->sequence,
            'sequence_sha256' => $this->sequenceSha256,
            'start' => $this->start,
        ];
    }
}
