<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum CorpuReleaseCostObservationSeverity: string
{
    case Info = 'info';
    case Warning = 'warning';
    case Error = 'error';
}
