<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CorpuReleaseAuditRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Content-addressed audit object id to decode directly. */
        public ?string $auditObjectId = null,
        /** Immutable corpus name. Required when ref and audit_object_id are omitted. */
        public ?string $corpus = null,
        /** Optional local or object-storage root. Defaults to the API server's release data root. */
        public ?string $objectStoreRoot = null,
        /** Optional immutable release ref formatted as corpus:release_id. When set, the audit chain for the corpus is searched for this release. */
        public ?string $ref = null,
        /** Immutable release id. Required with corpus when ref and audit_object_id are omitted. */
        public ?string $releaseId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            auditObjectId: $data['audit_object_id'] ?? null,
            corpus: $data['corpus'] ?? null,
            objectStoreRoot: $data['object_store_root'] ?? null,
            ref: $data['ref'] ?? null,
            releaseId: $data['release_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'audit_object_id' => $this->auditObjectId,
            'corpus' => $this->corpus,
            'object_store_root' => $this->objectStoreRoot,
            'ref' => $this->ref,
            'release_id' => $this->releaseId,
        ];
    }
}
