<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum CorpuReleaseSearchRequestStructureSearchPreset: string
{
    case Cheap = 'cheap';
    case Balanced = 'balanced';
    case RemoteHomologySensitive = 'remote_homology_sensitive';
    case FoldseekLikeSensitive = 'foldseek_like_sensitive';
    case StructureRecallMax = 'structure_recall_max';
}
