<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum CorpuReleaseSearchRequestSequencePlannerMode: string
{
    case V2 = 'v2';
    case V3 = 'v3';
    case V4 = 'v4';
    case V5 = 'v5';
    case V7 = 'v7';
    case V8 = 'v8';
}
