<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CorpuReleaseGcPlanRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Corpus whose catalog releases should be considered for GC. */
        public string $corpus,
        /** Keep true for a planning-only run. This primitive does not delete object bytes. */
        public ?bool $dryRun = null,
        /** Maximum release catalog rows to inspect. Defaults to 1000. */
        public ?int $limit = null,
        /** Optional stable GC plan id. Defaults to a deterministic timestamped id. */
        public ?string $planId = null,
        /** Keep at least this many newest releases in addition to current and pinned releases. Defaults to 2. */
        public ?int $retainLast = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'corpus',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CorpuReleaseGcPlanRequest::fromArray()");
            }
        }
        return new self(
            corpus: $data['corpus'],
            dryRun: $data['dry_run'] ?? null,
            limit: $data['limit'] ?? null,
            planId: $data['plan_id'] ?? null,
            retainLast: $data['retain_last'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'corpus' => $this->corpus,
            'dry_run' => $this->dryRun,
            'limit' => $this->limit,
            'plan_id' => $this->planId,
            'retain_last' => $this->retainLast,
        ];
    }
}
