<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CorpuReleaseValidateData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        public string $corpus,
        public string $objectStoreRoot,
        public bool $ok,
        public string $ref,
        public CorpuReleaseRecord $release,
        public string $releaseId,
        /** @var array<\Rafflesia\Resource\CorpuReleasePublishGate>|null */
        public ?array $gates = null,
        public ?CorpuReleaseSearchData $smokeSearch = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'corpus',
            'object_store_root',
            'ok',
            'ref',
            'release',
            'release_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CorpuReleaseValidateData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            corpus: $data['corpus'],
            objectStoreRoot: $data['object_store_root'],
            ok: $data['ok'],
            ref: $data['ref'],
            release: CorpuReleaseRecord::fromArray($data['release']),
            releaseId: $data['release_id'],
            gates: isset($data['gates']) ? array_map(fn ($item) => CorpuReleasePublishGate::fromArray($item), $data['gates']) : null,
            smokeSearch: isset($data['smoke_search']) ? CorpuReleaseSearchData::fromArray($data['smoke_search']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'corpus' => $this->corpus,
            'object_store_root' => $this->objectStoreRoot,
            'ok' => $this->ok,
            'ref' => $this->ref,
            'release' => $this->release->toArray(),
            'release_id' => $this->releaseId,
            'gates' => $this->gates !== null ? array_map(fn ($item) => $item->toArray(), $this->gates) : null,
            'smoke_search' => $this->smokeSearch?->toArray(),
        ];
    }
}
