<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CorpuReleaseSearchData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        public string $corpus,
        public string $engine,
        public string $family,
        /** @var array<\Rafflesia\Resource\CorpuReleaseHit>|null */
        public ?array $hits,
        public int $materializedDatabaseBytes,
        public string $objectStoreRoot,
        public CorpuReleaseSearchProvenance $provenance,
        public SequenceSeedIndexObjectReadBudget $readBudget,
        public string $releaseId,
        /**
         * Planner candidate record IDs before payload promotion or final ranking.
         * @var array<string>|null
         */
        public ?array $candidateIds = null,
        public ?CorpuReleaseExactRerankData $exactRerank = null,
        /**
         * Candidate record IDs whose payloads were fetched for scoring or verification.
         * @var array<string>|null
         */
        public ?array $payloadCandidateIds = null,
        public ?CorpuReleaseStructureTokenExtractionData $queryStructureTokenExtraction = null,
        public ?CorpuReleaseSequenceQueryTraceData $sequenceQueryTrace = null,
        /**
         * Candidate record IDs scored by the exact verifier.
         * @var array<string>|null
         */
        public ?array $verifiedCandidateIds = null,
        /** @var array<string>|null */
        public ?array $warnings = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'corpus',
            'engine',
            'family',
            'hits',
            'materialized_database_bytes',
            'object_store_root',
            'provenance',
            'read_budget',
            'release_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CorpuReleaseSearchData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            corpus: $data['corpus'],
            engine: $data['engine'],
            family: $data['family'],
            hits: isset($data['hits']) ? array_map(fn ($item) => CorpuReleaseHit::fromArray($item), $data['hits']) : null,
            materializedDatabaseBytes: $data['materialized_database_bytes'],
            objectStoreRoot: $data['object_store_root'],
            provenance: CorpuReleaseSearchProvenance::fromArray($data['provenance']),
            readBudget: SequenceSeedIndexObjectReadBudget::fromArray($data['read_budget']),
            releaseId: $data['release_id'],
            candidateIds: $data['candidate_ids'] ?? null,
            exactRerank: isset($data['exact_rerank']) ? CorpuReleaseExactRerankData::fromArray($data['exact_rerank']) : null,
            payloadCandidateIds: $data['payload_candidate_ids'] ?? null,
            queryStructureTokenExtraction: isset($data['query_structure_token_extraction']) ? CorpuReleaseStructureTokenExtractionData::fromArray($data['query_structure_token_extraction']) : null,
            sequenceQueryTrace: isset($data['sequence_query_trace']) ? CorpuReleaseSequenceQueryTraceData::fromArray($data['sequence_query_trace']) : null,
            verifiedCandidateIds: $data['verified_candidate_ids'] ?? null,
            warnings: $data['warnings'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'corpus' => $this->corpus,
            'engine' => $this->engine,
            'family' => $this->family,
            'hits' => $this->hits !== null ? array_map(fn ($item) => $item->toArray(), $this->hits) : null,
            'materialized_database_bytes' => $this->materializedDatabaseBytes,
            'object_store_root' => $this->objectStoreRoot,
            'provenance' => $this->provenance->toArray(),
            'read_budget' => $this->readBudget->toArray(),
            'release_id' => $this->releaseId,
            'candidate_ids' => $this->candidateIds,
            'exact_rerank' => $this->exactRerank?->toArray(),
            'payload_candidate_ids' => $this->payloadCandidateIds,
            'query_structure_token_extraction' => $this->queryStructureTokenExtraction?->toArray(),
            'sequence_query_trace' => $this->sequenceQueryTrace?->toArray(),
            'verified_candidate_ids' => $this->verifiedCandidateIds,
            'warnings' => $this->warnings,
        ];
    }
}
