<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CorpuReleaseListData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        public string $objectStoreRoot,
        public int $releaseCount,
        /** @var array<\Rafflesia\Resource\CorpuReleaseRecord>|null */
        public ?array $releases,
        public ?string $corpus = null,
        /** @var array<string, string>|null */
        public ?array $currentRefs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'object_store_root',
            'release_count',
            'releases',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CorpuReleaseListData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            objectStoreRoot: $data['object_store_root'],
            releaseCount: $data['release_count'],
            releases: isset($data['releases']) ? array_map(fn ($item) => CorpuReleaseRecord::fromArray($item), $data['releases']) : null,
            corpus: $data['corpus'] ?? null,
            currentRefs: $data['current_refs'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'object_store_root' => $this->objectStoreRoot,
            'release_count' => $this->releaseCount,
            'releases' => $this->releases !== null ? array_map(fn ($item) => $item->toArray(), $this->releases) : null,
            'corpus' => $this->corpus,
            'current_refs' => $this->currentRefs,
        ];
    }
}
