<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class CryoEmMapFetchRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $emdbId,
        public ?bool $allowNetwork = null,
        /** When true, download and store the EMDB voxel map object instead of metadata JSON. */
        public ?bool $includeVolume = null,
        /** Maximum EMDB volume download size in bytes; defaults to 500 MiB. */
        public ?int $maxDownloadBytes = null,
        /** Optional explicit EMDB map volume URL; defaults to the canonical EMDB FTP map path. */
        public ?string $volumeSourceUrl = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'emdb_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CryoEmMapFetchRequest::fromArray()");
            }
        }
        return new self(
            emdbId: $data['emdb_id'],
            allowNetwork: $data['allow_network'] ?? null,
            includeVolume: $data['include_volume'] ?? null,
            maxDownloadBytes: $data['max_download_bytes'] ?? null,
            volumeSourceUrl: $data['volume_source_url'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'emdb_id' => $this->emdbId,
            'allow_network' => $this->allowNetwork,
            'include_volume' => $this->includeVolume,
            'max_download_bytes' => $this->maxDownloadBytes,
            'volume_source_url' => $this->volumeSourceUrl,
        ];
    }
}
