<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetManifestScanEntry implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $datasetName,
        public string $datasetVersion,
        public int $failureCount,
        public bool $failureFree,
        public string $manifestPath,
        public string $manifestSha256,
        public string $modifiedAt,
        public int $rowCount,
        public int $structureCount,
        public int $tableArtifactCount,
        /** @var array<string>|null */
        public ?array $schemaHashes = null,
        public ?string $source = null,
        /** @var array<string, int>|null */
        public ?array $tableRowCounts = null,
        /** @var array<string>|null */
        public ?array $tables = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'dataset_name',
            'dataset_version',
            'failure_count',
            'failure_free',
            'manifest_path',
            'manifest_sha256',
            'modified_at',
            'row_count',
            'structure_count',
            'table_artifact_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetManifestScanEntry::fromArray()");
            }
        }
        return new self(
            datasetName: $data['dataset_name'],
            datasetVersion: $data['dataset_version'],
            failureCount: $data['failure_count'],
            failureFree: $data['failure_free'],
            manifestPath: $data['manifest_path'],
            manifestSha256: $data['manifest_sha256'],
            modifiedAt: $data['modified_at'],
            rowCount: $data['row_count'],
            structureCount: $data['structure_count'],
            tableArtifactCount: $data['table_artifact_count'],
            schemaHashes: $data['schema_hashes'] ?? null,
            source: $data['source'] ?? null,
            tableRowCounts: $data['table_row_counts'] ?? null,
            tables: $data['tables'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'dataset_name' => $this->datasetName,
            'dataset_version' => $this->datasetVersion,
            'failure_count' => $this->failureCount,
            'failure_free' => $this->failureFree,
            'manifest_path' => $this->manifestPath,
            'manifest_sha256' => $this->manifestSha256,
            'modified_at' => $this->modifiedAt,
            'row_count' => $this->rowCount,
            'structure_count' => $this->structureCount,
            'table_artifact_count' => $this->tableArtifactCount,
            'schema_hashes' => $this->schemaHashes,
            'source' => $this->source,
            'table_row_counts' => $this->tableRowCounts,
            'tables' => $this->tables,
        ];
    }
}
