<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum DatasetSourceSnapshotImportRequestImportMode: string
{
    case Catalog = 'catalog';
    case Streaming = 'streaming';
}
