<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinReleaseCertificationTarget implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $database,
        public bool $isComplete,
        public int $relationshipVariantCount,
        public string $release,
        public string $releaseDigest,
        public int $unavailableCount,
        public ?string $certificationId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'database',
            'is_complete',
            'relationship_variant_count',
            'release',
            'release_digest',
            'unavailable_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinReleaseCertificationTarget::fromArray()");
            }
        }
        return new self(
            database: $data['database'],
            isComplete: $data['is_complete'],
            relationshipVariantCount: $data['relationship_variant_count'],
            release: $data['release'],
            releaseDigest: $data['release_digest'],
            unavailableCount: $data['unavailable_count'],
            certificationId: $data['certification_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'database' => $this->database,
            'is_complete' => $this->isComplete,
            'relationship_variant_count' => $this->relationshipVariantCount,
            'release' => $this->release,
            'release_digest' => $this->releaseDigest,
            'unavailable_count' => $this->unavailableCount,
            'certification_id' => $this->certificationId,
        ];
    }
}
