<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinCoverageData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $cardinalityConsistentCount,
        public int $cardinalityContradictedCount,
        /** @var array<\Rafflesia\Resource\DatabaseJoinCoverageRow>|null */
        public ?array $data,
        public string $fromDatabase,
        public string $fromRelease,
        public string $id,
        public int $noOverlapObservedCount,
        public int $observedCount,
        public string $ontologyDigest,
        public string $ontologyVersion,
        public int $overlapObservedCount,
        public int $relationshipVariantCount,
        public string $toDatabase,
        public string $toRelease,
        public string $url,
        public string $object = 'database_join_coverage',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'cardinality_consistent_count',
            'cardinality_contradicted_count',
            'data',
            'from_database',
            'from_release',
            'id',
            'no_overlap_observed_count',
            'observed_count',
            'ontology_digest',
            'ontology_version',
            'overlap_observed_count',
            'relationship_variant_count',
            'to_database',
            'to_release',
            'url',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinCoverageData::fromArray()");
            }
        }
        return new self(
            cardinalityConsistentCount: $data['cardinality_consistent_count'],
            cardinalityContradictedCount: $data['cardinality_contradicted_count'],
            data: isset($data['data']) ? array_map(fn ($item) => DatabaseJoinCoverageRow::fromArray($item), $data['data']) : null,
            fromDatabase: $data['from_database'],
            fromRelease: $data['from_release'],
            id: $data['id'],
            noOverlapObservedCount: $data['no_overlap_observed_count'],
            observedCount: $data['observed_count'],
            ontologyDigest: $data['ontology_digest'],
            ontologyVersion: $data['ontology_version'],
            overlapObservedCount: $data['overlap_observed_count'],
            relationshipVariantCount: $data['relationship_variant_count'],
            toDatabase: $data['to_database'],
            toRelease: $data['to_release'],
            url: $data['url'],
            object: $data['object'] ?? 'database_join_coverage',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'cardinality_consistent_count' => $this->cardinalityConsistentCount,
            'cardinality_contradicted_count' => $this->cardinalityContradictedCount,
            'data' => $this->data !== null ? array_map(fn ($item) => $item->toArray(), $this->data) : null,
            'from_database' => $this->fromDatabase,
            'from_release' => $this->fromRelease,
            'id' => $this->id,
            'no_overlap_observed_count' => $this->noOverlapObservedCount,
            'observed_count' => $this->observedCount,
            'ontology_digest' => $this->ontologyDigest,
            'ontology_version' => $this->ontologyVersion,
            'overlap_observed_count' => $this->overlapObservedCount,
            'relationship_variant_count' => $this->relationshipVariantCount,
            'to_database' => $this->toDatabase,
            'to_release' => $this->toRelease,
            'url' => $this->url,
            'object' => $this->object,
        ];
    }
}
