<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetSplitRef implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $name,
        public string $partition,
        /** @var array<string>|null */
        public ?array $shardIds,
        public ?string $configId = null,
        public ?int $recordCount = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'name',
            'partition',
            'shard_ids',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetSplitRef::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            name: $data['name'],
            partition: $data['partition'],
            shardIds: $data['shard_ids'] ?? null,
            configId: $data['config_id'] ?? null,
            recordCount: $data['record_count'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'partition' => $this->partition,
            'shard_ids' => $this->shardIds,
            'config_id' => $this->configId,
            'record_count' => $this->recordCount,
        ];
    }
}
