<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetOntologyBindingListData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\DatasetOntologyBinding>|null */
        public ?array $data,
        public bool $hasMore,
        public string $ontologyDigest,
        public string $ontologyVersion,
        public string $object = 'list',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'data',
            'has_more',
            'ontology_digest',
            'ontology_version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetOntologyBindingListData::fromArray()");
            }
        }
        return new self(
            data: isset($data['data']) ? array_map(fn ($item) => DatasetOntologyBinding::fromArray($item), $data['data']) : null,
            hasMore: $data['has_more'],
            ontologyDigest: $data['ontology_digest'],
            ontologyVersion: $data['ontology_version'],
            object: $data['object'] ?? 'list',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'data' => $this->data !== null ? array_map(fn ($item) => $item->toArray(), $this->data) : null,
            'has_more' => $this->hasMore,
            'ontology_digest' => $this->ontologyDigest,
            'ontology_version' => $this->ontologyVersion,
            'object' => $this->object,
        ];
    }
}
