<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetBindingArtifact implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $format,
        public string $id,
        public string $objectId,
        public string $status,
        public ?int $rowCount = null,
        public ?string $sha256 = null,
        public ?int $sizeBytes = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'format',
            'id',
            'object_id',
            'status',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetBindingArtifact::fromArray()");
            }
        }
        return new self(
            format: $data['format'],
            id: $data['id'],
            objectId: $data['object_id'],
            status: $data['status'],
            rowCount: $data['row_count'] ?? null,
            sha256: $data['sha256'] ?? null,
            sizeBytes: $data['size_bytes'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'format' => $this->format,
            'id' => $this->id,
            'object_id' => $this->objectId,
            'status' => $this->status,
            'row_count' => $this->rowCount,
            'sha256' => $this->sha256,
            'size_bytes' => $this->sizeBytes,
        ];
    }
}
