<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum DatabaseJoinNeighborsAvailability: string
{
    case All = 'all';
    case Available = 'available';
    case Unavailable = 'unavailable';
}
