<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinCoverageLedgerListData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\DatabaseJoinCoverageLedgerData>|null */
        public ?array $data,
        public bool $hasMore,
        public string $url,
        public string $object = 'list',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'data',
            'has_more',
            'url',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinCoverageLedgerListData::fromArray()");
            }
        }
        return new self(
            data: isset($data['data']) ? array_map(fn ($item) => DatabaseJoinCoverageLedgerData::fromArray($item), $data['data']) : null,
            hasMore: $data['has_more'],
            url: $data['url'],
            object: $data['object'] ?? 'list',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'data' => $this->data !== null ? array_map(fn ($item) => $item->toArray(), $this->data) : null,
            'has_more' => $this->hasMore,
            'url' => $this->url,
            'object' => $this->object,
        ];
    }
}
