<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinCoverageControlRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public DatabaseJoinCoverageControlRequestExpectedOutcome $expectedOutcome,
        public string $fromDatabase,
        public string $fromRelease,
        public string $name,
        public string $relationshipId,
        public string $toDatabase,
        public string $toRelease,
        public ?OntologyKeyVariant $keyVariant = null,
        public ?DatabaseJoinsSafety $safety = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'expected_outcome',
            'from_database',
            'from_release',
            'name',
            'relationship_id',
            'to_database',
            'to_release',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinCoverageControlRequest::fromArray()");
            }
        }
        return new self(
            expectedOutcome: DatabaseJoinCoverageControlRequestExpectedOutcome::from($data['expected_outcome']),
            fromDatabase: $data['from_database'],
            fromRelease: $data['from_release'],
            name: $data['name'],
            relationshipId: $data['relationship_id'],
            toDatabase: $data['to_database'],
            toRelease: $data['to_release'],
            keyVariant: isset($data['key_variant']) ? OntologyKeyVariant::from($data['key_variant']) : null,
            safety: isset($data['safety']) ? DatabaseJoinsSafety::from($data['safety']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'expected_outcome' => $this->expectedOutcome->value,
            'from_database' => $this->fromDatabase,
            'from_release' => $this->fromRelease,
            'name' => $this->name,
            'relationship_id' => $this->relationshipId,
            'to_database' => $this->toDatabase,
            'to_release' => $this->toRelease,
            'key_variant' => $this->keyVariant?->value,
            'safety' => $this->safety?->value,
        ];
    }
}
