<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetSourceSnapshotIngestData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $isQueryReady,
        public int $recordCount,
        public string $ref,
        public int $rowCount,
        public string $source,
        public string $version,
        public ?string $database = null,
        public ?bool $dryRun = null,
        public ?bool $isReused = null,
        public ?string $relation = null,
        public ?string $release = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_query_ready',
            'record_count',
            'ref',
            'row_count',
            'source',
            'version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetSourceSnapshotIngestData::fromArray()");
            }
        }
        return new self(
            isQueryReady: $data['is_query_ready'],
            recordCount: $data['record_count'],
            ref: $data['ref'],
            rowCount: $data['row_count'],
            source: $data['source'],
            version: $data['version'],
            database: $data['database'] ?? null,
            dryRun: $data['dry_run'] ?? null,
            isReused: $data['is_reused'] ?? null,
            relation: $data['relation'] ?? null,
            release: $data['release'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_query_ready' => $this->isQueryReady,
            'record_count' => $this->recordCount,
            'ref' => $this->ref,
            'row_count' => $this->rowCount,
            'source' => $this->source,
            'version' => $this->version,
            'database' => $this->database,
            'dry_run' => $this->dryRun,
            'is_reused' => $this->isReused,
            'relation' => $this->relation,
            'release' => $this->release,
        ];
    }
}
