<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetManifestInspectRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Dataset manifest JSON path. */
        public string $manifestPath,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'manifest_path',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetManifestInspectRequest::fromArray()");
            }
        }
        return new self(
            manifestPath: $data['manifest_path'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'manifest_path' => $this->manifestPath,
        ];
    }
}
