<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum DatasetManifestScanRequestSort: string
{
    case Modified = 'modified';
    case Version = 'version';
}
