<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetBuildProfile implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $completedAt,
        public int $discoveryElapsedMs,
        public int $exportElapsedMs,
        public int $importElapsedMs,
        public int $manifestElapsedMs,
        public int $objectElapsedMs,
        public string $startedAt,
        /** @var array<\Rafflesia\Resource\DatasetBuildStructureTiming>|null */
        public ?array $structureTimings,
        /** @var array<\Rafflesia\Resource\DatasetBuildTableTiming>|null */
        public ?array $tableTimings,
        public int $totalElapsedMs,
        public ?int $compactionElapsedMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'completed_at',
            'discovery_elapsed_ms',
            'export_elapsed_ms',
            'import_elapsed_ms',
            'manifest_elapsed_ms',
            'object_elapsed_ms',
            'started_at',
            'structure_timings',
            'table_timings',
            'total_elapsed_ms',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetBuildProfile::fromArray()");
            }
        }
        return new self(
            completedAt: $data['completed_at'],
            discoveryElapsedMs: $data['discovery_elapsed_ms'],
            exportElapsedMs: $data['export_elapsed_ms'],
            importElapsedMs: $data['import_elapsed_ms'],
            manifestElapsedMs: $data['manifest_elapsed_ms'],
            objectElapsedMs: $data['object_elapsed_ms'],
            startedAt: $data['started_at'],
            structureTimings: isset($data['structure_timings']) ? array_map(fn ($item) => DatasetBuildStructureTiming::fromArray($item), $data['structure_timings']) : null,
            tableTimings: isset($data['table_timings']) ? array_map(fn ($item) => DatasetBuildTableTiming::fromArray($item), $data['table_timings']) : null,
            totalElapsedMs: $data['total_elapsed_ms'],
            compactionElapsedMs: $data['compaction_elapsed_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'completed_at' => $this->completedAt,
            'discovery_elapsed_ms' => $this->discoveryElapsedMs,
            'export_elapsed_ms' => $this->exportElapsedMs,
            'import_elapsed_ms' => $this->importElapsedMs,
            'manifest_elapsed_ms' => $this->manifestElapsedMs,
            'object_elapsed_ms' => $this->objectElapsedMs,
            'started_at' => $this->startedAt,
            'structure_timings' => $this->structureTimings !== null ? array_map(fn ($item) => $item->toArray(), $this->structureTimings) : null,
            'table_timings' => $this->tableTimings !== null ? array_map(fn ($item) => $item->toArray(), $this->tableTimings) : null,
            'total_elapsed_ms' => $this->totalElapsedMs,
            'compaction_elapsed_ms' => $this->compactionElapsedMs,
        ];
    }
}
