<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetRelationRef implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $name,
        /** @var array<string>|null */
        public ?array $primaryKey,
        public ?string $grain = null,
        public ?int $rowCount = null,
        public ?string $schemaHash = null,
        public ?int $schemaVersion = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'name',
            'primary_key',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetRelationRef::fromArray()");
            }
        }
        return new self(
            name: $data['name'],
            primaryKey: $data['primary_key'] ?? null,
            grain: $data['grain'] ?? null,
            rowCount: $data['row_count'] ?? null,
            schemaHash: $data['schema_hash'] ?? null,
            schemaVersion: $data['schema_version'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'primary_key' => $this->primaryKey,
            'grain' => $this->grain,
            'row_count' => $this->rowCount,
            'schema_hash' => $this->schemaHash,
            'schema_version' => $this->schemaVersion,
        ];
    }
}
