<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetTableCheck implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $exists,
        public int $expectedRowCount,
        public string $path,
        public bool $rowCountChecked,
        public bool $sha256Matches,
        public bool $sizeBytesMatches,
        public string $structureId,
        public string $tableName,
        public ?int $actualRowCount = null,
        public ?string $objectId = null,
        public ?string $partitionScope = null,
        public ?string $rowScopeColumn = null,
        public ?string $schemaHash = null,
        public ?int $schemaVersion = null,
        public ?string $sha256 = null,
        public ?int $sizeBytes = null,
        public ?string $toolRunId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'exists',
            'expected_row_count',
            'path',
            'row_count_checked',
            'sha256_matches',
            'size_bytes_matches',
            'structure_id',
            'table_name',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetTableCheck::fromArray()");
            }
        }
        return new self(
            exists: $data['exists'],
            expectedRowCount: $data['expected_row_count'],
            path: $data['path'],
            rowCountChecked: $data['row_count_checked'],
            sha256Matches: $data['sha256_matches'],
            sizeBytesMatches: $data['size_bytes_matches'],
            structureId: $data['structure_id'],
            tableName: $data['table_name'],
            actualRowCount: $data['actual_row_count'] ?? null,
            objectId: $data['object_id'] ?? null,
            partitionScope: $data['partition_scope'] ?? null,
            rowScopeColumn: $data['row_scope_column'] ?? null,
            schemaHash: $data['schema_hash'] ?? null,
            schemaVersion: $data['schema_version'] ?? null,
            sha256: $data['sha256'] ?? null,
            sizeBytes: $data['size_bytes'] ?? null,
            toolRunId: $data['tool_run_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'exists' => $this->exists,
            'expected_row_count' => $this->expectedRowCount,
            'path' => $this->path,
            'row_count_checked' => $this->rowCountChecked,
            'sha256_matches' => $this->sha256Matches,
            'size_bytes_matches' => $this->sizeBytesMatches,
            'structure_id' => $this->structureId,
            'table_name' => $this->tableName,
            'actual_row_count' => $this->actualRowCount,
            'object_id' => $this->objectId,
            'partition_scope' => $this->partitionScope,
            'row_scope_column' => $this->rowScopeColumn,
            'schema_hash' => $this->schemaHash,
            'schema_version' => $this->schemaVersion,
            'sha256' => $this->sha256,
            'size_bytes' => $this->sizeBytes,
            'tool_run_id' => $this->toolRunId,
        ];
    }
}
