<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetValidationIssue implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $code,
        public string $message,
        public string $severity,
        public ?string $actualPartitionScope = null,
        public ?int $actualRowCount = null,
        public ?string $actualRowScopeColumn = null,
        public ?string $actualSchemaHash = null,
        public ?int $actualSchemaVersion = null,
        public ?string $actualSha256 = null,
        public ?int $actualSizeBytes = null,
        public ?string $expectedPartitionScope = null,
        public ?int $expectedRowCount = null,
        public ?string $expectedRowScopeColumn = null,
        public ?string $expectedSchemaHash = null,
        public ?int $expectedSchemaVersion = null,
        public ?string $expectedSha256 = null,
        public ?int $expectedSizeBytes = null,
        public ?string $failureCode = null,
        public ?string $failureStage = null,
        public ?string $manifestField = null,
        public ?string $path = null,
        public ?string $structureId = null,
        public ?string $tableName = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'code',
            'message',
            'severity',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetValidationIssue::fromArray()");
            }
        }
        return new self(
            code: $data['code'],
            message: $data['message'],
            severity: $data['severity'],
            actualPartitionScope: $data['actual_partition_scope'] ?? null,
            actualRowCount: $data['actual_row_count'] ?? null,
            actualRowScopeColumn: $data['actual_row_scope_column'] ?? null,
            actualSchemaHash: $data['actual_schema_hash'] ?? null,
            actualSchemaVersion: $data['actual_schema_version'] ?? null,
            actualSha256: $data['actual_sha256'] ?? null,
            actualSizeBytes: $data['actual_size_bytes'] ?? null,
            expectedPartitionScope: $data['expected_partition_scope'] ?? null,
            expectedRowCount: $data['expected_row_count'] ?? null,
            expectedRowScopeColumn: $data['expected_row_scope_column'] ?? null,
            expectedSchemaHash: $data['expected_schema_hash'] ?? null,
            expectedSchemaVersion: $data['expected_schema_version'] ?? null,
            expectedSha256: $data['expected_sha256'] ?? null,
            expectedSizeBytes: $data['expected_size_bytes'] ?? null,
            failureCode: $data['failure_code'] ?? null,
            failureStage: $data['failure_stage'] ?? null,
            manifestField: $data['manifest_field'] ?? null,
            path: $data['path'] ?? null,
            structureId: $data['structure_id'] ?? null,
            tableName: $data['table_name'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'code' => $this->code,
            'message' => $this->message,
            'severity' => $this->severity,
            'actual_partition_scope' => $this->actualPartitionScope,
            'actual_row_count' => $this->actualRowCount,
            'actual_row_scope_column' => $this->actualRowScopeColumn,
            'actual_schema_hash' => $this->actualSchemaHash,
            'actual_schema_version' => $this->actualSchemaVersion,
            'actual_sha256' => $this->actualSha256,
            'actual_size_bytes' => $this->actualSizeBytes,
            'expected_partition_scope' => $this->expectedPartitionScope,
            'expected_row_count' => $this->expectedRowCount,
            'expected_row_scope_column' => $this->expectedRowScopeColumn,
            'expected_schema_hash' => $this->expectedSchemaHash,
            'expected_schema_version' => $this->expectedSchemaVersion,
            'expected_sha256' => $this->expectedSha256,
            'expected_size_bytes' => $this->expectedSizeBytes,
            'failure_code' => $this->failureCode,
            'failure_stage' => $this->failureStage,
            'manifest_field' => $this->manifestField,
            'path' => $this->path,
            'structure_id' => $this->structureId,
            'table_name' => $this->tableName,
        ];
    }
}
