<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatasetManifestScanRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Directory scanned recursively for dataset manifest JSON files (typically a lake root). */
        public string $root,
        /** Only include manifests whose dataset_name equals this value. */
        public ?string $datasetName = null,
        /** Only include manifests with zero recorded build failures and at least one non-empty table artifact. */
        public ?bool $failureFree = null,
        /** Maximum matched manifests to return after sorting. */
        public ?int $limit = null,
        /**
         * Only include manifests that contain every one of these table families.
         * @var array<string>|null
         */
        public ?array $requireTables = null,
        /** Ordering: modified (freshest file first, default) or version (dataset_version descending). */
        public ?DatasetManifestScanRequestSort $sort = null,
        /** Only include manifests whose dataset_version contains this substring. */
        public ?string $versionContains = null,
        /** Only include manifests whose dataset_version starts with this prefix. */
        public ?string $versionPrefix = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'root',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatasetManifestScanRequest::fromArray()");
            }
        }
        return new self(
            root: $data['root'],
            datasetName: $data['dataset_name'] ?? null,
            failureFree: $data['failure_free'] ?? null,
            limit: $data['limit'] ?? null,
            requireTables: $data['require_tables'] ?? null,
            sort: isset($data['sort']) ? DatasetManifestScanRequestSort::from($data['sort']) : null,
            versionContains: $data['version_contains'] ?? null,
            versionPrefix: $data['version_prefix'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'root' => $this->root,
            'dataset_name' => $this->datasetName,
            'failure_free' => $this->failureFree,
            'limit' => $this->limit,
            'require_tables' => $this->requireTables,
            'sort' => $this->sort?->value,
            'version_contains' => $this->versionContains,
            'version_prefix' => $this->versionPrefix,
        ];
    }
}
