<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinPathMeasurementRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Ordered acyclic path edges. Each edge after the first starts at the previous edge's to_source, and edge count must equal source count minus one.
         * @var array<\Rafflesia\Resource\DatabaseJoinPathEdge>|null
         */
        public ?array $edges,
        /** @var array<\Rafflesia\Resource\DatabaseJoinPathSource>|null */
        public ?array $sources,
        public ?QueryBudget $budget = null,
        public ?string $datasetName = null,
        public ?string $datasetVersion = null,
        public ?string $ontologyDigest = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'edges',
            'sources',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinPathMeasurementRequest::fromArray()");
            }
        }
        return new self(
            edges: isset($data['edges']) ? array_map(fn ($item) => DatabaseJoinPathEdge::fromArray($item), $data['edges']) : null,
            sources: isset($data['sources']) ? array_map(fn ($item) => DatabaseJoinPathSource::fromArray($item), $data['sources']) : null,
            budget: isset($data['budget']) ? QueryBudget::fromArray($data['budget']) : null,
            datasetName: $data['dataset_name'] ?? null,
            datasetVersion: $data['dataset_version'] ?? null,
            ontologyDigest: $data['ontology_digest'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'edges' => $this->edges !== null ? array_map(fn ($item) => $item->toArray(), $this->edges) : null,
            'sources' => $this->sources !== null ? array_map(fn ($item) => $item->toArray(), $this->sources) : null,
            'budget' => $this->budget?->toArray(),
            'dataset_name' => $this->datasetName,
            'dataset_version' => $this->datasetVersion,
            'ontology_digest' => $this->ontologyDigest,
        ];
    }
}
