<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinCandidateReviewData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $candidateId,
        public DatabaseJoinCandidateReviewDataDecision $decision,
        public string $id,
        public bool $isAccepted,
        public bool $isCurrent,
        public bool $isOntologyMutated,
        public bool $isSafeJoin,
        public string $reviewDigest,
        public ObjectRef $reviewObjectRef,
        public string $reviewVersion,
        public string $reviewer,
        public ?OntologyJoinReviewImpactData $impact = null,
        public ?OntologyJoinPatchData $patch = null,
        public ?ObjectRef $patchObjectRef = null,
        public ?string $supersededByReviewId = null,
        public ?string $supersedesReviewId = null,
        public string $object = 'database_join_candidate_review',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'candidate_id',
            'decision',
            'id',
            'is_accepted',
            'is_current',
            'is_ontology_mutated',
            'is_safe_join',
            'review_digest',
            'review_object_ref',
            'review_version',
            'reviewer',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinCandidateReviewData::fromArray()");
            }
        }
        return new self(
            candidateId: $data['candidate_id'],
            decision: DatabaseJoinCandidateReviewDataDecision::from($data['decision']),
            id: $data['id'],
            isAccepted: $data['is_accepted'],
            isCurrent: $data['is_current'],
            isOntologyMutated: $data['is_ontology_mutated'],
            isSafeJoin: $data['is_safe_join'],
            reviewDigest: $data['review_digest'],
            reviewObjectRef: ObjectRef::fromArray($data['review_object_ref']),
            reviewVersion: $data['review_version'],
            reviewer: $data['reviewer'],
            impact: isset($data['impact']) ? OntologyJoinReviewImpactData::fromArray($data['impact']) : null,
            patch: isset($data['patch']) ? OntologyJoinPatchData::fromArray($data['patch']) : null,
            patchObjectRef: isset($data['patch_object_ref']) ? ObjectRef::fromArray($data['patch_object_ref']) : null,
            supersededByReviewId: $data['superseded_by_review_id'] ?? null,
            supersedesReviewId: $data['supersedes_review_id'] ?? null,
            object: $data['object'] ?? 'database_join_candidate_review',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'candidate_id' => $this->candidateId,
            'decision' => $this->decision->value,
            'id' => $this->id,
            'is_accepted' => $this->isAccepted,
            'is_current' => $this->isCurrent,
            'is_ontology_mutated' => $this->isOntologyMutated,
            'is_safe_join' => $this->isSafeJoin,
            'review_digest' => $this->reviewDigest,
            'review_object_ref' => $this->reviewObjectRef->toArray(),
            'review_version' => $this->reviewVersion,
            'reviewer' => $this->reviewer,
            'impact' => $this->impact?->toArray(),
            'patch' => $this->patch?->toArray(),
            'patch_object_ref' => $this->patchObjectRef?->toArray(),
            'superseded_by_review_id' => $this->supersededByReviewId,
            'supersedes_review_id' => $this->supersedesReviewId,
            'object' => $this->object,
        ];
    }
}
