<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinCandidateProposalRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $candidateId,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'candidate_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinCandidateProposalRequest::fromArray()");
            }
        }
        return new self(
            candidateId: $data['candidate_id'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'candidate_id' => $this->candidateId,
        ];
    }
}
