<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DatabaseJoinCandidateMeasureRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $fromDatabase,
        public string $fromRelease,
        public string $toDatabase,
        public string $toRelease,
        public ?QueryBudget $budget = null,
        public ?QueryRequestBudgetProfile $budgetProfile = null,
        /** @var array<string>|null */
        public ?array $fromRelations = null,
        public ?int $maxCandidates = null,
        public ?string $ontologyDigest = null,
        /** @var array<string>|null */
        public ?array $toRelations = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'from_database',
            'from_release',
            'to_database',
            'to_release',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DatabaseJoinCandidateMeasureRequest::fromArray()");
            }
        }
        return new self(
            fromDatabase: $data['from_database'],
            fromRelease: $data['from_release'],
            toDatabase: $data['to_database'],
            toRelease: $data['to_release'],
            budget: isset($data['budget']) ? QueryBudget::fromArray($data['budget']) : null,
            budgetProfile: isset($data['budget_profile']) ? QueryRequestBudgetProfile::from($data['budget_profile']) : null,
            fromRelations: $data['from_relations'] ?? null,
            maxCandidates: $data['max_candidates'] ?? null,
            ontologyDigest: $data['ontology_digest'] ?? null,
            toRelations: $data['to_relations'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'from_database' => $this->fromDatabase,
            'from_release' => $this->fromRelease,
            'to_database' => $this->toDatabase,
            'to_release' => $this->toRelease,
            'budget' => $this->budget?->toArray(),
            'budget_profile' => $this->budgetProfile?->value,
            'from_relations' => $this->fromRelations,
            'max_candidates' => $this->maxCandidates,
            'ontology_digest' => $this->ontologyDigest,
            'to_relations' => $this->toRelations,
        ];
    }
}
