<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DiamondDbRegistryRecord implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $artifactCount,
        public string $engine,
        public string $manifestId,
        public string $name,
        public string $publishedAt,
        public string $ref,
        public int $totalSizeBytes,
        public string $version,
        public ?string $dbPrefix = null,
        public ?string $engineVersion = null,
        public ?ObjectRef $manifestObject = null,
        public ?string $manifestObjectId = null,
        public ?string $manifestPath = null,
        public ?string $sourceObjectId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'artifact_count',
            'engine',
            'manifest_id',
            'name',
            'published_at',
            'ref',
            'total_size_bytes',
            'version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DiamondDbRegistryRecord::fromArray()");
            }
        }
        return new self(
            artifactCount: $data['artifact_count'],
            engine: $data['engine'],
            manifestId: $data['manifest_id'],
            name: $data['name'],
            publishedAt: $data['published_at'],
            ref: $data['ref'],
            totalSizeBytes: $data['total_size_bytes'],
            version: $data['version'],
            dbPrefix: $data['db_prefix'] ?? null,
            engineVersion: $data['engine_version'] ?? null,
            manifestObject: isset($data['manifest_object']) ? ObjectRef::fromArray($data['manifest_object']) : null,
            manifestObjectId: $data['manifest_object_id'] ?? null,
            manifestPath: $data['manifest_path'] ?? null,
            sourceObjectId: $data['source_object_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'artifact_count' => $this->artifactCount,
            'engine' => $this->engine,
            'manifest_id' => $this->manifestId,
            'name' => $this->name,
            'published_at' => $this->publishedAt,
            'ref' => $this->ref,
            'total_size_bytes' => $this->totalSizeBytes,
            'version' => $this->version,
            'db_prefix' => $this->dbPrefix,
            'engine_version' => $this->engineVersion,
            'manifest_object' => $this->manifestObject?->toArray(),
            'manifest_object_id' => $this->manifestObjectId,
            'manifest_path' => $this->manifestPath,
            'source_object_id' => $this->sourceObjectId,
        ];
    }
}
