<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DiamondDbManifest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string>|null */
        public ?array $buildCommand,
        public string $createdAt,
        public DiamondDbArtifact $database,
        public string $dbId,
        public string $dbPrefix,
        public string $engine,
        public string $manifestId,
        public int $manifestVersion,
        public string $name,
        public DiamondDbArtifact $sourceFasta,
        public string $version,
        public ?string $engineVersion = null,
        /** @var array<string, mixed>|null */
        public ?array $parameters = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'build_command',
            'created_at',
            'database',
            'db_id',
            'db_prefix',
            'engine',
            'manifest_id',
            'manifest_version',
            'name',
            'source_fasta',
            'version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DiamondDbManifest::fromArray()");
            }
        }
        return new self(
            buildCommand: $data['build_command'] ?? null,
            createdAt: $data['created_at'],
            database: DiamondDbArtifact::fromArray($data['database']),
            dbId: $data['db_id'],
            dbPrefix: $data['db_prefix'],
            engine: $data['engine'],
            manifestId: $data['manifest_id'],
            manifestVersion: $data['manifest_version'],
            name: $data['name'],
            sourceFasta: DiamondDbArtifact::fromArray($data['source_fasta']),
            version: $data['version'],
            engineVersion: $data['engine_version'] ?? null,
            parameters: $data['parameters'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'build_command' => $this->buildCommand,
            'created_at' => $this->createdAt,
            'database' => $this->database->toArray(),
            'db_id' => $this->dbId,
            'db_prefix' => $this->dbPrefix,
            'engine' => $this->engine,
            'manifest_id' => $this->manifestId,
            'manifest_version' => $this->manifestVersion,
            'name' => $this->name,
            'source_fasta' => $this->sourceFasta->toArray(),
            'version' => $this->version,
            'engine_version' => $this->engineVersion,
            'parameters' => $this->parameters,
        ];
    }
}
