<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class DiamondCatalogBuildData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $catalog,
        public string $datasetVersion,
        public string $engine,
        public string $name,
        public int $recordCount,
        public int $requestedShards,
        public int $shardCount,
        /** @var array<\Rafflesia\Resource\DiamondCatalogShardData>|null */
        public ?array $shards,
        public string $storeRoot,
        public int $totalSizeBytes,
        public string $version,
        /** @var array<array<string>|null>|null */
        public ?array $buildCommands = null,
        /** @var array<string, mixed>|null */
        public ?array $catalogManifest = null,
        public ?string $catalogPath = null,
        public ?bool $dryRun = null,
        public ?string $engineVersion = null,
        /** @var array<string, mixed>|null */
        public ?array $parameters = null,
        public ?ObjectRef $sourceObject = null,
        public ?string $sourcePath = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'catalog',
            'dataset_version',
            'engine',
            'name',
            'record_count',
            'requested_shards',
            'shard_count',
            'shards',
            'store_root',
            'total_size_bytes',
            'version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for DiamondCatalogBuildData::fromArray()");
            }
        }
        return new self(
            catalog: $data['catalog'],
            datasetVersion: $data['dataset_version'],
            engine: $data['engine'],
            name: $data['name'],
            recordCount: $data['record_count'],
            requestedShards: $data['requested_shards'],
            shardCount: $data['shard_count'],
            shards: isset($data['shards']) ? array_map(fn ($item) => DiamondCatalogShardData::fromArray($item), $data['shards']) : null,
            storeRoot: $data['store_root'],
            totalSizeBytes: $data['total_size_bytes'],
            version: $data['version'],
            buildCommands: $data['build_commands'] ?? null,
            catalogManifest: $data['catalog_manifest'] ?? null,
            catalogPath: $data['catalog_path'] ?? null,
            dryRun: $data['dry_run'] ?? null,
            engineVersion: $data['engine_version'] ?? null,
            parameters: $data['parameters'] ?? null,
            sourceObject: isset($data['source_object']) ? ObjectRef::fromArray($data['source_object']) : null,
            sourcePath: $data['source_path'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'catalog' => $this->catalog,
            'dataset_version' => $this->datasetVersion,
            'engine' => $this->engine,
            'name' => $this->name,
            'record_count' => $this->recordCount,
            'requested_shards' => $this->requestedShards,
            'shard_count' => $this->shardCount,
            'shards' => $this->shards !== null ? array_map(fn ($item) => $item->toArray(), $this->shards) : null,
            'store_root' => $this->storeRoot,
            'total_size_bytes' => $this->totalSizeBytes,
            'version' => $this->version,
            'build_commands' => $this->buildCommands,
            'catalog_manifest' => $this->catalogManifest,
            'catalog_path' => $this->catalogPath,
            'dry_run' => $this->dryRun,
            'engine_version' => $this->engineVersion,
            'parameters' => $this->parameters,
            'source_object' => $this->sourceObject?->toArray(),
            'source_path' => $this->sourcePath,
        ];
    }
}
