<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class EnvironmentTask implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string>|null */
        public ?array $capabilityIds,
        public \DateTimeImmutable $createdAt,
        public string $difficulty,
        public string $environmentId,
        public string $environmentReleaseId,
        public string $graderHash,
        public string $id,
        public bool $isLivemode,
        public string $kind,
        /** @var array<string, string> */
        public array $metadata,
        public string $object,
        /** @var array<string, mixed> */
        public array $outputContract,
        public string $prompt,
        /** @var array<string, mixed> */
        public array $rewardContract,
        public string $rewardDefinitionId,
        public string $runtimeProfileId,
        public string $sourceTaskId,
        public string $taskHash,
        public string $title,
        /** @var array<string>|null */
        public ?array $warnings,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'capability_ids',
            'created_at',
            'difficulty',
            'environment_id',
            'environment_release_id',
            'grader_hash',
            'id',
            'is_livemode',
            'kind',
            'metadata',
            'object',
            'output_contract',
            'prompt',
            'reward_contract',
            'reward_definition_id',
            'runtime_profile_id',
            'source_task_id',
            'task_hash',
            'title',
            'warnings',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EnvironmentTask::fromArray()");
            }
        }
        return new self(
            capabilityIds: $data['capability_ids'] ?? null,
            createdAt: new \DateTimeImmutable($data['created_at']),
            difficulty: $data['difficulty'],
            environmentId: $data['environment_id'],
            environmentReleaseId: $data['environment_release_id'],
            graderHash: $data['grader_hash'],
            id: $data['id'],
            isLivemode: $data['is_livemode'],
            kind: $data['kind'],
            metadata: $data['metadata'],
            object: $data['object'],
            outputContract: $data['output_contract'],
            prompt: $data['prompt'],
            rewardContract: $data['reward_contract'],
            rewardDefinitionId: $data['reward_definition_id'],
            runtimeProfileId: $data['runtime_profile_id'],
            sourceTaskId: $data['source_task_id'],
            taskHash: $data['task_hash'],
            title: $data['title'],
            warnings: $data['warnings'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'capability_ids' => $this->capabilityIds,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'difficulty' => $this->difficulty,
            'environment_id' => $this->environmentId,
            'environment_release_id' => $this->environmentReleaseId,
            'grader_hash' => $this->graderHash,
            'id' => $this->id,
            'is_livemode' => $this->isLivemode,
            'kind' => $this->kind,
            'metadata' => $this->metadata,
            'object' => $this->object,
            'output_contract' => $this->outputContract,
            'prompt' => $this->prompt,
            'reward_contract' => $this->rewardContract,
            'reward_definition_id' => $this->rewardDefinitionId,
            'runtime_profile_id' => $this->runtimeProfileId,
            'source_task_id' => $this->sourceTaskId,
            'task_hash' => $this->taskHash,
            'title' => $this->title,
            'warnings' => $this->warnings,
        ];
    }
}
