<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class EpisodeEvent implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public \DateTimeImmutable $createdAt,
        /** @var array<string, mixed> */
        public array $data,
        public string $episodeId,
        public string $id,
        public string $object,
        public string $organizationId,
        public string $type,
        public ?string $attemptId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'created_at',
            'data',
            'episode_id',
            'id',
            'object',
            'organization_id',
            'type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EpisodeEvent::fromArray()");
            }
        }
        return new self(
            createdAt: new \DateTimeImmutable($data['created_at']),
            data: $data['data'],
            episodeId: $data['episode_id'],
            id: $data['id'],
            object: $data['object'],
            organizationId: $data['organization_id'],
            type: $data['type'],
            attemptId: $data['attempt_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'data' => $this->data,
            'episode_id' => $this->episodeId,
            'id' => $this->id,
            'object' => $this->object,
            'organization_id' => $this->organizationId,
            'type' => $this->type,
            'attempt_id' => $this->attemptId,
        ];
    }
}
