<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum EventsType: string
{
    case RunCreated = 'run.created';
    case RunStarted = 'run.started';
    case RunRetryScheduled = 'run.retry_scheduled';
    case RunCompleted = 'run.completed';
    case RunFailed = 'run.failed';
    case RunCanceled = 'run.canceled';
}
