<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ExecutionApiError implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Stable specific error code. Branch on this value instead of message. */
        public string $code,
        /** Stable documentation URL for this error code. */
        public string $docUrl,
        /**
         * One or more exact validation or execution failures. Machine logic should use type, loc, and ctx; msg is for people.
         * @var array<\Rafflesia\Resource\ApiErrorDetail>
         */
        public array $errors,
        /** Whether retrying the identical pinned request may succeed without changing its input. */
        public bool $isRetryable,
        /** Human-readable actionable explanation. Do not parse this value. */
        public string $message,
        /** Stable coarse error category. */
        public ApiErrorBodyType $type,
        /**
         * Additional structured error details retained for compatibility.
         * @var array<string, mixed>|null
         */
        public ?array $details = null,
        /** Request field responsible for the error when known. */
        public ?string $param = null,
        /** Request identifier to provide when reporting this occurrence. */
        public ?string $requestId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'code',
            'doc_url',
            'errors',
            'is_retryable',
            'message',
            'type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ExecutionApiError::fromArray()");
            }
        }
        return new self(
            code: $data['code'],
            docUrl: $data['doc_url'],
            errors: array_map(fn ($item) => ApiErrorDetail::fromArray($item), $data['errors']),
            isRetryable: $data['is_retryable'],
            message: $data['message'],
            type: ApiErrorBodyType::from($data['type']),
            details: $data['details'] ?? null,
            param: $data['param'] ?? null,
            requestId: $data['request_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'code' => $this->code,
            'doc_url' => $this->docUrl,
            'errors' => array_map(fn ($item) => $item->toArray(), $this->errors),
            'is_retryable' => $this->isRetryable,
            'message' => $this->message,
            'type' => $this->type->value,
            'details' => $this->details,
            'param' => $this->param,
            'request_id' => $this->requestId,
        ];
    }
}
