<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FileSignedUrl implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public \DateTimeImmutable $createdAt,
        public \DateTimeImmutable $expiresAt,
        public string $id,
        /** @var array<string>|null */
        public ?array $scope,
        public string $url,
        public string $object = 'file_signed_url',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'created_at',
            'expires_at',
            'id',
            'scope',
            'url',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FileSignedUrl::fromArray()");
            }
        }
        return new self(
            createdAt: new \DateTimeImmutable($data['created_at']),
            expiresAt: new \DateTimeImmutable($data['expires_at']),
            id: $data['id'],
            scope: $data['scope'] ?? null,
            url: $data['url'],
            object: $data['object'] ?? 'file_signed_url',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'expires_at' => $this->expiresAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'id' => $this->id,
            'scope' => $this->scope,
            'url' => $this->url,
            'object' => $this->object,
        ];
    }
}
