<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldIndexArtifactState implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public FoldIndexArtifact $artifact,
        public bool $exists,
        public bool $isLocal,
        public bool $verified,
        public ?string $error = null,
        public ?string $localPath = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'artifact',
            'exists',
            'is_local',
            'verified',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoldIndexArtifactState::fromArray()");
            }
        }
        return new self(
            artifact: FoldIndexArtifact::fromArray($data['artifact']),
            exists: $data['exists'],
            isLocal: $data['is_local'],
            verified: $data['verified'],
            error: $data['error'] ?? null,
            localPath: $data['local_path'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'artifact' => $this->artifact->toArray(),
            'exists' => $this->exists,
            'is_local' => $this->isLocal,
            'verified' => $this->verified,
            'error' => $this->error,
            'local_path' => $this->localPath,
        ];
    }
}
