<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldSearchProfile implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Materializing index shards into the local cache (S3 download on a cold cache). */
        public int $materializeIndexMs,
        /** Resolving the index ref/manifest. */
        public int $resolveIndexMs,
        /** Resolving the query id to a local structure file. */
        public int $resolveQueryMs,
        /** Wall-clock across all shard Foldseek subprocess runs (concurrent). */
        public int $searchMs,
        /** Storing the normalized hits object. */
        public int $storeOutputMs,
        /** Total handler wall-clock. */
        public int $totalMs,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'materialize_index_ms',
            'resolve_index_ms',
            'resolve_query_ms',
            'search_ms',
            'store_output_ms',
            'total_ms',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoldSearchProfile::fromArray()");
            }
        }
        return new self(
            materializeIndexMs: $data['materialize_index_ms'],
            resolveIndexMs: $data['resolve_index_ms'],
            resolveQueryMs: $data['resolve_query_ms'],
            searchMs: $data['search_ms'],
            storeOutputMs: $data['store_output_ms'],
            totalMs: $data['total_ms'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'materialize_index_ms' => $this->materializeIndexMs,
            'resolve_index_ms' => $this->resolveIndexMs,
            'resolve_query_ms' => $this->resolveQueryMs,
            'search_ms' => $this->searchMs,
            'store_output_ms' => $this->storeOutputMs,
            'total_ms' => $this->totalMs,
        ];
    }
}
