<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldSearchMonitoring implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $dataReadMetric,
        public string $runtimeMetric,
        public string $scalingLawId,
        public string $schemaVersion,
        /** @var array<\Rafflesia\Resource\FoldSearchMonitoringObservation>|null */
        public ?array $observations = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'data_read_metric',
            'runtime_metric',
            'scaling_law_id',
            'schema_version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoldSearchMonitoring::fromArray()");
            }
        }
        return new self(
            dataReadMetric: $data['data_read_metric'],
            runtimeMetric: $data['runtime_metric'],
            scalingLawId: $data['scaling_law_id'],
            schemaVersion: $data['schema_version'],
            observations: isset($data['observations']) ? array_map(fn ($item) => FoldSearchMonitoringObservation::fromArray($item), $data['observations']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'data_read_metric' => $this->dataReadMetric,
            'runtime_metric' => $this->runtimeMetric,
            'scaling_law_id' => $this->scalingLawId,
            'schema_version' => $this->schemaVersion,
            'observations' => $this->observations !== null ? array_map(fn ($item) => $item->toArray(), $this->observations) : null,
        ];
    }
}
