<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldIndexMaterializedFile implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $cacheHit,
        public string $fileName,
        public string $path,
        public string $role,
        public string $sha256,
        public string $shardId,
        public int $sizeBytes,
        public ?int $lockWaitMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'cache_hit',
            'file_name',
            'path',
            'role',
            'sha256',
            'shard_id',
            'size_bytes',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoldIndexMaterializedFile::fromArray()");
            }
        }
        return new self(
            cacheHit: $data['cache_hit'],
            fileName: $data['file_name'],
            path: $data['path'],
            role: $data['role'],
            sha256: $data['sha256'],
            shardId: $data['shard_id'],
            sizeBytes: $data['size_bytes'],
            lockWaitMs: $data['lock_wait_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'cache_hit' => $this->cacheHit,
            'file_name' => $this->fileName,
            'path' => $this->path,
            'role' => $this->role,
            'sha256' => $this->sha256,
            'shard_id' => $this->shardId,
            'size_bytes' => $this->sizeBytes,
            'lock_wait_ms' => $this->lockWaitMs,
        ];
    }
}
