<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldIndexMaterializeRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Manifest object id */
        public ?string $manifestObjectId = null,
        /** Local manifest path */
        public ?string $manifestPath = null,
        /** Published index ref such as name:version or manifest object id */
        public ?string $ref = null,
        /**
         * Optional Foldseek segment roles to materialize: search_index, routing_index. Empty materializes every segment.
         * @var array<string>|null
         */
        public ?array $segmentRoles = null,
        /**
         * Optional shard ids to materialize; empty materializes every shard with artifacts
         * @var array<string>|null
         */
        public ?array $shards = null,
        /** Directory used as the local Foldseek index cache */
        public ?string $targetDir = null,
        /** Verify materialized files by SHA-256 */
        public ?bool $verify = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            manifestObjectId: $data['manifest_object_id'] ?? null,
            manifestPath: $data['manifest_path'] ?? null,
            ref: $data['ref'] ?? null,
            segmentRoles: $data['segment_roles'] ?? null,
            shards: $data['shards'] ?? null,
            targetDir: $data['target_dir'] ?? null,
            verify: $data['verify'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'manifest_object_id' => $this->manifestObjectId,
            'manifest_path' => $this->manifestPath,
            'ref' => $this->ref,
            'segment_roles' => $this->segmentRoles,
            'shards' => $this->shards,
            'target_dir' => $this->targetDir,
            'verify' => $this->verify,
        ];
    }
}
