<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldCollectionRoutingDecision implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $blockBytes,
        public int $blockCount,
        public bool $isSelected,
        public int $rank,
        public int $recordCount,
        public string $ref,
        public float $score,
        public string $segmentId,
        public ?float $geometryOverlap = null,
        public ?float $lengthSimilarity = null,
        public ?string $reason = null,
        public ?int $residueCountDistance = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'block_bytes',
            'block_count',
            'is_selected',
            'rank',
            'record_count',
            'ref',
            'score',
            'segment_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoldCollectionRoutingDecision::fromArray()");
            }
        }
        return new self(
            blockBytes: $data['block_bytes'],
            blockCount: $data['block_count'],
            isSelected: $data['is_selected'],
            rank: $data['rank'],
            recordCount: $data['record_count'],
            ref: $data['ref'],
            score: $data['score'],
            segmentId: $data['segment_id'],
            geometryOverlap: $data['geometry_overlap'] ?? null,
            lengthSimilarity: $data['length_similarity'] ?? null,
            reason: $data['reason'] ?? null,
            residueCountDistance: $data['residue_count_distance'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'block_bytes' => $this->blockBytes,
            'block_count' => $this->blockCount,
            'is_selected' => $this->isSelected,
            'rank' => $this->rank,
            'record_count' => $this->recordCount,
            'ref' => $this->ref,
            'score' => $this->score,
            'segment_id' => $this->segmentId,
            'geometry_overlap' => $this->geometryOverlap,
            'length_similarity' => $this->lengthSimilarity,
            'reason' => $this->reason,
            'residue_count_distance' => $this->residueCountDistance,
        ];
    }
}
