<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoldIndexRoutingShardSelectionMetric implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $selectedCount,
        public string $shardId,
        public string $sketchKind,
        public int $sourceCount,
        public ?float $meanSelectedSketchCoverage = null,
        public ?float $minSelectedSketchCoverage = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'selected_count',
            'shard_id',
            'sketch_kind',
            'source_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoldIndexRoutingShardSelectionMetric::fromArray()");
            }
        }
        return new self(
            selectedCount: $data['selected_count'],
            shardId: $data['shard_id'],
            sketchKind: $data['sketch_kind'],
            sourceCount: $data['source_count'],
            meanSelectedSketchCoverage: $data['mean_selected_sketch_coverage'] ?? null,
            minSelectedSketchCoverage: $data['min_selected_sketch_coverage'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'selected_count' => $this->selectedCount,
            'shard_id' => $this->shardId,
            'sketch_kind' => $this->sketchKind,
            'source_count' => $this->sourceCount,
            'mean_selected_sketch_coverage' => $this->meanSelectedSketchCoverage,
            'min_selected_sketch_coverage' => $this->minSelectedSketchCoverage,
        ];
    }
}
