<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoundryModelEndpoint implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $method,
        public string $operationId,
        public string $path,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'method',
            'operation_id',
            'path',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoundryModelEndpoint::fromArray()");
            }
        }
        return new self(
            method: $data['method'],
            operationId: $data['operation_id'],
            path: $data['path'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'method' => $this->method,
            'operation_id' => $this->operationId,
            'path' => $this->path,
        ];
    }
}
