<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class FoundryVariantEffect implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $alternate,
        public string $id,
        public int $index,
        public float $logLikelihoodRatio,
        public string $object,
        public int $position,
        public string $reference,
        /** @var array<float>|null */
        public ?array $modelLogLikelihoodRatios = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'alternate',
            'id',
            'index',
            'log_likelihood_ratio',
            'object',
            'position',
            'reference',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for FoundryVariantEffect::fromArray()");
            }
        }
        return new self(
            alternate: $data['alternate'],
            id: $data['id'],
            index: $data['index'],
            logLikelihoodRatio: $data['log_likelihood_ratio'],
            object: $data['object'],
            position: $data['position'],
            reference: $data['reference'],
            modelLogLikelihoodRatios: $data['model_log_likelihood_ratios'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'alternate' => $this->alternate,
            'id' => $this->id,
            'index' => $this->index,
            'log_likelihood_ratio' => $this->logLikelihoodRatio,
            'object' => $this->object,
            'position' => $this->position,
            'reference' => $this->reference,
            'model_log_likelihood_ratios' => $this->modelLogLikelihoodRatios,
        ];
    }
}
