<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class GenomeRegionGetRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Assembly identifier (case-insensitive, alias-aware). */
        public string $assemblyId,
        /** Region string, e.g. chr17:43,044,295-43125483 (1-based inclusive). */
        public string $region,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'assembly_id',
            'region',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for GenomeRegionGetRequest::fromArray()");
            }
        }
        return new self(
            assemblyId: $data['assembly_id'],
            region: $data['region'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'assembly_id' => $this->assemblyId,
            'region' => $this->region,
        ];
    }
}
