<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class GenomeRegionData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Resolved assembly identifier. */
        public string $assemblyId,
        /** 1-based inclusive end coordinate. */
        public int $end,
        /** 1-based inclusive start coordinate. */
        public int $start,
        /** Canonical contig name. */
        public ?string $contig = null,
        /** Coordinate system, e.g. 1-based-inclusive. */
        public ?string $coordinateSystem = null,
        /** Region length in base pairs (end-start+1). */
        public ?int $lengthBp = null,
        /** Normalized region string. */
        public ?string $normalized = null,
        /** Strand, defaults to +. */
        public ?string $strand = null,
        /**
         * Non-fatal warnings (unknown contig, out of bounds, parse failure).
         * @var array<\Rafflesia\Resource\SearchWarning>|null
         */
        public ?array $warnings = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'assembly_id',
            'end',
            'start',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for GenomeRegionData::fromArray()");
            }
        }
        return new self(
            assemblyId: $data['assembly_id'],
            end: $data['end'],
            start: $data['start'],
            contig: $data['contig'] ?? null,
            coordinateSystem: $data['coordinate_system'] ?? null,
            lengthBp: $data['length_bp'] ?? null,
            normalized: $data['normalized'] ?? null,
            strand: $data['strand'] ?? null,
            warnings: isset($data['warnings']) ? array_map(fn ($item) => SearchWarning::fromArray($item), $data['warnings']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'assembly_id' => $this->assemblyId,
            'end' => $this->end,
            'start' => $this->start,
            'contig' => $this->contig,
            'coordinate_system' => $this->coordinateSystem,
            'length_bp' => $this->lengthBp,
            'normalized' => $this->normalized,
            'strand' => $this->strand,
            'warnings' => $this->warnings !== null ? array_map(fn ($item) => $item->toArray(), $this->warnings) : null,
        ];
    }
}
