<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyRankingComparator implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public HomologyRankingComparatorField $field,
        public HomologyResponseRankingOrder $order,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'field',
            'order',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyRankingComparator::fromArray()");
            }
        }
        return new self(
            field: HomologyRankingComparatorField::from($data['field']),
            order: HomologyResponseRankingOrder::from($data['order']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'field' => $this->field->value,
            'order' => $this->order->value,
        ];
    }
}
