<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyTailModel implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $fitExceedanceCount,
        /** Held-out observations the goodness-of-fit test used. Read the KS distance with this; the distance alone means little without the sample size behind it. */
        public int $holdoutExceedanceCount,
        public float $holdoutKolmogorovSmirnov,
        public float $holdoutSignificanceLevel,
        public float $k,
        public float $lambda,
        /** Lower bound of the fitted tail region. Extrapolation is only actually used once the counted null runs out, which support_status reports as supported_tail_model; a score above this threshold may still be served empirically. */
        public float $thresholdScore,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'fit_exceedance_count',
            'holdout_exceedance_count',
            'holdout_kolmogorov_smirnov',
            'holdout_significance_level',
            'k',
            'lambda',
            'threshold_score',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyTailModel::fromArray()");
            }
        }
        return new self(
            fitExceedanceCount: $data['fit_exceedance_count'],
            holdoutExceedanceCount: $data['holdout_exceedance_count'],
            holdoutKolmogorovSmirnov: $data['holdout_kolmogorov_smirnov'],
            holdoutSignificanceLevel: $data['holdout_significance_level'],
            k: $data['k'],
            lambda: $data['lambda'],
            thresholdScore: $data['threshold_score'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'fit_exceedance_count' => $this->fitExceedanceCount,
            'holdout_exceedance_count' => $this->holdoutExceedanceCount,
            'holdout_kolmogorov_smirnov' => $this->holdoutKolmogorovSmirnov,
            'holdout_significance_level' => $this->holdoutSignificanceLevel,
            'k' => $this->k,
            'lambda' => $this->lambda,
            'threshold_score' => $this->thresholdScore,
        ];
    }
}
