<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyPublicError implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $code,
        public string $docUrl,
        public string $message,
        public string $requestId,
        public ApiErrorBodyType $type,
        /** @var array<string, mixed>|null */
        public ?array $details = null,
        public ?string $param = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'code',
            'doc_url',
            'message',
            'request_id',
            'type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyPublicError::fromArray()");
            }
        }
        return new self(
            code: $data['code'],
            docUrl: $data['doc_url'],
            message: $data['message'],
            requestId: $data['request_id'],
            type: ApiErrorBodyType::from($data['type']),
            details: $data['details'] ?? null,
            param: $data['param'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'code' => $this->code,
            'doc_url' => $this->docUrl,
            'message' => $this->message,
            'request_id' => $this->requestId,
            'type' => $this->type->value,
            'details' => $this->details,
            'param' => $this->param,
        ];
    }
}
