<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyResponse implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Ranked retrieval candidates. These are measurements, not asserted homologs.
         * @var array<\Rafflesia\Resource\HomologyCandidate>
         */
        public array $candidates,
        public HomologyResponseDatabase $database,
        public HomologyEvidenceSummary $evidenceSummary,
        public HomologyResponseExecution $execution,
        /** True when additional ranked targets existed beyond limit. False means the returned list exhausted the searched population. */
        public bool $isResultLimitReached,
        public HomologyResponsePerformance $performance,
        public HomologyResponseQuery $query,
        public HomologyResponseRanking $ranking,
        public HomologyResponseReceipt $receipt,
        public string $requestId,
        public string $resultSha256,
        public HomologyResponseUsage $usage,
        /**
         * Non-fatal warnings. Always an array.
         * @var array<\Rafflesia\Resource\SearchWarning>
         */
        public array $warnings,
        /** Always homology_candidate_set. */
        public string $object = 'homology_candidate_set',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'candidates',
            'database',
            'evidence_summary',
            'execution',
            'is_result_limit_reached',
            'performance',
            'query',
            'ranking',
            'receipt',
            'request_id',
            'result_sha256',
            'usage',
            'warnings',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyResponse::fromArray()");
            }
        }
        return new self(
            candidates: array_map(fn ($item) => HomologyCandidate::fromArray($item), $data['candidates']),
            database: HomologyResponseDatabase::fromArray($data['database']),
            evidenceSummary: HomologyEvidenceSummary::fromArray($data['evidence_summary']),
            execution: HomologyResponseExecution::fromArray($data['execution']),
            isResultLimitReached: $data['is_result_limit_reached'],
            performance: HomologyResponsePerformance::fromArray($data['performance']),
            query: HomologyResponseQuery::fromArray($data['query']),
            ranking: HomologyResponseRanking::fromArray($data['ranking']),
            receipt: HomologyResponseReceipt::fromArray($data['receipt']),
            requestId: $data['request_id'],
            resultSha256: $data['result_sha256'],
            usage: HomologyResponseUsage::fromArray($data['usage']),
            warnings: array_map(fn ($item) => SearchWarning::fromArray($item), $data['warnings']),
            object: $data['object'] ?? 'homology_candidate_set',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'candidates' => array_map(fn ($item) => $item->toArray(), $this->candidates),
            'database' => $this->database->toArray(),
            'evidence_summary' => $this->evidenceSummary->toArray(),
            'execution' => $this->execution->toArray(),
            'is_result_limit_reached' => $this->isResultLimitReached,
            'performance' => $this->performance->toArray(),
            'query' => $this->query->toArray(),
            'ranking' => $this->ranking->toArray(),
            'receipt' => $this->receipt->toArray(),
            'request_id' => $this->requestId,
            'result_sha256' => $this->resultSha256,
            'usage' => $this->usage->toArray(),
            'warnings' => array_map(fn ($item) => $item->toArray(), $this->warnings),
            'object' => $this->object,
        ];
    }
}
