<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyQueryContextMeasurement implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $databaseId,
        public string $databaseReleaseId,
        /** Always homology_query_context_measurement. */
        public string $object,
        public DatabaseJoinCandidateDataObservationStatus $observationStatus,
        public mixed $cost = null,
        public mixed $coverage = null,
        public ?HomologyQueryContextExecutionFailure $executionFailure = null,
        public ?string $homologySearchId = null,
        /** Canonical Dandelion query-context measurements forwarded unchanged. */
        public mixed $queryContext = null,
        public mixed $resolvedParameters = null,
        public mixed $searchProvenance = null,
        /** @var array<\Rafflesia\Resource\SearchWarning>|null */
        public ?array $warnings = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'database_id',
            'database_release_id',
            'object',
            'observation_status',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyQueryContextMeasurement::fromArray()");
            }
        }
        return new self(
            databaseId: $data['database_id'],
            databaseReleaseId: $data['database_release_id'],
            object: $data['object'],
            observationStatus: DatabaseJoinCandidateDataObservationStatus::from($data['observation_status']),
            cost: $data['cost'] ?? null,
            coverage: $data['coverage'] ?? null,
            executionFailure: isset($data['execution_failure']) ? HomologyQueryContextExecutionFailure::fromArray($data['execution_failure']) : null,
            homologySearchId: $data['homology_search_id'] ?? null,
            queryContext: $data['query_context'] ?? null,
            resolvedParameters: $data['resolved_parameters'] ?? null,
            searchProvenance: $data['search_provenance'] ?? null,
            warnings: isset($data['warnings']) ? array_map(fn ($item) => SearchWarning::fromArray($item), $data['warnings']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'database_id' => $this->databaseId,
            'database_release_id' => $this->databaseReleaseId,
            'object' => $this->object,
            'observation_status' => $this->observationStatus->value,
            'cost' => $this->cost,
            'coverage' => $this->coverage,
            'execution_failure' => $this->executionFailure?->toArray(),
            'homology_search_id' => $this->homologySearchId,
            'query_context' => $this->queryContext,
            'resolved_parameters' => $this->resolvedParameters,
            'search_provenance' => $this->searchProvenance,
            'warnings' => $this->warnings !== null ? array_map(fn ($item) => $item->toArray(), $this->warnings) : null,
        ];
    }
}
