<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyFilterContainsAny implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $field,
        /** @var array<string> */
        public array $values,
        public string $op = 'contains_any',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'field',
            'values',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyFilterContainsAny::fromArray()");
            }
        }
        return new self(
            field: $data['field'],
            values: $data['values'],
            op: $data['op'] ?? 'contains_any',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'field' => $this->field,
            'values' => $this->values,
            'op' => $this->op,
        ];
    }
}
