<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyDatabase implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $displayName,
        /** @var array<\Rafflesia\Resource\Evidence>|null */
        public ?array $evidence,
        /** Opaque database id used to enumerate immutable releases. */
        public string $id,
        /** Whether omitting both database selectors currently resolves to this database and its advertised default release. */
        public bool $isDefault,
        /**
         * MSA configuration roles this corpus is explicitly registered to serve. Empty means the corpus cannot be used by an AF2, AF3, or ColabFold MSA build.
         * @var array<string>|null
         */
        public ?array $msaRoles,
        /** @var array<string>|null */
        public ?array $queryKinds,
        /** Human-readable stable database slug. */
        public string $slug,
        public ?string $defaultReleaseAlias = null,
        /** Immutable release currently selected by the default alias. */
        public ?string $defaultReleaseId = null,
        public ?string $description = null,
        /** Institution that curates the upstream corpus. Absent when the served corpus has no declared curator. */
        public ?string $organization = null,
        public string $moleculeType = 'protein',
        /** Always homology_database. */
        public string $object = 'homology_database',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'display_name',
            'evidence',
            'id',
            'is_default',
            'msa_roles',
            'query_kinds',
            'slug',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyDatabase::fromArray()");
            }
        }
        return new self(
            displayName: $data['display_name'],
            evidence: isset($data['evidence']) ? array_map(fn ($item) => Evidence::from($item), $data['evidence']) : null,
            id: $data['id'],
            isDefault: $data['is_default'],
            msaRoles: $data['msa_roles'] ?? null,
            queryKinds: $data['query_kinds'] ?? null,
            slug: $data['slug'],
            defaultReleaseAlias: $data['default_release_alias'] ?? null,
            defaultReleaseId: $data['default_release_id'] ?? null,
            description: $data['description'] ?? null,
            organization: $data['organization'] ?? null,
            moleculeType: $data['molecule_type'] ?? 'protein',
            object: $data['object'] ?? 'homology_database',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'display_name' => $this->displayName,
            'evidence' => $this->evidence !== null ? array_map(fn ($item) => $item->value, $this->evidence) : null,
            'id' => $this->id,
            'is_default' => $this->isDefault,
            'msa_roles' => $this->msaRoles,
            'query_kinds' => $this->queryKinds,
            'slug' => $this->slug,
            'default_release_alias' => $this->defaultReleaseAlias,
            'default_release_id' => $this->defaultReleaseId,
            'description' => $this->description,
            'organization' => $this->organization,
            'molecule_type' => $this->moleculeType,
            'object' => $this->object,
        ];
    }
}
