<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class HomologyMaxSimMeasurements implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public float $bidirectional,
        public float $queryToTarget,
        public float $targetToQuery,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'bidirectional',
            'query_to_target',
            'target_to_query',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for HomologyMaxSimMeasurements::fromArray()");
            }
        }
        return new self(
            bidirectional: $data['bidirectional'],
            queryToTarget: $data['query_to_target'],
            targetToQuery: $data['target_to_query'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'bidirectional' => $this->bidirectional,
            'query_to_target' => $this->queryToTarget,
            'target_to_query' => $this->targetToQuery,
        ];
    }
}
