<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class InterfaceModel implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $chainAId,
        public string $chainBId,
        public int $contactPairCount,
        public string $interfaceId,
        public string $method,
        public float $radius,
        public int $residueCountA,
        public int $residueCountB,
        /** @var array<\Rafflesia\Resource\ResiduePointer>|null */
        public ?array $residuesA,
        /** @var array<\Rafflesia\Resource\ResiduePointer>|null */
        public ?array $residuesB,
        public string $structureId,
        public ?string $assemblyId = null,
        /** @var array<\Rafflesia\Resource\ContactPair>|null */
        public ?array $contactPairs = null,
        public ?bool $isContactPairsTruncated = null,
        public ?float $meanDistanceAngstrom = null,
        public ?float $minDistanceAngstrom = null,
        public ?string $modelId = null,
        /**
         * Per-residue contact rollup for chain A, distance-sorted. Present when include_residue_contacts is set.
         * @var array<\Rafflesia\Resource\InterfaceResidueContact>|null
         */
        public ?array $residueContactsA = null,
        /**
         * Per-residue contact rollup for chain B, distance-sorted. Present when include_residue_contacts is set.
         * @var array<\Rafflesia\Resource\InterfaceResidueContact>|null
         */
        public ?array $residueContactsB = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'chain_a_id',
            'chain_b_id',
            'contact_pair_count',
            'interface_id',
            'method',
            'radius',
            'residue_count_a',
            'residue_count_b',
            'residues_a',
            'residues_b',
            'structure_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for InterfaceModel::fromArray()");
            }
        }
        return new self(
            chainAId: $data['chain_a_id'],
            chainBId: $data['chain_b_id'],
            contactPairCount: $data['contact_pair_count'],
            interfaceId: $data['interface_id'],
            method: $data['method'],
            radius: $data['radius'],
            residueCountA: $data['residue_count_a'],
            residueCountB: $data['residue_count_b'],
            residuesA: isset($data['residues_a']) ? array_map(fn ($item) => ResiduePointer::fromArray($item), $data['residues_a']) : null,
            residuesB: isset($data['residues_b']) ? array_map(fn ($item) => ResiduePointer::fromArray($item), $data['residues_b']) : null,
            structureId: $data['structure_id'],
            assemblyId: $data['assembly_id'] ?? null,
            contactPairs: isset($data['contact_pairs']) ? array_map(fn ($item) => ContactPair::fromArray($item), $data['contact_pairs']) : null,
            isContactPairsTruncated: $data['is_contact_pairs_truncated'] ?? null,
            meanDistanceAngstrom: $data['mean_distance_angstrom'] ?? null,
            minDistanceAngstrom: $data['min_distance_angstrom'] ?? null,
            modelId: $data['model_id'] ?? null,
            residueContactsA: isset($data['residue_contacts_a']) ? array_map(fn ($item) => InterfaceResidueContact::fromArray($item), $data['residue_contacts_a']) : null,
            residueContactsB: isset($data['residue_contacts_b']) ? array_map(fn ($item) => InterfaceResidueContact::fromArray($item), $data['residue_contacts_b']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'chain_a_id' => $this->chainAId,
            'chain_b_id' => $this->chainBId,
            'contact_pair_count' => $this->contactPairCount,
            'interface_id' => $this->interfaceId,
            'method' => $this->method,
            'radius' => $this->radius,
            'residue_count_a' => $this->residueCountA,
            'residue_count_b' => $this->residueCountB,
            'residues_a' => $this->residuesA !== null ? array_map(fn ($item) => $item->toArray(), $this->residuesA) : null,
            'residues_b' => $this->residuesB !== null ? array_map(fn ($item) => $item->toArray(), $this->residuesB) : null,
            'structure_id' => $this->structureId,
            'assembly_id' => $this->assemblyId,
            'contact_pairs' => $this->contactPairs !== null ? array_map(fn ($item) => $item->toArray(), $this->contactPairs) : null,
            'is_contact_pairs_truncated' => $this->isContactPairsTruncated,
            'mean_distance_angstrom' => $this->meanDistanceAngstrom,
            'min_distance_angstrom' => $this->minDistanceAngstrom,
            'model_id' => $this->modelId,
            'residue_contacts_a' => $this->residueContactsA !== null ? array_map(fn ($item) => $item->toArray(), $this->residueContactsA) : null,
            'residue_contacts_b' => $this->residueContactsB !== null ? array_map(fn ($item) => $item->toArray(), $this->residueContactsB) : null,
        ];
    }
}
