<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class InterfaceDetectRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $structureId,
        /** Database name published with the relation */
        public ?string $database = null,
        public ?bool $includePairs = null,
        /** Include a per-residue contact rollup (residue_contacts_a/b) built from the full contact set before any max_pairs cap. */
        public ?bool $includeResidueContacts = null,
        public ?bool $includeSameChain = null,
        /** Include water (HOH/WAT/DOD) residues; by default solvent is excluded so an interface reflects polymer-polymer contacts. */
        public ?bool $includeWaters = null,
        public ?int $maxInterfaces = null,
        public ?int $maxPairs = null,
        public ?string $method = null,
        /** For same-chain contacts, drop pairs whose residues are fewer than N positions apart (|pos_a - pos_b| < N). Removes trivial sequence-adjacent contacts. Cross-chain contacts are unaffected. */
        public ?int $minSequenceSeparation = null,
        /** Requested durable relation format; parquet is the initial physical format */
        public ?FoldSearchRequestOutputFormat $outputFormat = null,
        /** Local output path or alias for a durable relation artifact */
        public ?string $outputRelation = null,
        /**
         * Requested physical partition columns
         * @var array<string>|null
         */
        public ?array $partitionBy = null,
        /** When output_relation is requested, include at most this many rows as a non-pageable preview */
        public ?int $previewLimit = null,
        public ?float $radius = null,
        /** Requested logical relation name */
        public ?string $relation = null,
        /** Immutable database release published with the relation */
        public ?string $release = null,
        /**
         * Restrict contacts to those where at least one partner is a named residue. Each entry is CHAIN/POSITION (e.g. A/57) or a bare POSITION (e.g. 57, any chain); comma-separated lists are also accepted. Scopes every derived field (residue lists, counts, rollups, distances), not just contact_pairs.
         * @var array<string>|null
         */
        public ?array $residues = null,
        /** With residues set, keep a contact only when BOTH partners are named (instead of the default: either partner). Use to measure geometry among a specific residue set (e.g. a catalytic triad's internal H-bonds) rather than everything those residues touch. */
        public ?bool $residuesRequireBoth = null,
        /**
         * Requested physical sort columns
         * @var array<string>|null
         */
        public ?array $sortBy = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'structure_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for InterfaceDetectRequest::fromArray()");
            }
        }
        return new self(
            structureId: $data['structure_id'],
            database: $data['database'] ?? null,
            includePairs: $data['include_pairs'] ?? null,
            includeResidueContacts: $data['include_residue_contacts'] ?? null,
            includeSameChain: $data['include_same_chain'] ?? null,
            includeWaters: $data['include_waters'] ?? null,
            maxInterfaces: $data['max_interfaces'] ?? null,
            maxPairs: $data['max_pairs'] ?? null,
            method: $data['method'] ?? null,
            minSequenceSeparation: $data['min_sequence_separation'] ?? null,
            outputFormat: isset($data['output_format']) ? FoldSearchRequestOutputFormat::from($data['output_format']) : null,
            outputRelation: $data['output_relation'] ?? null,
            partitionBy: $data['partition_by'] ?? null,
            previewLimit: $data['preview_limit'] ?? null,
            radius: $data['radius'] ?? null,
            relation: $data['relation'] ?? null,
            release: $data['release'] ?? null,
            residues: $data['residues'] ?? null,
            residuesRequireBoth: $data['residues_require_both'] ?? null,
            sortBy: $data['sort_by'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'structure_id' => $this->structureId,
            'database' => $this->database,
            'include_pairs' => $this->includePairs,
            'include_residue_contacts' => $this->includeResidueContacts,
            'include_same_chain' => $this->includeSameChain,
            'include_waters' => $this->includeWaters,
            'max_interfaces' => $this->maxInterfaces,
            'max_pairs' => $this->maxPairs,
            'method' => $this->method,
            'min_sequence_separation' => $this->minSequenceSeparation,
            'output_format' => $this->outputFormat?->value,
            'output_relation' => $this->outputRelation,
            'partition_by' => $this->partitionBy,
            'preview_limit' => $this->previewLimit,
            'radius' => $this->radius,
            'relation' => $this->relation,
            'release' => $this->release,
            'residues' => $this->residues,
            'residues_require_both' => $this->residuesRequireBoth,
            'sort_by' => $this->sortBy,
        ];
    }
}
