<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class JobCleanupData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $deletedTerminalCount,
        public bool $dryRun,
        public int $limit,
        public int $markedFailedCount,
        public string $referenceAt,
        /** @var array<string>|null */
        public ?array $staleCandidateJobIds = null,
        public ?string $staleCutoffAt = null,
        /** @var array<string>|null */
        public ?array $terminalCandidateJobIds = null,
        public ?string $terminalCutoffAt = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'deleted_terminal_count',
            'dry_run',
            'limit',
            'marked_failed_count',
            'reference_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for JobCleanupData::fromArray()");
            }
        }
        return new self(
            deletedTerminalCount: $data['deleted_terminal_count'],
            dryRun: $data['dry_run'],
            limit: $data['limit'],
            markedFailedCount: $data['marked_failed_count'],
            referenceAt: $data['reference_at'],
            staleCandidateJobIds: $data['stale_candidate_job_ids'] ?? null,
            staleCutoffAt: $data['stale_cutoff_at'] ?? null,
            terminalCandidateJobIds: $data['terminal_candidate_job_ids'] ?? null,
            terminalCutoffAt: $data['terminal_cutoff_at'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'deleted_terminal_count' => $this->deletedTerminalCount,
            'dry_run' => $this->dryRun,
            'limit' => $this->limit,
            'marked_failed_count' => $this->markedFailedCount,
            'reference_at' => $this->referenceAt,
            'stale_candidate_job_ids' => $this->staleCandidateJobIds,
            'stale_cutoff_at' => $this->staleCutoffAt,
            'terminal_candidate_job_ids' => $this->terminalCandidateJobIds,
            'terminal_cutoff_at' => $this->terminalCutoffAt,
        ];
    }
}
