<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class JobQueueData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\JobQueueTask>|null */
        public ?array $active,
        /** @var array<\Rafflesia\Resource\JobQueueTask>|null */
        public ?array $pending,
        public JobQueueInfo $queue,
        /** @var array<\Rafflesia\Resource\JobQueueTask>|null */
        public ?array $retry,
        /** @var array<\Rafflesia\Resource\JobQueueTask>|null */
        public ?array $scheduled,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'active',
            'pending',
            'queue',
            'retry',
            'scheduled',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for JobQueueData::fromArray()");
            }
        }
        return new self(
            active: isset($data['active']) ? array_map(fn ($item) => JobQueueTask::fromArray($item), $data['active']) : null,
            pending: isset($data['pending']) ? array_map(fn ($item) => JobQueueTask::fromArray($item), $data['pending']) : null,
            queue: JobQueueInfo::fromArray($data['queue']),
            retry: isset($data['retry']) ? array_map(fn ($item) => JobQueueTask::fromArray($item), $data['retry']) : null,
            scheduled: isset($data['scheduled']) ? array_map(fn ($item) => JobQueueTask::fromArray($item), $data['scheduled']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'active' => $this->active !== null ? array_map(fn ($item) => $item->toArray(), $this->active) : null,
            'pending' => $this->pending !== null ? array_map(fn ($item) => $item->toArray(), $this->pending) : null,
            'queue' => $this->queue->toArray(),
            'retry' => $this->retry !== null ? array_map(fn ($item) => $item->toArray(), $this->retry) : null,
            'scheduled' => $this->scheduled !== null ? array_map(fn ($item) => $item->toArray(), $this->scheduled) : null,
        ];
    }
}
