<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class JoinApprovalCreateRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $evidenceId,
        public string $reason,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'evidence_id',
            'reason',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for JoinApprovalCreateRequest::fromArray()");
            }
        }
        return new self(
            evidenceId: $data['evidence_id'],
            reason: $data['reason'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'evidence_id' => $this->evidenceId,
            'reason' => $this->reason,
        ];
    }
}
