<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class MappedVariant implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Whether parsing succeeded. */
        public bool $isValid,
        /** Mutation class carried from parse. */
        public string $mutationType,
        /** Original mutation string. */
        public string $raw,
        /** Whether wildtype_aa matches the amino acid at the mapped structure residue. */
        public bool $wildtypeMatches,
        /** Mutant amino acid, or X for nonsense. */
        public ?string $mutantAa = null,
        /** 1-based sequence position. */
        public ?int $sequencePosition = null,
        /** Chain id of the mapped structure residue (empty when unmapped). */
        public ?string $structureChainId = null,
        /** Single-letter amino acid found at the mapped structure residue. */
        public ?string $structureResidueAa = null,
        /** 0-based index of the mapped residue in the structure residue array (0 when unmapped). */
        public ?int $structureResidueIndex = null,
        /** Residue number of the mapped structure residue (0 when unmapped). */
        public ?int $structureResidueNumber = null,
        /**
         * Mapping warnings (out-of-range, wildtype mismatch, residue not found).
         * @var array<\Rafflesia\Resource\SearchWarning>|null
         */
        public ?array $warnings = null,
        /** Wildtype amino acid from parse. */
        public ?string $wildtypeAa = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_valid',
            'mutation_type',
            'raw',
            'wildtype_matches',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for MappedVariant::fromArray()");
            }
        }
        return new self(
            isValid: $data['is_valid'],
            mutationType: $data['mutation_type'],
            raw: $data['raw'],
            wildtypeMatches: $data['wildtype_matches'],
            mutantAa: $data['mutant_aa'] ?? null,
            sequencePosition: $data['sequence_position'] ?? null,
            structureChainId: $data['structure_chain_id'] ?? null,
            structureResidueAa: $data['structure_residue_aa'] ?? null,
            structureResidueIndex: $data['structure_residue_index'] ?? null,
            structureResidueNumber: $data['structure_residue_number'] ?? null,
            warnings: isset($data['warnings']) ? array_map(fn ($item) => SearchWarning::fromArray($item), $data['warnings']) : null,
            wildtypeAa: $data['wildtype_aa'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_valid' => $this->isValid,
            'mutation_type' => $this->mutationType,
            'raw' => $this->raw,
            'wildtype_matches' => $this->wildtypeMatches,
            'mutant_aa' => $this->mutantAa,
            'sequence_position' => $this->sequencePosition,
            'structure_chain_id' => $this->structureChainId,
            'structure_residue_aa' => $this->structureResidueAa,
            'structure_residue_index' => $this->structureResidueIndex,
            'structure_residue_number' => $this->structureResidueNumber,
            'warnings' => $this->warnings !== null ? array_map(fn ($item) => $item->toArray(), $this->warnings) : null,
            'wildtype_aa' => $this->wildtypeAa,
        ];
    }
}
