<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class MemberResourceGrant implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        /** @var array<string>|null */
        public ?array $roles,
        public ?string $name = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'roles',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for MemberResourceGrant::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            roles: $data['roles'] ?? null,
            name: $data['name'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'roles' => $this->roles,
            'name' => $this->name,
        ];
    }
}
