<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class MmseqSearchData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        /** @var array<string>|null */
        public ?array $command,
        public int $hitCount,
        public string $query,
        public string $target,
        public ?bool $dryRun = null,
        /** @var array<\Rafflesia\Resource\MmseqSearchHit>|null */
        public ?array $hits = null,
        public ?string $manifestId = null,
        public ?ObjectArtifactMaterializeData $materialization = null,
        public ?ObjectRef $outputObject = null,
        public ?string $outputPath = null,
        /** @var array<string, mixed>|null */
        public ?array $parameters = null,
        public ?ObjectRef $rawOutputObject = null,
        /** Immutable relation artifact emitted when output_relation is requested */
        public ?RelationArtifactData $relation = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'command',
            'hit_count',
            'query',
            'target',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for MmseqSearchData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            command: $data['command'] ?? null,
            hitCount: $data['hit_count'],
            query: $data['query'],
            target: $data['target'],
            dryRun: $data['dry_run'] ?? null,
            hits: isset($data['hits']) ? array_map(fn ($item) => MmseqSearchHit::fromArray($item), $data['hits']) : null,
            manifestId: $data['manifest_id'] ?? null,
            materialization: isset($data['materialization']) ? ObjectArtifactMaterializeData::fromArray($data['materialization']) : null,
            outputObject: isset($data['output_object']) ? ObjectRef::fromArray($data['output_object']) : null,
            outputPath: $data['output_path'] ?? null,
            parameters: $data['parameters'] ?? null,
            rawOutputObject: isset($data['raw_output_object']) ? ObjectRef::fromArray($data['raw_output_object']) : null,
            relation: isset($data['relation']) ? RelationArtifactData::fromArray($data['relation']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'command' => $this->command,
            'hit_count' => $this->hitCount,
            'query' => $this->query,
            'target' => $this->target,
            'dry_run' => $this->dryRun,
            'hits' => $this->hits !== null ? array_map(fn ($item) => $item->toArray(), $this->hits) : null,
            'manifest_id' => $this->manifestId,
            'materialization' => $this->materialization?->toArray(),
            'output_object' => $this->outputObject?->toArray(),
            'output_path' => $this->outputPath,
            'parameters' => $this->parameters,
            'raw_output_object' => $this->rawOutputObject?->toArray(),
            'relation' => $this->relation?->toArray(),
        ];
    }
}
