<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ModelUsageLine implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Deprecated: use cost_total. Same value as cost_total.
         * @deprecated
         */
        public float $cost,
        /** Discount applied to this line item (cost_subtotal − cost_total). */
        public float $costDiscount,
        /** Cost before discounts (quantity × unit_price). */
        public float $costSubtotal,
        /** Amount charged after discounts (cost_subtotal − cost_discount). */
        public float $costTotal,
        /** Three-letter currency code (ISO 4217, for example, 'USD'). */
        public string $currency,
        /** Endpoint identifier that was used (for example, 'rafflesia/homology'). */
        public string $endpointId,
        /** Percentage discount applied to this line item (for example, 20 = 20% discount). Null when no percentage discount applies. Usage billed at different discount rates appears as separate rows, like unit_price. */
        public ?float $percentDiscount,
        /** Quantity of usage in the specified billing unit. */
        public float $quantity,
        /** The billing unit (for example, 'search', 'image', 'video', or a compute unit). */
        public string $unit,
        /** Per-unit price before percentage discounts. */
        public float $unitPrice,
        /** Authentication method label (for example, 'Production Key' or 'User token'). Only populated when 'auth_method' is included in expand. */
        public ?string $authMethod = null,
        /** Structured authentication method identity. Only populated when 'auth_method_structured' is included in expand. */
        public ?ModelAuthMethod $authMethodStructured = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'cost',
            'cost_discount',
            'cost_subtotal',
            'cost_total',
            'currency',
            'endpoint_id',
            'percent_discount',
            'quantity',
            'unit',
            'unit_price',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ModelUsageLine::fromArray()");
            }
        }
        return new self(
            cost: $data['cost'],
            costDiscount: $data['cost_discount'],
            costSubtotal: $data['cost_subtotal'],
            costTotal: $data['cost_total'],
            currency: $data['currency'],
            endpointId: $data['endpoint_id'],
            percentDiscount: $data['percent_discount'] ?? null,
            quantity: $data['quantity'],
            unit: $data['unit'],
            unitPrice: $data['unit_price'],
            authMethod: $data['auth_method'] ?? null,
            authMethodStructured: isset($data['auth_method_structured']) ? ModelAuthMethod::fromArray($data['auth_method_structured']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'cost' => $this->cost,
            'cost_discount' => $this->costDiscount,
            'cost_subtotal' => $this->costSubtotal,
            'cost_total' => $this->costTotal,
            'currency' => $this->currency,
            'endpoint_id' => $this->endpointId,
            'percent_discount' => $this->percentDiscount,
            'quantity' => $this->quantity,
            'unit' => $this->unit,
            'unit_price' => $this->unitPrice,
            'auth_method' => $this->authMethod,
            'auth_method_structured' => $this->authMethodStructured?->toArray(),
        ];
    }
}
