<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class MountStatusUpdateRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public RegistryMountStatus $status,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'status',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for MountStatusUpdateRequest::fromArray()");
            }
        }
        return new self(
            status: RegistryMountStatus::from($data['status']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'status' => $this->status->value,
        ];
    }
}
