<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class MsaBuildData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        /** @var array<string>|null */
        public ?array $command,
        public ?ObjectRef $alignmentObject = null,
        public ?bool $cacheHit = null,
        public ?string $cacheKey = null,
        public ?string $cacheMode = null,
        public ?bool $dryRun = null,
        public ?ObjectRef $inputObject = null,
        public ?string $inputPath = null,
        public ?MsaInspectData $inspection = null,
        public ?MsaArtifactManifest $manifest = null,
        public ?ObjectRef $manifestObject = null,
        public ?string $outputPath = null,
        /** @var array<string, mixed>|null */
        public ?array $parameters = null,
        public ?ObjectRef $rawOutputObject = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'command',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for MsaBuildData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            command: $data['command'] ?? null,
            alignmentObject: isset($data['alignment_object']) ? ObjectRef::fromArray($data['alignment_object']) : null,
            cacheHit: $data['cache_hit'] ?? null,
            cacheKey: $data['cache_key'] ?? null,
            cacheMode: $data['cache_mode'] ?? null,
            dryRun: $data['dry_run'] ?? null,
            inputObject: isset($data['input_object']) ? ObjectRef::fromArray($data['input_object']) : null,
            inputPath: $data['input_path'] ?? null,
            inspection: isset($data['inspection']) ? MsaInspectData::fromArray($data['inspection']) : null,
            manifest: isset($data['manifest']) ? MsaArtifactManifest::fromArray($data['manifest']) : null,
            manifestObject: isset($data['manifest_object']) ? ObjectRef::fromArray($data['manifest_object']) : null,
            outputPath: $data['output_path'] ?? null,
            parameters: $data['parameters'] ?? null,
            rawOutputObject: isset($data['raw_output_object']) ? ObjectRef::fromArray($data['raw_output_object']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'command' => $this->command,
            'alignment_object' => $this->alignmentObject?->toArray(),
            'cache_hit' => $this->cacheHit,
            'cache_key' => $this->cacheKey,
            'cache_mode' => $this->cacheMode,
            'dry_run' => $this->dryRun,
            'input_object' => $this->inputObject?->toArray(),
            'input_path' => $this->inputPath,
            'inspection' => $this->inspection?->toArray(),
            'manifest' => $this->manifest?->toArray(),
            'manifest_object' => $this->manifestObject?->toArray(),
            'output_path' => $this->outputPath,
            'parameters' => $this->parameters,
            'raw_output_object' => $this->rawOutputObject?->toArray(),
        ];
    }
}
