<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ObjectArtifactImportRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Immutable material kind: blast_db, blast_index, foldseek_index, mmseqs2_index, hmmer_index, model_weights, model_parameters, sequence_database, structure_database, annotation_database, or task_input. */
        public string $kind,
        /** Allow import even when required material file sets are incomplete. */
        public ?bool $allowIncomplete = null,
        /** Object id containing an archive inventory manifest whose extracted member objects become a collection. Mutually exclusive with path and archive_inventory_path. */
        public ?string $archiveInventoryObjectId = null,
        /** Archive inventory manifest whose extracted member objects become a collection without a local copy. Mutually exclusive with path and archive_inventory_object_id. */
        public ?string $archiveInventoryPath = null,
        /**
         * Archive member paths that must have extracted, hash-verified objects before marker files are created.
         * @var array<string>|null
         */
        public ?array $archiveRequiredMemberPaths = null,
        /** Optional dataset name carried into the manifest. */
        public ?string $datasetName = null,
        /** Optional dataset version carried into the manifest. */
        public ?string $datasetVersion = null,
        /**
         * Immutable manifest ids required by this collection.
         * @var array<string>|null
         */
        public ?array $dependencyManifestIds = null,
        /** Force directory input to use a shard-aware collection manifest even when it has no nested directories. */
        public ?bool $isCollection = null,
        /** Optional portable path prefix prepended to archive member paths in the collection. */
        public ?string $layoutPrefix = null,
        /** License identifier or source license label for this collection. */
        public ?string $license = null,
        /**
         * Optional portable marker-file paths created after every archive member object is validated.
         * @var array<string>|null
         */
        public ?array $markerPaths = null,
        /** Expected absolute sandbox mount path for this collection. */
        public ?string $mountPath = null,
        /** Optional manifest name. */
        public ?string $name = null,
        /** Optional local directory where the stamped manifest JSON should be written. */
        public ?string $outputDir = null,
        /** Local material file, directory tree, or supported database/index prefix path. Mutually exclusive with archive_inventory_path and archive_inventory_object_id. */
        public ?string $path = null,
        /** Target collection shard size in bytes. Files are never split; zero defaults to 4 GiB. */
        public ?int $shardSizeBytes = null,
        /** Source distribution URI recorded as provenance; no implicit download is performed. */
        public ?string $sourceUri = null,
        /** Optional external tool name. Defaults from kind. */
        public ?string $toolName = null,
        /** Optional external tool version string. */
        public ?string $toolVersion = null,
        /** Optional manifest version. */
        public ?string $version = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'kind',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ObjectArtifactImportRequest::fromArray()");
            }
        }
        return new self(
            kind: $data['kind'],
            allowIncomplete: $data['allow_incomplete'] ?? null,
            archiveInventoryObjectId: $data['archive_inventory_object_id'] ?? null,
            archiveInventoryPath: $data['archive_inventory_path'] ?? null,
            archiveRequiredMemberPaths: $data['archive_required_member_paths'] ?? null,
            datasetName: $data['dataset_name'] ?? null,
            datasetVersion: $data['dataset_version'] ?? null,
            dependencyManifestIds: $data['dependency_manifest_ids'] ?? null,
            isCollection: $data['is_collection'] ?? null,
            layoutPrefix: $data['layout_prefix'] ?? null,
            license: $data['license'] ?? null,
            markerPaths: $data['marker_paths'] ?? null,
            mountPath: $data['mount_path'] ?? null,
            name: $data['name'] ?? null,
            outputDir: $data['output_dir'] ?? null,
            path: $data['path'] ?? null,
            shardSizeBytes: $data['shard_size_bytes'] ?? null,
            sourceUri: $data['source_uri'] ?? null,
            toolName: $data['tool_name'] ?? null,
            toolVersion: $data['tool_version'] ?? null,
            version: $data['version'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind,
            'allow_incomplete' => $this->allowIncomplete,
            'archive_inventory_object_id' => $this->archiveInventoryObjectId,
            'archive_inventory_path' => $this->archiveInventoryPath,
            'archive_required_member_paths' => $this->archiveRequiredMemberPaths,
            'dataset_name' => $this->datasetName,
            'dataset_version' => $this->datasetVersion,
            'dependency_manifest_ids' => $this->dependencyManifestIds,
            'is_collection' => $this->isCollection,
            'layout_prefix' => $this->layoutPrefix,
            'license' => $this->license,
            'marker_paths' => $this->markerPaths,
            'mount_path' => $this->mountPath,
            'name' => $this->name,
            'output_dir' => $this->outputDir,
            'path' => $this->path,
            'shard_size_bytes' => $this->shardSizeBytes,
            'source_uri' => $this->sourceUri,
            'tool_name' => $this->toolName,
            'tool_version' => $this->toolVersion,
            'version' => $this->version,
        ];
    }
}
