<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ObjectReadDiagnostics implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $contentTypeSource = null,
        public ?int $decodeElapsedMs = null,
        public ?bool $isLocal = null,
        public ?bool $isRemote = null,
        public ?int $maxReadBytes = null,
        public ?int $objectSizeBytes = null,
        public ?int $readElapsedMs = null,
        public ?string $readSource = null,
        public ?int $requestedBytes = null,
        public ?int $resolveElapsedMs = null,
        public ?string $resolveSource = null,
        public ?int $returnedBytes = null,
        public ?int $totalElapsedMs = null,
        public ?bool $usedRangeRead = null,
        public ?bool $wasSizeBounded = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            contentTypeSource: $data['content_type_source'] ?? null,
            decodeElapsedMs: $data['decode_elapsed_ms'] ?? null,
            isLocal: $data['is_local'] ?? null,
            isRemote: $data['is_remote'] ?? null,
            maxReadBytes: $data['max_read_bytes'] ?? null,
            objectSizeBytes: $data['object_size_bytes'] ?? null,
            readElapsedMs: $data['read_elapsed_ms'] ?? null,
            readSource: $data['read_source'] ?? null,
            requestedBytes: $data['requested_bytes'] ?? null,
            resolveElapsedMs: $data['resolve_elapsed_ms'] ?? null,
            resolveSource: $data['resolve_source'] ?? null,
            returnedBytes: $data['returned_bytes'] ?? null,
            totalElapsedMs: $data['total_elapsed_ms'] ?? null,
            usedRangeRead: $data['used_range_read'] ?? null,
            wasSizeBounded: $data['was_size_bounded'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'content_type_source' => $this->contentTypeSource,
            'decode_elapsed_ms' => $this->decodeElapsedMs,
            'is_local' => $this->isLocal,
            'is_remote' => $this->isRemote,
            'max_read_bytes' => $this->maxReadBytes,
            'object_size_bytes' => $this->objectSizeBytes,
            'read_elapsed_ms' => $this->readElapsedMs,
            'read_source' => $this->readSource,
            'requested_bytes' => $this->requestedBytes,
            'resolve_elapsed_ms' => $this->resolveElapsedMs,
            'resolve_source' => $this->resolveSource,
            'returned_bytes' => $this->returnedBytes,
            'total_elapsed_ms' => $this->totalElapsedMs,
            'used_range_read' => $this->usedRangeRead,
            'was_size_bounded' => $this->wasSizeBounded,
        ];
    }
}
