<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ObjectArtifactRequiredSet implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $isComplete,
        public string $name,
        /** @var array<string>|null */
        public ?array $requiredSuffixes,
        /** @var array<string>|null */
        public ?array $missingPaths = null,
        /** @var array<string>|null */
        public ?array $missingSuffixes = null,
        public ?string $prefix = null,
        /** @var array<string>|null */
        public ?array $presentSuffixes = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_complete',
            'name',
            'required_suffixes',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ObjectArtifactRequiredSet::fromArray()");
            }
        }
        return new self(
            isComplete: $data['is_complete'],
            name: $data['name'],
            requiredSuffixes: $data['required_suffixes'] ?? null,
            missingPaths: $data['missing_paths'] ?? null,
            missingSuffixes: $data['missing_suffixes'] ?? null,
            prefix: $data['prefix'] ?? null,
            presentSuffixes: $data['present_suffixes'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_complete' => $this->isComplete,
            'name' => $this->name,
            'required_suffixes' => $this->requiredSuffixes,
            'missing_paths' => $this->missingPaths,
            'missing_suffixes' => $this->missingSuffixes,
            'prefix' => $this->prefix,
            'present_suffixes' => $this->presentSuffixes,
        ];
    }
}
