<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ObjectArtifactCacheEvictRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** List cache files without deleting them */
        public ?bool $dryRun = null,
        /** Neutral object-artifact manifest object id */
        public ?string $manifestObjectId = null,
        /** Local neutral object-artifact manifest path */
        public ?string $manifestPath = null,
        /** If positive, evict oldest selected cache files until selected cache bytes are less than or equal to this limit. Zero evicts every selected file. */
        public ?int $maxBytes = null,
        /** Optional cache policy for TTL and pinned-path eviction controls. */
        public ?CacheEvictionPolicy $policy = null,
        /**
         * Optional shard ids to evict; empty evicts every shard
         * @var array<string>|null
         */
        public ?array $shards = null,
        /** Local object-artifact cache root */
        public ?string $targetDir = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            dryRun: $data['dry_run'] ?? null,
            manifestObjectId: $data['manifest_object_id'] ?? null,
            manifestPath: $data['manifest_path'] ?? null,
            maxBytes: $data['max_bytes'] ?? null,
            policy: isset($data['policy']) ? CacheEvictionPolicy::fromArray($data['policy']) : null,
            shards: $data['shards'] ?? null,
            targetDir: $data['target_dir'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'dry_run' => $this->dryRun,
            'manifest_object_id' => $this->manifestObjectId,
            'manifest_path' => $this->manifestPath,
            'max_bytes' => $this->maxBytes,
            'policy' => $this->policy?->toArray(),
            'shards' => $this->shards,
            'target_dir' => $this->targetDir,
        ];
    }
}
