<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ObjectMetadataData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $isLocal,
        public string $kind,
        public string $objectId,
        public string $sha256,
        public int $sizeBytes,
        public ?string $bucket = null,
        public ?string $contentType = null,
        public ?string $objectKey = null,
        public ?string $path = null,
        /** @var array<\Rafflesia\Resource\ObjectRecordRef>|null */
        public ?array $recordRefs = null,
        public ?string $storageBackend = null,
        public ?string $uri = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_local',
            'kind',
            'object_id',
            'sha256',
            'size_bytes',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ObjectMetadataData::fromArray()");
            }
        }
        return new self(
            isLocal: $data['is_local'],
            kind: $data['kind'],
            objectId: $data['object_id'],
            sha256: $data['sha256'],
            sizeBytes: $data['size_bytes'],
            bucket: $data['bucket'] ?? null,
            contentType: $data['content_type'] ?? null,
            objectKey: $data['object_key'] ?? null,
            path: $data['path'] ?? null,
            recordRefs: isset($data['record_refs']) ? array_map(fn ($item) => ObjectRecordRef::fromArray($item), $data['record_refs']) : null,
            storageBackend: $data['storage_backend'] ?? null,
            uri: $data['uri'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_local' => $this->isLocal,
            'kind' => $this->kind,
            'object_id' => $this->objectId,
            'sha256' => $this->sha256,
            'size_bytes' => $this->sizeBytes,
            'bucket' => $this->bucket,
            'content_type' => $this->contentType,
            'object_key' => $this->objectKey,
            'path' => $this->path,
            'record_refs' => $this->recordRefs !== null ? array_map(fn ($item) => $item->toArray(), $this->recordRefs) : null,
            'storage_backend' => $this->storageBackend,
            'uri' => $this->uri,
        ];
    }
}
