<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ObjectJsonGetRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $objectId,
        public ?int $limit = null,
        public ?int $maxBytes = null,
        public ?string $path = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'object_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ObjectJsonGetRequest::fromArray()");
            }
        }
        return new self(
            objectId: $data['object_id'],
            limit: $data['limit'] ?? null,
            maxBytes: $data['max_bytes'] ?? null,
            path: $data['path'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'object_id' => $this->objectId,
            'limit' => $this->limit,
            'max_bytes' => $this->maxBytes,
            'path' => $this->path,
        ];
    }
}
