<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum OnboardingStageStatus: string
{
    case Complete = 'complete';
    case Pending = 'pending';
    case Failed = 'failed';
    case NotApplicable = 'not_applicable';
}
