<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class OntologyValidationRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public OntologySnapshotData $snapshot,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'snapshot',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for OntologyValidationRequest::fromArray()");
            }
        }
        return new self(
            snapshot: OntologySnapshotData::fromArray($data['snapshot']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'snapshot' => $this->snapshot->toArray(),
        ];
    }
}
