<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class OntologyRelationData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\OntologyColumnData>|null */
        public ?array $columns,
        public string $description,
        public string $domain,
        public string $entityType,
        public string $grain,
        public string $id,
        public string $name,
        public string $ontologyDigest,
        public string $ontologyVersion,
        /** @var array<string>|null */
        public ?array $primaryKey,
        public string $schemaHash,
        public int $schemaVersion,
        public string $url,
        /** @var array<string>|null */
        public ?array $aliases = null,
        /** @var array<string>|null */
        public ?array $defaultOrder = null,
        /** @var array<\Rafflesia\Resource\OntologyEvidenceRelationshipContractData>|null */
        public ?array $evidenceRelationshipContracts = null,
        public ?string $partitionScope = null,
        /** @var array<string>|null */
        public ?array $qualityNotes = null,
        /** @var array<string>|null */
        public ?array $recommendedFilters = null,
        /** @var array<\Rafflesia\Resource\OntologyRelationshipData>|null */
        public ?array $relationships = null,
        public ?string $rowScopeColumn = null,
        public string $object = 'ontology_relation',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'columns',
            'description',
            'domain',
            'entity_type',
            'grain',
            'id',
            'name',
            'ontology_digest',
            'ontology_version',
            'primary_key',
            'schema_hash',
            'schema_version',
            'url',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for OntologyRelationData::fromArray()");
            }
        }
        return new self(
            columns: isset($data['columns']) ? array_map(fn ($item) => OntologyColumnData::fromArray($item), $data['columns']) : null,
            description: $data['description'],
            domain: $data['domain'],
            entityType: $data['entity_type'],
            grain: $data['grain'],
            id: $data['id'],
            name: $data['name'],
            ontologyDigest: $data['ontology_digest'],
            ontologyVersion: $data['ontology_version'],
            primaryKey: $data['primary_key'] ?? null,
            schemaHash: $data['schema_hash'],
            schemaVersion: $data['schema_version'],
            url: $data['url'],
            aliases: $data['aliases'] ?? null,
            defaultOrder: $data['default_order'] ?? null,
            evidenceRelationshipContracts: isset($data['evidence_relationship_contracts']) ? array_map(fn ($item) => OntologyEvidenceRelationshipContractData::fromArray($item), $data['evidence_relationship_contracts']) : null,
            partitionScope: $data['partition_scope'] ?? null,
            qualityNotes: $data['quality_notes'] ?? null,
            recommendedFilters: $data['recommended_filters'] ?? null,
            relationships: isset($data['relationships']) ? array_map(fn ($item) => OntologyRelationshipData::fromArray($item), $data['relationships']) : null,
            rowScopeColumn: $data['row_scope_column'] ?? null,
            object: $data['object'] ?? 'ontology_relation',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'columns' => $this->columns !== null ? array_map(fn ($item) => $item->toArray(), $this->columns) : null,
            'description' => $this->description,
            'domain' => $this->domain,
            'entity_type' => $this->entityType,
            'grain' => $this->grain,
            'id' => $this->id,
            'name' => $this->name,
            'ontology_digest' => $this->ontologyDigest,
            'ontology_version' => $this->ontologyVersion,
            'primary_key' => $this->primaryKey,
            'schema_hash' => $this->schemaHash,
            'schema_version' => $this->schemaVersion,
            'url' => $this->url,
            'aliases' => $this->aliases,
            'default_order' => $this->defaultOrder,
            'evidence_relationship_contracts' => $this->evidenceRelationshipContracts !== null ? array_map(fn ($item) => $item->toArray(), $this->evidenceRelationshipContracts) : null,
            'partition_scope' => $this->partitionScope,
            'quality_notes' => $this->qualityNotes,
            'recommended_filters' => $this->recommendedFilters,
            'relationships' => $this->relationships !== null ? array_map(fn ($item) => $item->toArray(), $this->relationships) : null,
            'row_scope_column' => $this->rowScopeColumn,
            'object' => $this->object,
        ];
    }
}
