<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum OntologyReleaseCoverageRelationDataStatus: string
{
    case Queryable = 'queryable';
    case Unavailable = 'unavailable';
    case Missing = 'missing';
}
