<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum OntologyReleaseCoverageRelationDataPhysicalSchemaStatus: string
{
    case Verified = 'verified';
    case Drifted = 'drifted';
    case NotMeasured = 'not_measured';
}
