<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class OntologyEvidenceScopeContractData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public OntologyEvidenceScopeContractDataKind $kind,
        public ?string $alignmentIdColumn = null,
        public ?string $objectDomainInstanceColumn = null,
        public ?string $objectEndColumn = null,
        public ?string $objectStartColumn = null,
        public ?string $subjectDomainInstanceColumn = null,
        public ?string $subjectEndColumn = null,
        public ?string $subjectStartColumn = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'kind',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for OntologyEvidenceScopeContractData::fromArray()");
            }
        }
        return new self(
            kind: OntologyEvidenceScopeContractDataKind::from($data['kind']),
            alignmentIdColumn: $data['alignment_id_column'] ?? null,
            objectDomainInstanceColumn: $data['object_domain_instance_column'] ?? null,
            objectEndColumn: $data['object_end_column'] ?? null,
            objectStartColumn: $data['object_start_column'] ?? null,
            subjectDomainInstanceColumn: $data['subject_domain_instance_column'] ?? null,
            subjectEndColumn: $data['subject_end_column'] ?? null,
            subjectStartColumn: $data['subject_start_column'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind->value,
            'alignment_id_column' => $this->alignmentIdColumn,
            'object_domain_instance_column' => $this->objectDomainInstanceColumn,
            'object_end_column' => $this->objectEndColumn,
            'object_start_column' => $this->objectStartColumn,
            'subject_domain_instance_column' => $this->subjectDomainInstanceColumn,
            'subject_end_column' => $this->subjectEndColumn,
            'subject_start_column' => $this->subjectStartColumn,
        ];
    }
}
