<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class OntologyPathQueryPlan implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public bool $isExecutable,
        public string $planDigest,
        /** @var array<\Rafflesia\Resource\DatabaseJoinSourceFragment>|null */
        public ?array $sources,
        public string $sqlFromClause,
        /** @var array<\Rafflesia\Resource\DatabaseJoinEvidenceRequirement>|null */
        public ?array $requiredJoinEvidence = null,
        public string $object = 'ontology_path_query_plan',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'is_executable',
            'plan_digest',
            'sources',
            'sql_from_clause',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for OntologyPathQueryPlan::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            isExecutable: $data['is_executable'],
            planDigest: $data['plan_digest'],
            sources: isset($data['sources']) ? array_map(fn ($item) => DatabaseJoinSourceFragment::fromArray($item), $data['sources']) : null,
            sqlFromClause: $data['sql_from_clause'],
            requiredJoinEvidence: isset($data['required_join_evidence']) ? array_map(fn ($item) => DatabaseJoinEvidenceRequirement::fromArray($item), $data['required_join_evidence']) : null,
            object: $data['object'] ?? 'ontology_path_query_plan',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'is_executable' => $this->isExecutable,
            'plan_digest' => $this->planDigest,
            'sources' => $this->sources !== null ? array_map(fn ($item) => $item->toArray(), $this->sources) : null,
            'sql_from_clause' => $this->sqlFromClause,
            'required_join_evidence' => $this->requiredJoinEvidence !== null ? array_map(fn ($item) => $item->toArray(), $this->requiredJoinEvidence) : null,
            'object' => $this->object,
        ];
    }
}
