<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class OntologyConnectivityImpactData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $fromComponentId,
        public int $fromComponentSize,
        public string $fromRelation,
        public string $id,
        public bool $isAlreadyReachable,
        public string $ontologyDigest,
        public string $ontologyVersion,
        /** Exact a*b closure gain if the proposed anchor merges distinct components. */
        public int $reachablePairGain,
        public OntologySafety $safety,
        public string $toComponentId,
        public int $toComponentSize,
        public string $toRelation,
        public string $formula = 'from_component_size * to_component_size',
        public string $object = 'ontology_connectivity_impact',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'from_component_id',
            'from_component_size',
            'from_relation',
            'id',
            'is_already_reachable',
            'ontology_digest',
            'ontology_version',
            'reachable_pair_gain',
            'safety',
            'to_component_id',
            'to_component_size',
            'to_relation',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for OntologyConnectivityImpactData::fromArray()");
            }
        }
        return new self(
            fromComponentId: $data['from_component_id'],
            fromComponentSize: $data['from_component_size'],
            fromRelation: $data['from_relation'],
            id: $data['id'],
            isAlreadyReachable: $data['is_already_reachable'],
            ontologyDigest: $data['ontology_digest'],
            ontologyVersion: $data['ontology_version'],
            reachablePairGain: $data['reachable_pair_gain'],
            safety: OntologySafety::from($data['safety']),
            toComponentId: $data['to_component_id'],
            toComponentSize: $data['to_component_size'],
            toRelation: $data['to_relation'],
            formula: $data['formula'] ?? 'from_component_size * to_component_size',
            object: $data['object'] ?? 'ontology_connectivity_impact',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'from_component_id' => $this->fromComponentId,
            'from_component_size' => $this->fromComponentSize,
            'from_relation' => $this->fromRelation,
            'id' => $this->id,
            'is_already_reachable' => $this->isAlreadyReachable,
            'ontology_digest' => $this->ontologyDigest,
            'ontology_version' => $this->ontologyVersion,
            'reachable_pair_gain' => $this->reachablePairGain,
            'safety' => $this->safety->value,
            'to_component_id' => $this->toComponentId,
            'to_component_size' => $this->toComponentSize,
            'to_relation' => $this->toRelation,
            'formula' => $this->formula,
            'object' => $this->object,
        ];
    }
}
