<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum OntologyPathListDataSafetyBasis: string
{
    case DeclaredContract = 'declared_contract';
    case DeclaredContractAndReleaseIntegrity = 'declared_contract_and_release_integrity';
}
