<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class OntologyContextRelation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $columnCount,
        /** @var array<\Rafflesia\Resource\OntologyContextColumn>|null */
        public ?array $columns,
        public string $description,
        public string $domain,
        public string $entityType,
        public string $grain,
        public string $id,
        public bool $isColumnsTruncated,
        public bool $isRequiredColumnsTruncated,
        public string $name,
        public string $object,
        /** @var array<string>|null */
        public ?array $primaryKey,
        public int $requiredColumnCount,
        /** @var array<string>|null */
        public ?array $aliases = null,
        /** @var array<string>|null */
        public ?array $defaultOrder = null,
        /** @var array<\Rafflesia\Resource\OntologyEvidenceRelationshipContractData>|null */
        public ?array $evidenceRelationshipContracts = null,
        /** @var array<string>|null */
        public ?array $matchedFields = null,
        public ?int $matchedTermCount = null,
        /** @var array<string>|null */
        public ?array $matchedTerms = null,
        /** @var array<string>|null */
        public ?array $omittedRequiredColumns = null,
        /** @var array<string>|null */
        public ?array $qualityNotes = null,
        /** @var array<string>|null */
        public ?array $recommendedFilters = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'column_count',
            'columns',
            'description',
            'domain',
            'entity_type',
            'grain',
            'id',
            'is_columns_truncated',
            'is_required_columns_truncated',
            'name',
            'object',
            'primary_key',
            'required_column_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for OntologyContextRelation::fromArray()");
            }
        }
        return new self(
            columnCount: $data['column_count'],
            columns: isset($data['columns']) ? array_map(fn ($item) => OntologyContextColumn::fromArray($item), $data['columns']) : null,
            description: $data['description'],
            domain: $data['domain'],
            entityType: $data['entity_type'],
            grain: $data['grain'],
            id: $data['id'],
            isColumnsTruncated: $data['is_columns_truncated'],
            isRequiredColumnsTruncated: $data['is_required_columns_truncated'],
            name: $data['name'],
            object: $data['object'],
            primaryKey: $data['primary_key'] ?? null,
            requiredColumnCount: $data['required_column_count'],
            aliases: $data['aliases'] ?? null,
            defaultOrder: $data['default_order'] ?? null,
            evidenceRelationshipContracts: isset($data['evidence_relationship_contracts']) ? array_map(fn ($item) => OntologyEvidenceRelationshipContractData::fromArray($item), $data['evidence_relationship_contracts']) : null,
            matchedFields: $data['matched_fields'] ?? null,
            matchedTermCount: $data['matched_term_count'] ?? null,
            matchedTerms: $data['matched_terms'] ?? null,
            omittedRequiredColumns: $data['omitted_required_columns'] ?? null,
            qualityNotes: $data['quality_notes'] ?? null,
            recommendedFilters: $data['recommended_filters'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'column_count' => $this->columnCount,
            'columns' => $this->columns !== null ? array_map(fn ($item) => $item->toArray(), $this->columns) : null,
            'description' => $this->description,
            'domain' => $this->domain,
            'entity_type' => $this->entityType,
            'grain' => $this->grain,
            'id' => $this->id,
            'is_columns_truncated' => $this->isColumnsTruncated,
            'is_required_columns_truncated' => $this->isRequiredColumnsTruncated,
            'name' => $this->name,
            'object' => $this->object,
            'primary_key' => $this->primaryKey,
            'required_column_count' => $this->requiredColumnCount,
            'aliases' => $this->aliases,
            'default_order' => $this->defaultOrder,
            'evidence_relationship_contracts' => $this->evidenceRelationshipContracts !== null ? array_map(fn ($item) => $item->toArray(), $this->evidenceRelationshipContracts) : null,
            'matched_fields' => $this->matchedFields,
            'matched_term_count' => $this->matchedTermCount,
            'matched_terms' => $this->matchedTerms,
            'omitted_required_columns' => $this->omittedRequiredColumns,
            'quality_notes' => $this->qualityNotes,
            'recommended_filters' => $this->recommendedFilters,
        ];
    }
}
