<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class PasswordResetStartData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $email,
        public ?string $passwordResetUrl = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'email',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for PasswordResetStartData::fromArray()");
            }
        }
        return new self(
            email: $data['email'],
            passwordResetUrl: $data['password_reset_url'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'password_reset_url' => $this->passwordResetUrl,
        ];
    }
}
