<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum PocketLigandDistancesRequestTopNReference: string
{
    case LigandInstance = 'ligand_instance';
    case LigandGroup = 'ligand_group';
}
