<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class ProteinFoldCandidateSearchRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Structure candidate namespace to search. */
        public string $namespace,
        /** Structural token k-mer size; defaults to the build/query family default. */
        public ?int $kmerSize = null,
        /** Maximum number of hits returned; defaults to 10. */
        public ?int $maxHits = null,
        /** Optional hard budget checked against observed object bytes. */
        public ?int $maxObjectBytes = null,
        /** Optional hard budget checked against observed object reads. */
        public ?int $maxObjectReads = null,
        /** Candidate threshold on shared structural tokens; defaults to 1. */
        public ?int $minSharedTokens = null,
        /** Object id containing one query structure record. */
        public ?string $queryObjectId = null,
        /** JSON file containing one query structure record. */
        public ?string $queryPath = null,
        /** Inline query structure record. */
        public ?ProteinFoldCandidateRecord $queryStructure = null,
        /** Require the object-native path to materialize zero local database bytes. */
        public ?bool $requireZeroMaterialization = null,
        /** Hard deadline for this search in milliseconds; defaults to the structure candidate search timeout. */
        public ?int $timeoutMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'namespace',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for ProteinFoldCandidateSearchRequest::fromArray()");
            }
        }
        return new self(
            namespace: $data['namespace'],
            kmerSize: $data['kmer_size'] ?? null,
            maxHits: $data['max_hits'] ?? null,
            maxObjectBytes: $data['max_object_bytes'] ?? null,
            maxObjectReads: $data['max_object_reads'] ?? null,
            minSharedTokens: $data['min_shared_tokens'] ?? null,
            queryObjectId: $data['query_object_id'] ?? null,
            queryPath: $data['query_path'] ?? null,
            queryStructure: isset($data['query_structure']) ? ProteinFoldCandidateRecord::fromArray($data['query_structure']) : null,
            requireZeroMaterialization: $data['require_zero_materialization'] ?? null,
            timeoutMs: $data['timeout_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'namespace' => $this->namespace,
            'kmer_size' => $this->kmerSize,
            'max_hits' => $this->maxHits,
            'max_object_bytes' => $this->maxObjectBytes,
            'max_object_reads' => $this->maxObjectReads,
            'min_shared_tokens' => $this->minSharedTokens,
            'query_object_id' => $this->queryObjectId,
            'query_path' => $this->queryPath,
            'query_structure' => $this->queryStructure?->toArray(),
            'require_zero_materialization' => $this->requireZeroMaterialization,
            'timeout_ms' => $this->timeoutMs,
        ];
    }
}
