<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum QueryMeasurementsObjectReadMeasurementKind: string
{
    case BackendReported = 'backend_reported';
    case ServerObserved = 'server_observed';
    case NotMeasured = 'not_measured';
    case NotApplicable = 'not_applicable';
}
