<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum QueryRequestBudgetProfile: string
{
    case Interactive = 'interactive';
    case Batch = 'batch';
}
