<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RegistryEvidenceSet implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string>|null */
        public ?array $artifactIds,
        /** @var array<string>|null */
        public ?array $derivedFrom,
        public string $id,
        public string $kind,
        public string $origin,
        public string $representation,
        public ?int $availableRecords = null,
        public ?float $coverageFraction = null,
        public ?int $eligibleRecords = null,
        public ?string $modelReleaseId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'artifact_ids',
            'derived_from',
            'id',
            'kind',
            'origin',
            'representation',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RegistryEvidenceSet::fromArray()");
            }
        }
        return new self(
            artifactIds: $data['artifact_ids'] ?? null,
            derivedFrom: $data['derived_from'] ?? null,
            id: $data['id'],
            kind: $data['kind'],
            origin: $data['origin'],
            representation: $data['representation'],
            availableRecords: $data['available_records'] ?? null,
            coverageFraction: $data['coverage_fraction'] ?? null,
            eligibleRecords: $data['eligible_records'] ?? null,
            modelReleaseId: $data['model_release_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'artifact_ids' => $this->artifactIds,
            'derived_from' => $this->derivedFrom,
            'id' => $this->id,
            'kind' => $this->kind,
            'origin' => $this->origin,
            'representation' => $this->representation,
            'available_records' => $this->availableRecords,
            'coverage_fraction' => $this->coverageFraction,
            'eligible_records' => $this->eligibleRecords,
            'model_release_id' => $this->modelReleaseId,
        ];
    }
}
