<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RegionSplitData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $method,
        /** @var array<\Rafflesia\Resource\Region>|null */
        public ?array $regions,
        public string $structureId,
        public float $threshold,
        public ?RegionSplitAlgorithm $algorithm = null,
        public ?string $confidenceMetric = null,
        /** Immutable relation artifact emitted when output_relation is requested */
        public ?RelationArtifactData $relation = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'method',
            'regions',
            'structure_id',
            'threshold',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RegionSplitData::fromArray()");
            }
        }
        return new self(
            method: $data['method'],
            regions: isset($data['regions']) ? array_map(fn ($item) => Region::fromArray($item), $data['regions']) : null,
            structureId: $data['structure_id'],
            threshold: $data['threshold'],
            algorithm: isset($data['algorithm']) ? RegionSplitAlgorithm::fromArray($data['algorithm']) : null,
            confidenceMetric: $data['confidence_metric'] ?? null,
            relation: isset($data['relation']) ? RelationArtifactData::fromArray($data['relation']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'method' => $this->method,
            'regions' => $this->regions !== null ? array_map(fn ($item) => $item->toArray(), $this->regions) : null,
            'structure_id' => $this->structureId,
            'threshold' => $this->threshold,
            'algorithm' => $this->algorithm?->toArray(),
            'confidence_metric' => $this->confidenceMetric,
            'relation' => $this->relation?->toArray(),
        ];
    }
}
