<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RelationCapabilities implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $canAggregate,
        public bool $canFilter,
        public bool $canJoin,
        public bool $canProject,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'can_aggregate',
            'can_filter',
            'can_join',
            'can_project',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RelationCapabilities::fromArray()");
            }
        }
        return new self(
            canAggregate: $data['can_aggregate'],
            canFilter: $data['can_filter'],
            canJoin: $data['can_join'],
            canProject: $data['can_project'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'can_aggregate' => $this->canAggregate,
            'can_filter' => $this->canFilter,
            'can_join' => $this->canJoin,
            'can_project' => $this->canProject,
        ];
    }
}
