<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RelationKey implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string>|null */
        public ?array $columns,
        public ?string $namespace = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'columns',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RelationKey::fromArray()");
            }
        }
        return new self(
            columns: $data['columns'] ?? null,
            namespace: $data['namespace'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'columns' => $this->columns,
            'namespace' => $this->namespace,
        ];
    }
}
