<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RelationReleasePublicationDataJoinCertificationState: string
{
    case Queued = 'queued';
    case Reused = 'reused';
    case Completed = 'completed';
    case NotConfigured = 'not_configured';
    case NotRequestedDryRun = 'not_requested_dry_run';
    case EnqueueFailed = 'enqueue_failed';
    case ExecutionFailed = 'execution_failed';
}
