<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RelationReleasesSchemaStatus: string
{
    case Current = 'current';
    case Outdated = 'outdated';
    case All = 'all';
}
