<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RelationReleaseOntologyRelation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public RelationReleaseOntologyRelationConnectivityClass $connectivityClass,
        public int $directIdentitySafeReleaseEdgeCount,
        public int $directStrictReleaseEdgeCount,
        public string $identitySafeComponentId,
        /** Relation count in the complete ontology component, including relations absent from this release. */
        public int $identitySafeComponentSize,
        public int $identitySafeReachableReleaseRelationCount,
        public int $inferredIdentitySafeReleaseRelationCount,
        public int $inferredStrictReleaseRelationCount,
        public string $relation,
        public string $strictComponentId,
        /** Relation count in the complete strict ontology component, including relations absent from this release. */
        public int $strictComponentSize,
        public int $strictReachableReleaseRelationCount,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'connectivity_class',
            'direct_identity_safe_release_edge_count',
            'direct_strict_release_edge_count',
            'identity_safe_component_id',
            'identity_safe_component_size',
            'identity_safe_reachable_release_relation_count',
            'inferred_identity_safe_release_relation_count',
            'inferred_strict_release_relation_count',
            'relation',
            'strict_component_id',
            'strict_component_size',
            'strict_reachable_release_relation_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RelationReleaseOntologyRelation::fromArray()");
            }
        }
        return new self(
            connectivityClass: RelationReleaseOntologyRelationConnectivityClass::from($data['connectivity_class']),
            directIdentitySafeReleaseEdgeCount: $data['direct_identity_safe_release_edge_count'],
            directStrictReleaseEdgeCount: $data['direct_strict_release_edge_count'],
            identitySafeComponentId: $data['identity_safe_component_id'],
            identitySafeComponentSize: $data['identity_safe_component_size'],
            identitySafeReachableReleaseRelationCount: $data['identity_safe_reachable_release_relation_count'],
            inferredIdentitySafeReleaseRelationCount: $data['inferred_identity_safe_release_relation_count'],
            inferredStrictReleaseRelationCount: $data['inferred_strict_release_relation_count'],
            relation: $data['relation'],
            strictComponentId: $data['strict_component_id'],
            strictComponentSize: $data['strict_component_size'],
            strictReachableReleaseRelationCount: $data['strict_reachable_release_relation_count'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'connectivity_class' => $this->connectivityClass->value,
            'direct_identity_safe_release_edge_count' => $this->directIdentitySafeReleaseEdgeCount,
            'direct_strict_release_edge_count' => $this->directStrictReleaseEdgeCount,
            'identity_safe_component_id' => $this->identitySafeComponentId,
            'identity_safe_component_size' => $this->identitySafeComponentSize,
            'identity_safe_reachable_release_relation_count' => $this->identitySafeReachableReleaseRelationCount,
            'inferred_identity_safe_release_relation_count' => $this->inferredIdentitySafeReleaseRelationCount,
            'inferred_strict_release_relation_count' => $this->inferredStrictReleaseRelationCount,
            'relation' => $this->relation,
            'strict_component_id' => $this->strictComponentId,
            'strict_component_size' => $this->strictComponentSize,
            'strict_reachable_release_relation_count' => $this->strictReachableReleaseRelationCount,
        ];
    }
}
