<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RepositoryRef implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $fullName,
        public string $id,
        public RepositoriesKind $kind,
        public string $namespace,
        public string $slug,
        public string $object = 'repository',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'full_name',
            'id',
            'kind',
            'namespace',
            'slug',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RepositoryRef::fromArray()");
            }
        }
        return new self(
            fullName: $data['full_name'],
            id: $data['id'],
            kind: RepositoriesKind::from($data['kind']),
            namespace: $data['namespace'],
            slug: $data['slug'],
            object: $data['object'] ?? 'repository',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'full_name' => $this->fullName,
            'id' => $this->id,
            'kind' => $this->kind->value,
            'namespace' => $this->namespace,
            'slug' => $this->slug,
            'object' => $this->object,
        ];
    }
}
