<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RepositorySummary implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\ReleaseAlias>|null */
        public ?array $aliases,
        public int $buildCount,
        /** @var array<string>|null */
        public ?array $capabilities,
        public string $description,
        public string $displayName,
        public int $releaseCount,
        public RepositoryRef $repository,
        public RegistryScope $scope,
        public string $visibility,
        public ?ReleaseRef $latestRelease = null,
        public ?string $license = null,
        public ?string $sourceUrl = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'aliases',
            'build_count',
            'capabilities',
            'description',
            'display_name',
            'release_count',
            'repository',
            'scope',
            'visibility',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RepositorySummary::fromArray()");
            }
        }
        return new self(
            aliases: isset($data['aliases']) ? array_map(fn ($item) => ReleaseAlias::fromArray($item), $data['aliases']) : null,
            buildCount: $data['build_count'],
            capabilities: $data['capabilities'] ?? null,
            description: $data['description'],
            displayName: $data['display_name'],
            releaseCount: $data['release_count'],
            repository: RepositoryRef::fromArray($data['repository']),
            scope: RegistryScope::fromArray($data['scope']),
            visibility: $data['visibility'],
            latestRelease: isset($data['latest_release']) ? ReleaseRef::fromArray($data['latest_release']) : null,
            license: $data['license'] ?? null,
            sourceUrl: $data['source_url'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'aliases' => $this->aliases !== null ? array_map(fn ($item) => $item->toArray(), $this->aliases) : null,
            'build_count' => $this->buildCount,
            'capabilities' => $this->capabilities,
            'description' => $this->description,
            'display_name' => $this->displayName,
            'release_count' => $this->releaseCount,
            'repository' => $this->repository->toArray(),
            'scope' => $this->scope->toArray(),
            'visibility' => $this->visibility,
            'latest_release' => $this->latestRelease?->toArray(),
            'license' => $this->license,
            'source_url' => $this->sourceUrl,
        ];
    }
}
