<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum Requirements: string
{
    case NotRequested = 'not_requested';
    case IfAvailable = 'if_available';
    case Required = 'required';
}
