<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlCompilerExplanation implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\RqlCallerFilterExpansion>|null */
        public ?array $callerFilterExpansions,
        public string $explanationDigest,
        /** @var array<\Rafflesia\Resource\RqlGrainProof>|null */
        public ?array $grainProofs,
        public string $id,
        /** @var array<\Rafflesia\Resource\RqlJoinDecision>|null */
        public ?array $joinDecisions,
        public SemanticQueryRequest $normalizedAst,
        public string $normalizedAstDigest,
        /** @var array<\Rafflesia\Resource\RqlResolvedOntologyEdge>|null */
        public ?array $resolvedOntologyEdges,
        /** @var array<\Rafflesia\Resource\RqlResolvedEvidenceRelationship>|null */
        public ?array $evidenceRelationships = null,
        public string $object = 'rql_compiler_explanation',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'caller_filter_expansions',
            'explanation_digest',
            'grain_proofs',
            'id',
            'join_decisions',
            'normalized_ast',
            'normalized_ast_digest',
            'resolved_ontology_edges',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlCompilerExplanation::fromArray()");
            }
        }
        return new self(
            callerFilterExpansions: isset($data['caller_filter_expansions']) ? array_map(fn ($item) => RqlCallerFilterExpansion::fromArray($item), $data['caller_filter_expansions']) : null,
            explanationDigest: $data['explanation_digest'],
            grainProofs: isset($data['grain_proofs']) ? array_map(fn ($item) => RqlGrainProof::fromArray($item), $data['grain_proofs']) : null,
            id: $data['id'],
            joinDecisions: isset($data['join_decisions']) ? array_map(fn ($item) => RqlJoinDecision::fromArray($item), $data['join_decisions']) : null,
            normalizedAst: SemanticQueryRequest::fromArray($data['normalized_ast']),
            normalizedAstDigest: $data['normalized_ast_digest'],
            resolvedOntologyEdges: isset($data['resolved_ontology_edges']) ? array_map(fn ($item) => RqlResolvedOntologyEdge::fromArray($item), $data['resolved_ontology_edges']) : null,
            evidenceRelationships: isset($data['evidence_relationships']) ? array_map(fn ($item) => RqlResolvedEvidenceRelationship::fromArray($item), $data['evidence_relationships']) : null,
            object: $data['object'] ?? 'rql_compiler_explanation',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'caller_filter_expansions' => $this->callerFilterExpansions !== null ? array_map(fn ($item) => $item->toArray(), $this->callerFilterExpansions) : null,
            'explanation_digest' => $this->explanationDigest,
            'grain_proofs' => $this->grainProofs !== null ? array_map(fn ($item) => $item->toArray(), $this->grainProofs) : null,
            'id' => $this->id,
            'join_decisions' => $this->joinDecisions !== null ? array_map(fn ($item) => $item->toArray(), $this->joinDecisions) : null,
            'normalized_ast' => $this->normalizedAst->toArray(),
            'normalized_ast_digest' => $this->normalizedAstDigest,
            'resolved_ontology_edges' => $this->resolvedOntologyEdges !== null ? array_map(fn ($item) => $item->toArray(), $this->resolvedOntologyEdges) : null,
            'evidence_relationships' => $this->evidenceRelationships !== null ? array_map(fn ($item) => $item->toArray(), $this->evidenceRelationships) : null,
            'object' => $this->object,
        ];
    }
}
