<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RqlEvidenceProfileComparisonSetOperationOperator: string
{
    case Base = 'base';
    case UnionAll = 'union_all';
    case Intersect = 'intersect';
    case Except = 'except';
}
