<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlEvidenceProfileRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $name,
        /** @var array<\Rafflesia\Resource\RqlEvidenceProfileOverrideRequest>|null */
        public ?array $overrides,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'name',
            'overrides',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlEvidenceProfileRequest::fromArray()");
            }
        }
        return new self(
            name: $data['name'],
            overrides: isset($data['overrides']) ? array_map(fn ($item) => RqlEvidenceProfileOverrideRequest::fromArray($item), $data['overrides']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'overrides' => $this->overrides !== null ? array_map(fn ($item) => $item->toArray(), $this->overrides) : null,
        ];
    }
}
