<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlEvidenceRelationshipScopeDefinition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public OntologyEvidenceScopeContractDataKind $kind,
        public ?RqlMeasurementFieldDefinition $alignment = null,
        public ?RqlMeasurementFieldDefinition $objectDomainInstance = null,
        public ?RqlMeasurementFieldDefinition $objectEnd = null,
        public ?RqlMeasurementFieldDefinition $objectStart = null,
        public ?RqlMeasurementFieldDefinition $subjectDomainInstance = null,
        public ?RqlMeasurementFieldDefinition $subjectEnd = null,
        public ?RqlMeasurementFieldDefinition $subjectStart = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'kind',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlEvidenceRelationshipScopeDefinition::fromArray()");
            }
        }
        return new self(
            kind: OntologyEvidenceScopeContractDataKind::from($data['kind']),
            alignment: isset($data['alignment']) ? RqlMeasurementFieldDefinition::fromArray($data['alignment']) : null,
            objectDomainInstance: isset($data['object_domain_instance']) ? RqlMeasurementFieldDefinition::fromArray($data['object_domain_instance']) : null,
            objectEnd: isset($data['object_end']) ? RqlMeasurementFieldDefinition::fromArray($data['object_end']) : null,
            objectStart: isset($data['object_start']) ? RqlMeasurementFieldDefinition::fromArray($data['object_start']) : null,
            subjectDomainInstance: isset($data['subject_domain_instance']) ? RqlMeasurementFieldDefinition::fromArray($data['subject_domain_instance']) : null,
            subjectEnd: isset($data['subject_end']) ? RqlMeasurementFieldDefinition::fromArray($data['subject_end']) : null,
            subjectStart: isset($data['subject_start']) ? RqlMeasurementFieldDefinition::fromArray($data['subject_start']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind->value,
            'alignment' => $this->alignment?->toArray(),
            'object_domain_instance' => $this->objectDomainInstance?->toArray(),
            'object_end' => $this->objectEnd?->toArray(),
            'object_start' => $this->objectStart?->toArray(),
            'subject_domain_instance' => $this->subjectDomainInstance?->toArray(),
            'subject_end' => $this->subjectEnd?->toArray(),
            'subject_start' => $this->subjectStart?->toArray(),
        ];
    }
}
