<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RqlEvidenceRelationshipComparisonComparabilityReason: string
{
    case TypedNamespaceAndScopeMatch = 'typed_namespace_and_scope_match';
    case IdenticalTypedColumns = 'identical_typed_columns';
    case ScopeKindMismatch = 'scope_kind_mismatch';
    case SubjectNamespaceUndeclared = 'subject_namespace_undeclared';
    case SubjectNamespaceMismatch = 'subject_namespace_mismatch';
    case ObjectNamespaceUndeclared = 'object_namespace_undeclared';
    case ObjectNamespaceMismatch = 'object_namespace_mismatch';
}
