<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlEvidenceRelationshipDefinition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $description,
        /** @var array<\Rafflesia\Resource\RqlMeasurementFieldDefinition>|null */
        public ?array $evidenceFields,
        public string $evidenceSource,
        public RqlLockedEvidenceRelationshipKind $kind,
        public RqlMeasurementFieldDefinition $method,
        public RqlLockedEvidenceRelationshipMissingEvidencePolicy $missingEvidencePolicy,
        public string $name,
        public RqlMeasurementFieldDefinition $object,
        public OntologyEvidenceRelationshipContractData $ontologyContract,
        public RqlEvidenceRelationshipScopeDefinition $scope,
        public RqlLockedEvidenceRelationshipStatus $status,
        public RqlMeasurementFieldDefinition $subject,
        /** @var array<\Rafflesia\Resource\RqlFilterDefinition>|null */
        public ?array $criteria = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'description',
            'evidence_fields',
            'evidence_source',
            'kind',
            'method',
            'missing_evidence_policy',
            'name',
            'object',
            'ontology_contract',
            'scope',
            'status',
            'subject',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlEvidenceRelationshipDefinition::fromArray()");
            }
        }
        return new self(
            description: $data['description'],
            evidenceFields: isset($data['evidence_fields']) ? array_map(fn ($item) => RqlMeasurementFieldDefinition::fromArray($item), $data['evidence_fields']) : null,
            evidenceSource: $data['evidence_source'],
            kind: RqlLockedEvidenceRelationshipKind::from($data['kind']),
            method: RqlMeasurementFieldDefinition::fromArray($data['method']),
            missingEvidencePolicy: RqlLockedEvidenceRelationshipMissingEvidencePolicy::from($data['missing_evidence_policy']),
            name: $data['name'],
            object: RqlMeasurementFieldDefinition::fromArray($data['object']),
            ontologyContract: OntologyEvidenceRelationshipContractData::fromArray($data['ontology_contract']),
            scope: RqlEvidenceRelationshipScopeDefinition::fromArray($data['scope']),
            status: RqlLockedEvidenceRelationshipStatus::from($data['status']),
            subject: RqlMeasurementFieldDefinition::fromArray($data['subject']),
            criteria: isset($data['criteria']) ? array_map(fn ($item) => RqlFilterDefinition::fromArray($item), $data['criteria']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'description' => $this->description,
            'evidence_fields' => $this->evidenceFields !== null ? array_map(fn ($item) => $item->toArray(), $this->evidenceFields) : null,
            'evidence_source' => $this->evidenceSource,
            'kind' => $this->kind->value,
            'method' => $this->method->toArray(),
            'missing_evidence_policy' => $this->missingEvidencePolicy->value,
            'name' => $this->name,
            'object' => $this->object->toArray(),
            'ontology_contract' => $this->ontologyContract->toArray(),
            'scope' => $this->scope->toArray(),
            'status' => $this->status->value,
            'subject' => $this->subject->toArray(),
            'criteria' => $this->criteria !== null ? array_map(fn ($item) => $item->toArray(), $this->criteria) : null,
        ];
    }
}
