<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlGrainProof implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $measurement,
        public RqlGrainProofProtection $protection,
        /** @var array<string>|null */
        public ?array $fanoutJoinIds = null,
        /** @var array<string>|null */
        public ?array $inputGrain = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'measurement',
            'protection',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlGrainProof::fromArray()");
            }
        }
        return new self(
            measurement: $data['measurement'],
            protection: RqlGrainProofProtection::from($data['protection']),
            fanoutJoinIds: $data['fanout_join_ids'] ?? null,
            inputGrain: $data['input_grain'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'measurement' => $this->measurement,
            'protection' => $this->protection->value,
            'fanout_join_ids' => $this->fanoutJoinIds,
            'input_grain' => $this->inputGrain,
        ];
    }
}
