<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RqlJoinDecisionReason: string
{
    case Always = 'always';
    case ReferencedByQuery = 'referenced_by_query';
    case RequiredByActiveDescendant = 'required_by_active_descendant';
    case UnreferencedSafeLeftToOne = 'unreferenced_safe_left_to_one';
}
