<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlMeasurementFieldDefinition implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $column,
        public string $source,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'column',
            'source',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlMeasurementFieldDefinition::fromArray()");
            }
        }
        return new self(
            column: $data['column'],
            source: $data['source'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'column' => $this->column,
            'source' => $this->source,
        ];
    }
}
