<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RqlOutputContractCompatibility implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $actualDigest,
        /** @var array<\Rafflesia\Resource\RqlOutputContractChange>|null */
        public ?array $changes,
        public bool $isCompatible,
        public RqlOutputContractCompatibilityStatus $status,
        public ?string $expectedDigest = null,
        public string $object = 'rql_output_contract_compatibility',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'actual_digest',
            'changes',
            'is_compatible',
            'status',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RqlOutputContractCompatibility::fromArray()");
            }
        }
        return new self(
            actualDigest: $data['actual_digest'],
            changes: isset($data['changes']) ? array_map(fn ($item) => RqlOutputContractChange::fromArray($item), $data['changes']) : null,
            isCompatible: $data['is_compatible'],
            status: RqlOutputContractCompatibilityStatus::from($data['status']),
            expectedDigest: $data['expected_digest'] ?? null,
            object: $data['object'] ?? 'rql_output_contract_compatibility',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'actual_digest' => $this->actualDigest,
            'changes' => $this->changes !== null ? array_map(fn ($item) => $item->toArray(), $this->changes) : null,
            'is_compatible' => $this->isCompatible,
            'status' => $this->status->value,
            'expected_digest' => $this->expectedDigest,
            'object' => $this->object,
        ];
    }
}
