<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointRafflesiaEsmFinetuneOutputEndpointExample implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $background,
        /** @var array<string, mixed> */
        public array $input,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'background',
            'input',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointRafflesiaEsmFinetuneOutputEndpointExample::fromArray()");
            }
        }
        return new self(
            background: $data['background'],
            input: $data['input'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'background' => $this->background,
            'input' => $this->input,
        ];
    }
}
