<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointGoogleDeepmindAlphafold2MonomerOutput implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Provider artifact name to ordinary URL.
         * @var array<string, string>
         */
        public array $artifactUrls,
        public string $model,
        public string $predictionId,
        public string $structureUrl,
        public RunEndpointGoogleDeepmindAlphafold2MonomerOutputRunUsage $usage,
        public ?RunEndpointGoogleDeepmindAlphafold2MonomerOutputStructureRunInferenceMsa $inferenceMsa = null,
        public ?string $manifestUrl = null,
        /** @var array<string, float>|null */
        public ?array $metrics = null,
        public ?RunEndpointGoogleDeepmindAlphafold2MonomerOutputStructureRunMsa $msa = null,
        public ?string $msaProfile = null,
        public ?string $pipelineManifestUrl = null,
        public ?string $pipelineReleaseId = null,
        public ?RunEndpointGoogleDeepmindAlphafold2MonomerOutputStructurePredictionServingMeasurements $serving = null,
        /** @var array<string, int>|null */
        public ?array $timingsMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'artifact_urls',
            'model',
            'prediction_id',
            'structure_url',
            'usage',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointGoogleDeepmindAlphafold2MonomerOutput::fromArray()");
            }
        }
        return new self(
            artifactUrls: $data['artifact_urls'],
            model: $data['model'],
            predictionId: $data['prediction_id'],
            structureUrl: $data['structure_url'],
            usage: RunEndpointGoogleDeepmindAlphafold2MonomerOutputRunUsage::fromArray($data['usage']),
            inferenceMsa: isset($data['inference_msa']) ? RunEndpointGoogleDeepmindAlphafold2MonomerOutputStructureRunInferenceMsa::fromArray($data['inference_msa']) : null,
            manifestUrl: $data['manifest_url'] ?? null,
            metrics: $data['metrics'] ?? null,
            msa: isset($data['msa']) ? RunEndpointGoogleDeepmindAlphafold2MonomerOutputStructureRunMsa::fromArray($data['msa']) : null,
            msaProfile: $data['msa_profile'] ?? null,
            pipelineManifestUrl: $data['pipeline_manifest_url'] ?? null,
            pipelineReleaseId: $data['pipeline_release_id'] ?? null,
            serving: isset($data['serving']) ? RunEndpointGoogleDeepmindAlphafold2MonomerOutputStructurePredictionServingMeasurements::fromArray($data['serving']) : null,
            timingsMs: $data['timings_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'artifact_urls' => $this->artifactUrls,
            'model' => $this->model,
            'prediction_id' => $this->predictionId,
            'structure_url' => $this->structureUrl,
            'usage' => $this->usage->toArray(),
            'inference_msa' => $this->inferenceMsa?->toArray(),
            'manifest_url' => $this->manifestUrl,
            'metrics' => $this->metrics,
            'msa' => $this->msa?->toArray(),
            'msa_profile' => $this->msaProfile,
            'pipeline_manifest_url' => $this->pipelineManifestUrl,
            'pipeline_release_id' => $this->pipelineReleaseId,
            'serving' => $this->serving?->toArray(),
            'timings_ms' => $this->timingsMs,
        ];
    }
}
