<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointRafflesiaMsaAf2InputAf2MsaDatabaseReleases implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Immutable combined BFD plus UniRef30 release used by the full AF2 pipeline. */
        public string $bfdUniref30,
        /** Immutable Tomato-backed MGnify release. */
        public string $mgnify,
        /** Immutable Tomato-backed UniRef90 release. */
        public string $uniref90,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'bfd_uniref30',
            'mgnify',
            'uniref90',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointRafflesiaMsaAf2InputAf2MsaDatabaseReleases::fromArray()");
            }
        }
        return new self(
            bfdUniref30: $data['bfd_uniref30'],
            mgnify: $data['mgnify'],
            uniref90: $data['uniref90'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'bfd_uniref30' => $this->bfdUniref30,
            'mgnify' => $this->mgnify,
            'uniref90' => $this->uniref90,
        ];
    }
}
