<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointInstituteForProteinDesignLigandmpnnV3201025OutputProteinDesignUsage implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $generatedSequenceCount,
        public int $residueCount,
        public int $structureCount,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'generated_sequence_count',
            'residue_count',
            'structure_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointInstituteForProteinDesignLigandmpnnV3201025OutputProteinDesignUsage::fromArray()");
            }
        }
        return new self(
            generatedSequenceCount: $data['generated_sequence_count'],
            residueCount: $data['residue_count'],
            structureCount: $data['structure_count'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'generated_sequence_count' => $this->generatedSequenceCount,
            'residue_count' => $this->residueCount,
            'structure_count' => $this->structureCount,
        ];
    }
}
