<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointRosettacommonsRosettafold3OutputStructureRunMsa implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $cacheKey,
        public bool $isCacheHit,
        /**
         * Alignment role to ordinary A3M URL.
         * @var array<string, string>
         */
        public array $laneUrls,
        public string $manifestUrl,
        public string $profile,
        public int $sequenceCount,
        public string $url,
        public ?RunEndpointRosettacommonsRosettafold3OutputMsaMeasurementLink $measurements = null,
        public ?string $pairedSourceUrl = null,
        public ?string $rowIdentitiesUrl = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'cache_key',
            'is_cache_hit',
            'lane_urls',
            'manifest_url',
            'profile',
            'sequence_count',
            'url',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointRosettacommonsRosettafold3OutputStructureRunMsa::fromArray()");
            }
        }
        return new self(
            cacheKey: $data['cache_key'],
            isCacheHit: $data['is_cache_hit'],
            laneUrls: $data['lane_urls'],
            manifestUrl: $data['manifest_url'],
            profile: $data['profile'],
            sequenceCount: $data['sequence_count'],
            url: $data['url'],
            measurements: isset($data['measurements']) ? RunEndpointRosettacommonsRosettafold3OutputMsaMeasurementLink::fromArray($data['measurements']) : null,
            pairedSourceUrl: $data['paired_source_url'] ?? null,
            rowIdentitiesUrl: $data['row_identities_url'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'cache_key' => $this->cacheKey,
            'is_cache_hit' => $this->isCacheHit,
            'lane_urls' => $this->laneUrls,
            'manifest_url' => $this->manifestUrl,
            'profile' => $this->profile,
            'sequence_count' => $this->sequenceCount,
            'url' => $this->url,
            'measurements' => $this->measurements?->toArray(),
            'paired_source_url' => $this->pairedSourceUrl,
            'row_identities_url' => $this->rowIdentitiesUrl,
        ];
    }
}
