<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointRafflesiaMsaColabfoldOutputMsaMeasurementSummary implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Rows removed because normalized target ids were repeated. */
        public int $collapsedDuplicateRows,
        public int $columnsAtLeast50PctOccupancy,
        public int $columnsAtLeast75PctOccupancy,
        public int $columnsAtLeast90PctOccupancy,
        /** Query columns occupied by no homolog row. */
        public int $columnsWithNoResidue,
        /** Sum of sequence weights over non-query homolog rows. */
        public float $homologNeff,
        /** Number of non-query homolog rows after optional target-id collapse. */
        public int $homologRowCount,
        public float $identityThreshold,
        public float $insertionRowFraction,
        public bool $isDuplicateTargetCollapsed,
        public bool $isNeffExact,
        /** True when pairwise comparable/similar/identity diagnostics are estimates from deterministic samples. */
        public bool $isPairwiseDiagnosticsEstimated,
        public bool $isQueryIncludedInNeff,
        /** Mean Shannon entropy of non-gap homolog residues, in bits. */
        public float $meanColumnEntropyBits,
        /** Mean residue occupancy over homolog rows and query columns; excludes the query row. */
        public float $meanColumnOccupancy,
        /** Mean ungapped identity to the query over homolog rows. */
        public float $meanIdentityToQuery,
        /** Mean occupied-query-column fraction over homolog rows; excludes the query. */
        public float $meanRowCoverage,
        public float $medianColumnOccupancy,
        public float $medianIdentityToQuery,
        public float $medianRowCoverage,
        public float $minimumOverlapFraction,
        /** Sum of inverse-neighborhood sequence weights, including the query. Consult is_neff_exact and neff_standard_error. */
        public float $neff,
        public RunEndpointRafflesiaMsaOutputMsaMeasurementSummaryNeffMethod $neffMethod,
        /** Neff divided by query length. */
        public float $neffPerColumn,
        /** Neff divided by total sequence count; lower values indicate more redundancy. */
        public float $neffSequenceRatio,
        /** Delta-method estimated standard error for sampled Neff; zero for exact Neff. */
        public float $neffStandardError,
        /** Query-boundary insertion slots occupied by at least one homolog. */
        public int $occupiedInsertionSlots,
        public float $p10ColumnOccupancy,
        public float $p10IdentityToQuery,
        public float $p10RowCoverage,
        public float $p90ColumnOccupancy,
        public float $p90IdentityToQuery,
        public float $p90RowCoverage,
        /** Number of directed row-partner samples evaluated by the sampled method; zero for exact weighting. */
        public int $pairSampleCount,
        /** Fraction of all directed row pairs evaluated by the sampled method; zero for exact weighting. */
        public float $pairSamplingFraction,
        /** Pairs meeting the minimum overlap threshold and sharing at least one residue. */
        public int $pairwiseComparablePairs,
        /** All unordered MSA row pairs, including pairs involving the query. */
        public int $pairwiseComparisons,
        /** Mean jointly occupied query-column fraction over comparable pairs. */
        public float $pairwiseMeanOverlapFraction,
        /** Identical jointly occupied residues divided by all jointly occupied residues over comparable pairs. */
        public float $pairwisePooledIdentity,
        /** Comparable pairs meeting the identity threshold. */
        public int $pairwiseSimilarPairs,
        public float $pairwiseSimilarityFraction,
        /** Number of query-anchored match columns. */
        public int $queryLength,
        /** Rows represented by an already-seen aligned state during exact weighting. */
        public int $redundantAlignedSequenceRows,
        public int $rowsWithInsertions,
        /** Seed used by deterministic sampling; zero when exact weighting was used. */
        public int $samplingSeed,
        /** Total MSA depth including the query row. */
        public int $sequenceCount,
        public int $totalInsertionResidues,
        /** Distinct query-column state strings including the query. */
        public int $uniqueAlignedSequences,
        /** Distinct normalized non-query target identifiers. */
        public int $uniqueTargetIds,
        /** Mean Shannon entropy after exact sequence reweighting, in bits. */
        public float $weightedMeanColumnEntropyBits,
        /** Mean column occupancy weighted by the selected sequence weights; excludes the query. */
        public float $weightedMeanColumnOccupancy,
        /** Unique aligned-state comparisons actually evaluated after exact duplicate-state grouping. */
        public int $weightingKernelComparisons,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'collapsed_duplicate_rows',
            'columns_at_least_50_pct_occupancy',
            'columns_at_least_75_pct_occupancy',
            'columns_at_least_90_pct_occupancy',
            'columns_with_no_residue',
            'homolog_neff',
            'homolog_row_count',
            'identity_threshold',
            'insertion_row_fraction',
            'is_duplicate_target_collapsed',
            'is_neff_exact',
            'is_pairwise_diagnostics_estimated',
            'is_query_included_in_neff',
            'mean_column_entropy_bits',
            'mean_column_occupancy',
            'mean_identity_to_query',
            'mean_row_coverage',
            'median_column_occupancy',
            'median_identity_to_query',
            'median_row_coverage',
            'minimum_overlap_fraction',
            'neff',
            'neff_method',
            'neff_per_column',
            'neff_sequence_ratio',
            'neff_standard_error',
            'occupied_insertion_slots',
            'p10_column_occupancy',
            'p10_identity_to_query',
            'p10_row_coverage',
            'p90_column_occupancy',
            'p90_identity_to_query',
            'p90_row_coverage',
            'pair_sample_count',
            'pair_sampling_fraction',
            'pairwise_comparable_pairs',
            'pairwise_comparisons',
            'pairwise_mean_overlap_fraction',
            'pairwise_pooled_identity',
            'pairwise_similar_pairs',
            'pairwise_similarity_fraction',
            'query_length',
            'redundant_aligned_sequence_rows',
            'rows_with_insertions',
            'sampling_seed',
            'sequence_count',
            'total_insertion_residues',
            'unique_aligned_sequences',
            'unique_target_ids',
            'weighted_mean_column_entropy_bits',
            'weighted_mean_column_occupancy',
            'weighting_kernel_comparisons',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointRafflesiaMsaColabfoldOutputMsaMeasurementSummary::fromArray()");
            }
        }
        return new self(
            collapsedDuplicateRows: $data['collapsed_duplicate_rows'],
            columnsAtLeast50PctOccupancy: $data['columns_at_least_50_pct_occupancy'],
            columnsAtLeast75PctOccupancy: $data['columns_at_least_75_pct_occupancy'],
            columnsAtLeast90PctOccupancy: $data['columns_at_least_90_pct_occupancy'],
            columnsWithNoResidue: $data['columns_with_no_residue'],
            homologNeff: $data['homolog_neff'],
            homologRowCount: $data['homolog_row_count'],
            identityThreshold: $data['identity_threshold'],
            insertionRowFraction: $data['insertion_row_fraction'],
            isDuplicateTargetCollapsed: $data['is_duplicate_target_collapsed'],
            isNeffExact: $data['is_neff_exact'],
            isPairwiseDiagnosticsEstimated: $data['is_pairwise_diagnostics_estimated'],
            isQueryIncludedInNeff: $data['is_query_included_in_neff'],
            meanColumnEntropyBits: $data['mean_column_entropy_bits'],
            meanColumnOccupancy: $data['mean_column_occupancy'],
            meanIdentityToQuery: $data['mean_identity_to_query'],
            meanRowCoverage: $data['mean_row_coverage'],
            medianColumnOccupancy: $data['median_column_occupancy'],
            medianIdentityToQuery: $data['median_identity_to_query'],
            medianRowCoverage: $data['median_row_coverage'],
            minimumOverlapFraction: $data['minimum_overlap_fraction'],
            neff: $data['neff'],
            neffMethod: RunEndpointRafflesiaMsaOutputMsaMeasurementSummaryNeffMethod::from($data['neff_method']),
            neffPerColumn: $data['neff_per_column'],
            neffSequenceRatio: $data['neff_sequence_ratio'],
            neffStandardError: $data['neff_standard_error'],
            occupiedInsertionSlots: $data['occupied_insertion_slots'],
            p10ColumnOccupancy: $data['p10_column_occupancy'],
            p10IdentityToQuery: $data['p10_identity_to_query'],
            p10RowCoverage: $data['p10_row_coverage'],
            p90ColumnOccupancy: $data['p90_column_occupancy'],
            p90IdentityToQuery: $data['p90_identity_to_query'],
            p90RowCoverage: $data['p90_row_coverage'],
            pairSampleCount: $data['pair_sample_count'],
            pairSamplingFraction: $data['pair_sampling_fraction'],
            pairwiseComparablePairs: $data['pairwise_comparable_pairs'],
            pairwiseComparisons: $data['pairwise_comparisons'],
            pairwiseMeanOverlapFraction: $data['pairwise_mean_overlap_fraction'],
            pairwisePooledIdentity: $data['pairwise_pooled_identity'],
            pairwiseSimilarPairs: $data['pairwise_similar_pairs'],
            pairwiseSimilarityFraction: $data['pairwise_similarity_fraction'],
            queryLength: $data['query_length'],
            redundantAlignedSequenceRows: $data['redundant_aligned_sequence_rows'],
            rowsWithInsertions: $data['rows_with_insertions'],
            samplingSeed: $data['sampling_seed'],
            sequenceCount: $data['sequence_count'],
            totalInsertionResidues: $data['total_insertion_residues'],
            uniqueAlignedSequences: $data['unique_aligned_sequences'],
            uniqueTargetIds: $data['unique_target_ids'],
            weightedMeanColumnEntropyBits: $data['weighted_mean_column_entropy_bits'],
            weightedMeanColumnOccupancy: $data['weighted_mean_column_occupancy'],
            weightingKernelComparisons: $data['weighting_kernel_comparisons'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'collapsed_duplicate_rows' => $this->collapsedDuplicateRows,
            'columns_at_least_50_pct_occupancy' => $this->columnsAtLeast50PctOccupancy,
            'columns_at_least_75_pct_occupancy' => $this->columnsAtLeast75PctOccupancy,
            'columns_at_least_90_pct_occupancy' => $this->columnsAtLeast90PctOccupancy,
            'columns_with_no_residue' => $this->columnsWithNoResidue,
            'homolog_neff' => $this->homologNeff,
            'homolog_row_count' => $this->homologRowCount,
            'identity_threshold' => $this->identityThreshold,
            'insertion_row_fraction' => $this->insertionRowFraction,
            'is_duplicate_target_collapsed' => $this->isDuplicateTargetCollapsed,
            'is_neff_exact' => $this->isNeffExact,
            'is_pairwise_diagnostics_estimated' => $this->isPairwiseDiagnosticsEstimated,
            'is_query_included_in_neff' => $this->isQueryIncludedInNeff,
            'mean_column_entropy_bits' => $this->meanColumnEntropyBits,
            'mean_column_occupancy' => $this->meanColumnOccupancy,
            'mean_identity_to_query' => $this->meanIdentityToQuery,
            'mean_row_coverage' => $this->meanRowCoverage,
            'median_column_occupancy' => $this->medianColumnOccupancy,
            'median_identity_to_query' => $this->medianIdentityToQuery,
            'median_row_coverage' => $this->medianRowCoverage,
            'minimum_overlap_fraction' => $this->minimumOverlapFraction,
            'neff' => $this->neff,
            'neff_method' => $this->neffMethod->value,
            'neff_per_column' => $this->neffPerColumn,
            'neff_sequence_ratio' => $this->neffSequenceRatio,
            'neff_standard_error' => $this->neffStandardError,
            'occupied_insertion_slots' => $this->occupiedInsertionSlots,
            'p10_column_occupancy' => $this->p10ColumnOccupancy,
            'p10_identity_to_query' => $this->p10IdentityToQuery,
            'p10_row_coverage' => $this->p10RowCoverage,
            'p90_column_occupancy' => $this->p90ColumnOccupancy,
            'p90_identity_to_query' => $this->p90IdentityToQuery,
            'p90_row_coverage' => $this->p90RowCoverage,
            'pair_sample_count' => $this->pairSampleCount,
            'pair_sampling_fraction' => $this->pairSamplingFraction,
            'pairwise_comparable_pairs' => $this->pairwiseComparablePairs,
            'pairwise_comparisons' => $this->pairwiseComparisons,
            'pairwise_mean_overlap_fraction' => $this->pairwiseMeanOverlapFraction,
            'pairwise_pooled_identity' => $this->pairwisePooledIdentity,
            'pairwise_similar_pairs' => $this->pairwiseSimilarPairs,
            'pairwise_similarity_fraction' => $this->pairwiseSimilarityFraction,
            'query_length' => $this->queryLength,
            'redundant_aligned_sequence_rows' => $this->redundantAlignedSequenceRows,
            'rows_with_insertions' => $this->rowsWithInsertions,
            'sampling_seed' => $this->samplingSeed,
            'sequence_count' => $this->sequenceCount,
            'total_insertion_residues' => $this->totalInsertionResidues,
            'unique_aligned_sequences' => $this->uniqueAlignedSequences,
            'unique_target_ids' => $this->uniqueTargetIds,
            'weighted_mean_column_entropy_bits' => $this->weightedMeanColumnEntropyBits,
            'weighted_mean_column_occupancy' => $this->weightedMeanColumnOccupancy,
            'weighting_kernel_comparisons' => $this->weightingKernelComparisons,
        ];
    }
}
