<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointRafflesiaEsmFinetuneOutputEndpointContentPolicyCapabilities implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $isSupported,
        public ?RunEndpointRafflesiaEsmFinetuneOutputEndpointContentPolicyCapabilitiesEnforcement $enforcement = null,
        public string $errorCode = 'content_policy_violation',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_supported',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointRafflesiaEsmFinetuneOutputEndpointContentPolicyCapabilities::fromArray()");
            }
        }
        return new self(
            isSupported: $data['is_supported'],
            enforcement: isset($data['enforcement']) ? RunEndpointRafflesiaEsmFinetuneOutputEndpointContentPolicyCapabilitiesEnforcement::from($data['enforcement']) : null,
            errorCode: $data['error_code'] ?? 'content_policy_violation',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_supported' => $this->isSupported,
            'enforcement' => $this->enforcement?->value,
            'error_code' => $this->errorCode,
        ];
    }
}
