<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointAiriInstituteModerngenaBaseOutput implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\RunEndpointAiriInstituteModerngenaBaseOutputFoundryEmbeddingVector>|null */
        public ?array $data,
        public string $layer,
        public string $modelId,
        public string $modelRelease,
        public string $object,
        public string $pooling,
        public RunEndpointAiriInstituteModerngenaBaseOutputFoundryEmbeddingUsage $usage,
        public ?string $providerRequestId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'data',
            'layer',
            'model_id',
            'model_release',
            'object',
            'pooling',
            'usage',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointAiriInstituteModerngenaBaseOutput::fromArray()");
            }
        }
        return new self(
            data: isset($data['data']) ? array_map(fn ($item) => RunEndpointAiriInstituteModerngenaBaseOutputFoundryEmbeddingVector::fromArray($item), $data['data']) : null,
            layer: $data['layer'],
            modelId: $data['model_id'],
            modelRelease: $data['model_release'],
            object: $data['object'],
            pooling: $data['pooling'],
            usage: RunEndpointAiriInstituteModerngenaBaseOutputFoundryEmbeddingUsage::fromArray($data['usage']),
            providerRequestId: $data['provider_request_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'data' => $this->data !== null ? array_map(fn ($item) => $item->toArray(), $this->data) : null,
            'layer' => $this->layer,
            'model_id' => $this->modelId,
            'model_release' => $this->modelRelease,
            'object' => $this->object,
            'pooling' => $this->pooling,
            'usage' => $this->usage->toArray(),
            'provider_request_id' => $this->providerRequestId,
        ];
    }
}
