<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointBoltzCommunityBoltz2InputStructurePredictionEntity implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Unique chain or molecule identifier. */
        public string $id,
        /**
         * One or more ligand CCD codes; mutually exclusive with smiles.
         * @var array<string>|null
         */
        public ?array $ccd = null,
        /**
         * Explicit polymer residue modifications.
         * @var array<\Rafflesia\Resource\RunEndpointBoltzCommunityBoltz2InputStructurePredictionModification>|null
         */
        public ?array $modifications = null,
        /** Polymer sequence for protein, DNA, or RNA entities. */
        public ?string $sequence = null,
        /** Ligand SMILES; mutually exclusive with ccd. */
        public ?string $smiles = null,
        /** Molecule type; defaults to protein. */
        public ?RunEndpointChaidiscoveryChai1InputStructurePredictionEntityType $type = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointBoltzCommunityBoltz2InputStructurePredictionEntity::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            ccd: $data['ccd'] ?? null,
            modifications: isset($data['modifications']) ? array_map(fn ($item) => RunEndpointBoltzCommunityBoltz2InputStructurePredictionModification::fromArray($item), $data['modifications']) : null,
            sequence: $data['sequence'] ?? null,
            smiles: $data['smiles'] ?? null,
            type: isset($data['type']) ? RunEndpointChaidiscoveryChai1InputStructurePredictionEntityType::from($data['type']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'ccd' => $this->ccd,
            'modifications' => $this->modifications !== null ? array_map(fn ($item) => $item->toArray(), $this->modifications) : null,
            'sequence' => $this->sequence,
            'smiles' => $this->smiles,
            'type' => $this->type?->value,
        ];
    }
}
