<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointRafflesiaEsmFinetuneOutputPrivateModelArtifact implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $sha256,
        public string $url,
        public ?string $contentType = null,
        public ?string $fileName = null,
        public ?int $sizeBytes = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'sha256',
            'url',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointRafflesiaEsmFinetuneOutputPrivateModelArtifact::fromArray()");
            }
        }
        return new self(
            sha256: $data['sha256'],
            url: $data['url'],
            contentType: $data['content_type'] ?? null,
            fileName: $data['file_name'] ?? null,
            sizeBytes: $data['size_bytes'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'sha256' => $this->sha256,
            'url' => $this->url,
            'content_type' => $this->contentType,
            'file_name' => $this->fileName,
            'size_bytes' => $this->sizeBytes,
        ];
    }
}
