<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointBiohubEsmfold2FastOutputMsaMeasurementLink implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public RunEndpointBiohubEsmfold2FastOutputMsaMeasurementArtifacts $artifacts,
        public string $id,
        public RunEndpointBiohubEsmfold2FastOutputMsaMeasurementSummary $summary,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'artifacts',
            'id',
            'summary',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointBiohubEsmfold2FastOutputMsaMeasurementLink::fromArray()");
            }
        }
        return new self(
            artifacts: RunEndpointBiohubEsmfold2FastOutputMsaMeasurementArtifacts::fromArray($data['artifacts']),
            id: $data['id'],
            summary: RunEndpointBiohubEsmfold2FastOutputMsaMeasurementSummary::fromArray($data['summary']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'artifacts' => $this->artifacts->toArray(),
            'id' => $this->id,
            'summary' => $this->summary->toArray(),
        ];
    }
}
