<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RunEndpointBiohubEsmc6BInputRepresentation: string
{
    case Residue = 'residue';
    case TomatoContextualTokensV1 = 'tomato_contextual_tokens_v1';
}
