<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointBiohubEsmfold26BSingleSequenceInputStructurePredictionModification implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Chemical Component Dictionary code for the modified residue. */
        public string $ccd,
        /** 1-based polymer residue position. */
        public int $position,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'ccd',
            'position',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointBiohubEsmfold26BSingleSequenceInputStructurePredictionModification::fromArray()");
            }
        }
        return new self(
            ccd: $data['ccd'],
            position: $data['position'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'ccd' => $this->ccd,
            'position' => $this->position,
        ];
    }
}
