<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunEndpointBytedanceProtenixV2464MOutputMsaMeasurementArtifacts implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public RunEndpointBytedanceProtenixV2464MOutputObjectRef $columnsCsv,
        public RunEndpointBytedanceProtenixV2464MOutputObjectRef $insertionSlotsCsv,
        public RunEndpointBytedanceProtenixV2464MOutputObjectRef $manifest,
        public RunEndpointBytedanceProtenixV2464MOutputObjectRef $rowsCsv,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'columns_csv',
            'insertion_slots_csv',
            'manifest',
            'rows_csv',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunEndpointBytedanceProtenixV2464MOutputMsaMeasurementArtifacts::fromArray()");
            }
        }
        return new self(
            columnsCsv: RunEndpointBytedanceProtenixV2464MOutputObjectRef::fromArray($data['columns_csv']),
            insertionSlotsCsv: RunEndpointBytedanceProtenixV2464MOutputObjectRef::fromArray($data['insertion_slots_csv']),
            manifest: RunEndpointBytedanceProtenixV2464MOutputObjectRef::fromArray($data['manifest']),
            rowsCsv: RunEndpointBytedanceProtenixV2464MOutputObjectRef::fromArray($data['rows_csv']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'columns_csv' => $this->columnsCsv->toArray(),
            'insertion_slots_csv' => $this->insertionSlotsCsv->toArray(),
            'manifest' => $this->manifest->toArray(),
            'rows_csv' => $this->rowsCsv->toArray(),
        ];
    }
}
