<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RunEndpointRafflesiaMsaOutputMsaArtifactRole: string
{
    case Lane = 'lane';
    case Unpaired = 'unpaired';
    case PairingSource = 'pairing_source';
    case PairedChain = 'paired_chain';
}
