<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class RunProgress implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $stage,
        public \DateTimeImmutable $updatedAt,
        public ?int $current = null,
        public ?int $total = null,
        public ?string $unit = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'stage',
            'updated_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for RunProgress::fromArray()");
            }
        }
        return new self(
            stage: $data['stage'],
            updatedAt: new \DateTimeImmutable($data['updated_at']),
            current: $data['current'] ?? null,
            total: $data['total'] ?? null,
            unit: $data['unit'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'stage' => $this->stage,
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'current' => $this->current,
            'total' => $this->total,
            'unit' => $this->unit,
        ];
    }
}
