<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum RunQueueStatusStatus: string
{
    case InQueue = 'IN_QUEUE';
    case InProgress = 'IN_PROGRESS';
    case Completed = 'COMPLETED';
}
