<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SearchSegmentBuildData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $algorithm,
        public int $blockBytes,
        public int $blockCount,
        public int $blockSizeBytes,
        public string $keyMode,
        public SearchSegmentManifest $manifest,
        public ObjectRef $manifestObject,
        public string $name,
        public SearchSegmentRoot $root,
        public ObjectRef $rootObject,
        public string $segmentId,
        public ObjectRef $sourceObject,
        public string $version,
        public ?ObjectRef $bundleObject = null,
        public ?string $datasetName = null,
        public ?string $datasetVersion = null,
        public ?int $footerLengthBytes = null,
        public ?int $footerOffsetBytes = null,
        public ?string $footerSha256 = null,
        public ?int $recordCount = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'algorithm',
            'block_bytes',
            'block_count',
            'block_size_bytes',
            'key_mode',
            'manifest',
            'manifest_object',
            'name',
            'root',
            'root_object',
            'segment_id',
            'source_object',
            'version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SearchSegmentBuildData::fromArray()");
            }
        }
        return new self(
            algorithm: $data['algorithm'],
            blockBytes: $data['block_bytes'],
            blockCount: $data['block_count'],
            blockSizeBytes: $data['block_size_bytes'],
            keyMode: $data['key_mode'],
            manifest: SearchSegmentManifest::fromArray($data['manifest']),
            manifestObject: ObjectRef::fromArray($data['manifest_object']),
            name: $data['name'],
            root: SearchSegmentRoot::fromArray($data['root']),
            rootObject: ObjectRef::fromArray($data['root_object']),
            segmentId: $data['segment_id'],
            sourceObject: ObjectRef::fromArray($data['source_object']),
            version: $data['version'],
            bundleObject: isset($data['bundle_object']) ? ObjectRef::fromArray($data['bundle_object']) : null,
            datasetName: $data['dataset_name'] ?? null,
            datasetVersion: $data['dataset_version'] ?? null,
            footerLengthBytes: $data['footer_length_bytes'] ?? null,
            footerOffsetBytes: $data['footer_offset_bytes'] ?? null,
            footerSha256: $data['footer_sha256'] ?? null,
            recordCount: $data['record_count'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'algorithm' => $this->algorithm,
            'block_bytes' => $this->blockBytes,
            'block_count' => $this->blockCount,
            'block_size_bytes' => $this->blockSizeBytes,
            'key_mode' => $this->keyMode,
            'manifest' => $this->manifest->toArray(),
            'manifest_object' => $this->manifestObject->toArray(),
            'name' => $this->name,
            'root' => $this->root->toArray(),
            'root_object' => $this->rootObject->toArray(),
            'segment_id' => $this->segmentId,
            'source_object' => $this->sourceObject->toArray(),
            'version' => $this->version,
            'bundle_object' => $this->bundleObject?->toArray(),
            'dataset_name' => $this->datasetName,
            'dataset_version' => $this->datasetVersion,
            'footer_length_bytes' => $this->footerLengthBytes,
            'footer_offset_bytes' => $this->footerOffsetBytes,
            'footer_sha256' => $this->footerSha256,
            'record_count' => $this->recordCount,
        ];
    }
}
