<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SearchSegmentPrefetchData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $blockCacheHits,
        public int $blockCacheMisses,
        public SearchPhysicalPlanBudget $budget,
        public int $materializedBytes,
        public int $objectBytesFetched,
        public int $objectReadCount,
        public SearchSegmentPlanData $plan,
        /** @var array<string>|null */
        public ?array $prefetchedObjectIds,
        public string $segmentId,
        public int $selectedBlockCount,
        public ?string $queryKey = null,
        /** @var array<\Rafflesia\Resource\SearchWarning>|null */
        public ?array $readWarnings = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'block_cache_hits',
            'block_cache_misses',
            'budget',
            'materialized_bytes',
            'object_bytes_fetched',
            'object_read_count',
            'plan',
            'prefetched_object_ids',
            'segment_id',
            'selected_block_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SearchSegmentPrefetchData::fromArray()");
            }
        }
        return new self(
            blockCacheHits: $data['block_cache_hits'],
            blockCacheMisses: $data['block_cache_misses'],
            budget: SearchPhysicalPlanBudget::fromArray($data['budget']),
            materializedBytes: $data['materialized_bytes'],
            objectBytesFetched: $data['object_bytes_fetched'],
            objectReadCount: $data['object_read_count'],
            plan: SearchSegmentPlanData::fromArray($data['plan']),
            prefetchedObjectIds: $data['prefetched_object_ids'] ?? null,
            segmentId: $data['segment_id'],
            selectedBlockCount: $data['selected_block_count'],
            queryKey: $data['query_key'] ?? null,
            readWarnings: isset($data['read_warnings']) ? array_map(fn ($item) => SearchWarning::fromArray($item), $data['read_warnings']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'block_cache_hits' => $this->blockCacheHits,
            'block_cache_misses' => $this->blockCacheMisses,
            'budget' => $this->budget->toArray(),
            'materialized_bytes' => $this->materializedBytes,
            'object_bytes_fetched' => $this->objectBytesFetched,
            'object_read_count' => $this->objectReadCount,
            'plan' => $this->plan->toArray(),
            'prefetched_object_ids' => $this->prefetchedObjectIds,
            'segment_id' => $this->segmentId,
            'selected_block_count' => $this->selectedBlockCount,
            'query_key' => $this->queryKey,
            'read_warnings' => $this->readWarnings !== null ? array_map(fn ($item) => $item->toArray(), $this->readWarnings) : null,
        ];
    }
}
