<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SecondaryStructureResidue implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $chainId,
        public string $code,
        public string $label,
        public int $position,
        public string $residue,
        public string $simple,
        public ?string $authChainId = null,
        public ?int $authPosition = null,
        public ?string $insertionCode = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'chain_id',
            'code',
            'label',
            'position',
            'residue',
            'simple',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SecondaryStructureResidue::fromArray()");
            }
        }
        return new self(
            chainId: $data['chain_id'],
            code: $data['code'],
            label: $data['label'],
            position: $data['position'],
            residue: $data['residue'],
            simple: $data['simple'],
            authChainId: $data['auth_chain_id'] ?? null,
            authPosition: $data['auth_position'] ?? null,
            insertionCode: $data['insertion_code'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'chain_id' => $this->chainId,
            'code' => $this->code,
            'label' => $this->label,
            'position' => $this->position,
            'residue' => $this->residue,
            'simple' => $this->simple,
            'auth_chain_id' => $this->authChainId,
            'auth_position' => $this->authPosition,
            'insertion_code' => $this->insertionCode,
        ];
    }
}
