<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SecondaryStructureSummary implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $coilCount,
        public float $coilFraction,
        /** @var array<string, int> */
        public array $counts,
        public int $helixCount,
        public float $helixFraction,
        public int $residueCount,
        public int $strandCount,
        public float $strandFraction,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'coil_count',
            'coil_fraction',
            'counts',
            'helix_count',
            'helix_fraction',
            'residue_count',
            'strand_count',
            'strand_fraction',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SecondaryStructureSummary::fromArray()");
            }
        }
        return new self(
            coilCount: $data['coil_count'],
            coilFraction: $data['coil_fraction'],
            counts: $data['counts'],
            helixCount: $data['helix_count'],
            helixFraction: $data['helix_fraction'],
            residueCount: $data['residue_count'],
            strandCount: $data['strand_count'],
            strandFraction: $data['strand_fraction'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'coil_count' => $this->coilCount,
            'coil_fraction' => $this->coilFraction,
            'counts' => $this->counts,
            'helix_count' => $this->helixCount,
            'helix_fraction' => $this->helixFraction,
            'residue_count' => $this->residueCount,
            'strand_count' => $this->strandCount,
            'strand_fraction' => $this->strandFraction,
        ];
    }
}
