<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SemanticRelationshipPredicate implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $leftSource,
        public string $rightSource,
        public ?OntologyKeyVariant $keyVariant = null,
        public ?string $relationshipId = null,
        /** @var array<\Rafflesia\Resource\SemanticFilter>|null */
        public ?array $where = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'left_source',
            'right_source',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SemanticRelationshipPredicate::fromArray()");
            }
        }
        return new self(
            leftSource: $data['left_source'],
            rightSource: $data['right_source'],
            keyVariant: isset($data['key_variant']) ? OntologyKeyVariant::from($data['key_variant']) : null,
            relationshipId: $data['relationship_id'] ?? null,
            where: isset($data['where']) ? array_map(fn ($item) => SemanticFilter::fromArray($item), $data['where']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'left_source' => $this->leftSource,
            'right_source' => $this->rightSource,
            'key_variant' => $this->keyVariant?->value,
            'relationship_id' => $this->relationshipId,
            'where' => $this->where !== null ? array_map(fn ($item) => $item->toArray(), $this->where) : null,
        ];
    }
}
