<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum SemanticJoinActivation: string
{
    case Always = 'always';
    case WhenReferenced = 'when_referenced';
}
