<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SemanticQueryData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public QueryRequest $compiledQuery,
        public string $id,
        /** @var array<\Rafflesia\Resource\OntologyJoinStep>|null */
        public ?array $joinPlan,
        public string $object,
        public string $ontologyDigest,
        public string $ontologyVersion,
        /** @var array<\Rafflesia\Resource\QueryOutputColumnContract>|null */
        public ?array $outputColumns,
        public string $semanticDialect,
        public string $semanticQueryDigest,
        /** @var array<\Rafflesia\Resource\SemanticJoin>|null */
        public ?array $activatedJoins = null,
        /** @var array<\Rafflesia\Resource\SemanticJoin>|null */
        public ?array $prunedJoins = null,
        /** @var array<string>|null */
        public ?array $resultGrain = null,
        /** @var array<string>|null */
        public ?array $resultKey = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'compiled_query',
            'id',
            'join_plan',
            'object',
            'ontology_digest',
            'ontology_version',
            'output_columns',
            'semantic_dialect',
            'semantic_query_digest',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SemanticQueryData::fromArray()");
            }
        }
        return new self(
            compiledQuery: QueryRequest::fromArray($data['compiled_query']),
            id: $data['id'],
            joinPlan: isset($data['join_plan']) ? array_map(fn ($item) => OntologyJoinStep::fromArray($item), $data['join_plan']) : null,
            object: $data['object'],
            ontologyDigest: $data['ontology_digest'],
            ontologyVersion: $data['ontology_version'],
            outputColumns: isset($data['output_columns']) ? array_map(fn ($item) => QueryOutputColumnContract::fromArray($item), $data['output_columns']) : null,
            semanticDialect: $data['semantic_dialect'],
            semanticQueryDigest: $data['semantic_query_digest'],
            activatedJoins: isset($data['activated_joins']) ? array_map(fn ($item) => SemanticJoin::fromArray($item), $data['activated_joins']) : null,
            prunedJoins: isset($data['pruned_joins']) ? array_map(fn ($item) => SemanticJoin::fromArray($item), $data['pruned_joins']) : null,
            resultGrain: $data['result_grain'] ?? null,
            resultKey: $data['result_key'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'compiled_query' => $this->compiledQuery->toArray(),
            'id' => $this->id,
            'join_plan' => $this->joinPlan !== null ? array_map(fn ($item) => $item->toArray(), $this->joinPlan) : null,
            'object' => $this->object,
            'ontology_digest' => $this->ontologyDigest,
            'ontology_version' => $this->ontologyVersion,
            'output_columns' => $this->outputColumns !== null ? array_map(fn ($item) => $item->toArray(), $this->outputColumns) : null,
            'semantic_dialect' => $this->semanticDialect,
            'semantic_query_digest' => $this->semanticQueryDigest,
            'activated_joins' => $this->activatedJoins !== null ? array_map(fn ($item) => $item->toArray(), $this->activatedJoins) : null,
            'pruned_joins' => $this->prunedJoins !== null ? array_map(fn ($item) => $item->toArray(), $this->prunedJoins) : null,
            'result_grain' => $this->resultGrain,
            'result_key' => $this->resultKey,
        ];
    }
}
