<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SequenceSeedIndexObjectReadBudget implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $isConfigured,
        public bool $isWithinBudget,
        public int $materializedDatabaseBytes,
        public int $plannedObjectBytes,
        public int $plannedObjectReadCount,
        public ?int $maxObjectBytes = null,
        public ?int $maxObjectReads = null,
        /** @var array<string>|null */
        public ?array $reasons = null,
        public ?bool $requireZeroMaterialization = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_configured',
            'is_within_budget',
            'materialized_database_bytes',
            'planned_object_bytes',
            'planned_object_read_count',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SequenceSeedIndexObjectReadBudget::fromArray()");
            }
        }
        return new self(
            isConfigured: $data['is_configured'],
            isWithinBudget: $data['is_within_budget'],
            materializedDatabaseBytes: $data['materialized_database_bytes'],
            plannedObjectBytes: $data['planned_object_bytes'],
            plannedObjectReadCount: $data['planned_object_read_count'],
            maxObjectBytes: $data['max_object_bytes'] ?? null,
            maxObjectReads: $data['max_object_reads'] ?? null,
            reasons: $data['reasons'] ?? null,
            requireZeroMaterialization: $data['require_zero_materialization'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_configured' => $this->isConfigured,
            'is_within_budget' => $this->isWithinBudget,
            'materialized_database_bytes' => $this->materializedDatabaseBytes,
            'planned_object_bytes' => $this->plannedObjectBytes,
            'planned_object_read_count' => $this->plannedObjectReadCount,
            'max_object_bytes' => $this->maxObjectBytes,
            'max_object_reads' => $this->maxObjectReads,
            'reasons' => $this->reasons,
            'require_zero_materialization' => $this->requireZeroMaterialization,
        ];
    }
}
