<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

enum SequenceSeedIndexWalRecordOperation: string
{
    case Upsert = 'upsert';
    case Delete = 'delete';
}
