<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SequenceCandidateVerifyCheck implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $name,
        public bool $passed,
        public ?string $message = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'name',
            'passed',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SequenceCandidateVerifyCheck::fromArray()");
            }
        }
        return new self(
            name: $data['name'],
            passed: $data['passed'],
            message: $data['message'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'passed' => $this->passed,
            'message' => $this->message,
        ];
    }
}
