<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SequenceCandidateApplyData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        public SequenceCandidateBuildData $build,
        public string $decisionId,
        public string $engine,
        public SequenceCandidateSweepRow $selected,
        public ?ObjectRef $decisionObject = null,
        public ?int $timeoutMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'build',
            'decision_id',
            'engine',
            'selected',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SequenceCandidateApplyData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            build: SequenceCandidateBuildData::fromArray($data['build']),
            decisionId: $data['decision_id'],
            engine: $data['engine'],
            selected: SequenceCandidateSweepRow::fromArray($data['selected']),
            decisionObject: isset($data['decision_object']) ? ObjectRef::fromArray($data['decision_object']) : null,
            timeoutMs: $data['timeout_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'build' => $this->build->toArray(),
            'decision_id' => $this->decisionId,
            'engine' => $this->engine,
            'selected' => $this->selected->toArray(),
            'decision_object' => $this->decisionObject?->toArray(),
            'timeout_ms' => $this->timeoutMs,
        ];
    }
}
