<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SequenceCatalogManifest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $catalogId,
        public string $contentSha256,
        public string $createdAt,
        /** @var array<\Rafflesia\Resource\SequenceCatalogEntry>|null */
        public ?array $entries,
        public ObjectRef $fastaObject,
        public string $kind,
        public int $manifestVersion,
        public string $name,
        public int $sequenceCount,
        public string $version,
        public ?string $datasetName = null,
        public ?string $datasetVersion = null,
        public ?DatabaseSnapshot $sourceDatabaseSnapshot = null,
        public ?ObjectRef $sourceObject = null,
        public ?string $sourceObjectId = null,
        public ?string $sourcePath = null,
        public ?ToolVersion $sourceToolVersion = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'catalog_id',
            'content_sha256',
            'created_at',
            'entries',
            'fasta_object',
            'kind',
            'manifest_version',
            'name',
            'sequence_count',
            'version',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SequenceCatalogManifest::fromArray()");
            }
        }
        return new self(
            catalogId: $data['catalog_id'],
            contentSha256: $data['content_sha256'],
            createdAt: $data['created_at'],
            entries: isset($data['entries']) ? array_map(fn ($item) => SequenceCatalogEntry::fromArray($item), $data['entries']) : null,
            fastaObject: ObjectRef::fromArray($data['fasta_object']),
            kind: $data['kind'],
            manifestVersion: $data['manifest_version'],
            name: $data['name'],
            sequenceCount: $data['sequence_count'],
            version: $data['version'],
            datasetName: $data['dataset_name'] ?? null,
            datasetVersion: $data['dataset_version'] ?? null,
            sourceDatabaseSnapshot: isset($data['source_database_snapshot']) ? DatabaseSnapshot::fromArray($data['source_database_snapshot']) : null,
            sourceObject: isset($data['source_object']) ? ObjectRef::fromArray($data['source_object']) : null,
            sourceObjectId: $data['source_object_id'] ?? null,
            sourcePath: $data['source_path'] ?? null,
            sourceToolVersion: isset($data['source_tool_version']) ? ToolVersion::fromArray($data['source_tool_version']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'catalog_id' => $this->catalogId,
            'content_sha256' => $this->contentSha256,
            'created_at' => $this->createdAt,
            'entries' => $this->entries !== null ? array_map(fn ($item) => $item->toArray(), $this->entries) : null,
            'fasta_object' => $this->fastaObject->toArray(),
            'kind' => $this->kind,
            'manifest_version' => $this->manifestVersion,
            'name' => $this->name,
            'sequence_count' => $this->sequenceCount,
            'version' => $this->version,
            'dataset_name' => $this->datasetName,
            'dataset_version' => $this->datasetVersion,
            'source_database_snapshot' => $this->sourceDatabaseSnapshot?->toArray(),
            'source_object' => $this->sourceObject?->toArray(),
            'source_object_id' => $this->sourceObjectId,
            'source_path' => $this->sourcePath,
            'source_tool_version' => $this->sourceToolVersion?->toArray(),
        ];
    }
}
