<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SimulationGromacsStageOutputObject implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $isPresent,
        public string $path,
        public ?string $format = null,
        public ?string $localPath = null,
        public ?ObjectRef $object = null,
        public ?string $plannedRef = null,
        public ?string $role = null,
        public ?string $sha256 = null,
        public ?int $sizeBytes = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'is_present',
            'path',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SimulationGromacsStageOutputObject::fromArray()");
            }
        }
        return new self(
            isPresent: $data['is_present'],
            path: $data['path'],
            format: $data['format'] ?? null,
            localPath: $data['local_path'] ?? null,
            object: isset($data['object']) ? ObjectRef::fromArray($data['object']) : null,
            plannedRef: $data['planned_ref'] ?? null,
            role: $data['role'] ?? null,
            sha256: $data['sha256'] ?? null,
            sizeBytes: $data['size_bytes'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'is_present' => $this->isPresent,
            'path' => $this->path,
            'format' => $this->format,
            'local_path' => $this->localPath,
            'object' => $this->object?->toArray(),
            'planned_ref' => $this->plannedRef,
            'role' => $this->role,
            'sha256' => $this->sha256,
            'size_bytes' => $this->sizeBytes,
        ];
    }
}
