<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SimulationRuntimeBootstrapRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Install requested packages into the virtual environment after creation. */
        public bool $install,
        /** Remove and recreate the output_dir before bootstrapping. */
        public ?bool $forceRecreate = null,
        /** Local directory for the simulation Python virtual environment. Defaults to .evidence/simulations/mdanalysis-venv when called from the repo. */
        public ?string $outputDir = null,
        /**
         * Python packages to install when install is true. Defaults to MDAnalysis.
         * @var array<string>|null
         */
        public ?array $packages = null,
        /** Python executable used to create the virtual environment. Defaults to python3 on PATH. */
        public ?string $pythonPath = null,
        public ?int $timeoutMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'install',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SimulationRuntimeBootstrapRequest::fromArray()");
            }
        }
        return new self(
            install: $data['install'],
            forceRecreate: $data['force_recreate'] ?? null,
            outputDir: $data['output_dir'] ?? null,
            packages: $data['packages'] ?? null,
            pythonPath: $data['python_path'] ?? null,
            timeoutMs: $data['timeout_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'install' => $this->install,
            'force_recreate' => $this->forceRecreate,
            'output_dir' => $this->outputDir,
            'packages' => $this->packages,
            'python_path' => $this->pythonPath,
            'timeout_ms' => $this->timeoutMs,
        ];
    }
}
