<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SimulationGromacsInputMaterialization implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public SimulationGromacsFileRef $input,
        public SimulationGromacsInputResolution $resolution,
        public string $scriptPath,
        public string $status,
        public ?SimulationGromacsInventoryEntry $candidate = null,
        public ?ObjectDownloadData $downloadedObject = null,
        public ?string $localPath = null,
        public ?string $message = null,
        public ?string $normalizedPath = null,
        public ?ObjectRef $object = null,
        public ?string $producer = null,
        public ?string $sha256 = null,
        public ?int $sizeBytes = null,
        public ?string $targetRelativePath = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'input',
            'resolution',
            'script_path',
            'status',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SimulationGromacsInputMaterialization::fromArray()");
            }
        }
        return new self(
            input: SimulationGromacsFileRef::fromArray($data['input']),
            resolution: SimulationGromacsInputResolution::fromArray($data['resolution']),
            scriptPath: $data['script_path'],
            status: $data['status'],
            candidate: isset($data['candidate']) ? SimulationGromacsInventoryEntry::fromArray($data['candidate']) : null,
            downloadedObject: isset($data['downloaded_object']) ? ObjectDownloadData::fromArray($data['downloaded_object']) : null,
            localPath: $data['local_path'] ?? null,
            message: $data['message'] ?? null,
            normalizedPath: $data['normalized_path'] ?? null,
            object: isset($data['object']) ? ObjectRef::fromArray($data['object']) : null,
            producer: $data['producer'] ?? null,
            sha256: $data['sha256'] ?? null,
            sizeBytes: $data['size_bytes'] ?? null,
            targetRelativePath: $data['target_relative_path'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'input' => $this->input->toArray(),
            'resolution' => $this->resolution->toArray(),
            'script_path' => $this->scriptPath,
            'status' => $this->status,
            'candidate' => $this->candidate?->toArray(),
            'downloaded_object' => $this->downloadedObject?->toArray(),
            'local_path' => $this->localPath,
            'message' => $this->message,
            'normalized_path' => $this->normalizedPath,
            'object' => $this->object?->toArray(),
            'producer' => $this->producer,
            'sha256' => $this->sha256,
            'size_bytes' => $this->sizeBytes,
            'target_relative_path' => $this->targetRelativePath,
        ];
    }
}
