<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class SimulationTrajectoryImportData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public SimulationBackendEvidence $backend,
        public float $frameTimeStepPs,
        public int $importedObjectCount,
        public bool $isDecoded,
        public float $timeEndPs,
        public float $timeStartPs,
        public SimulationInputRef $trajectory,
        public string $trajectoryId,
        public ?int $atomCount = null,
        public ?int $frameCount = null,
        public ?bool $hasTime = null,
        public ?int $residueCount = null,
        /** @var array<string>|null */
        public ?array $supportedMeasurements = null,
        public ?SimulationInputRef $topology = null,
        public ?string $topologyFormat = null,
        public ?string $trajectoryFormat = null,
        public ?SimulationTrajectoryManifest $trajectoryManifest = null,
        public ?ObjectRef $trajectoryManifestObject = null,
        public ?int $unitCellFrameCount = null,
        /** @var array<string>|null */
        public ?array $unsupportedMeasurements = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'frame_time_step_ps',
            'imported_object_count',
            'is_decoded',
            'time_end_ps',
            'time_start_ps',
            'trajectory',
            'trajectory_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SimulationTrajectoryImportData::fromArray()");
            }
        }
        return new self(
            backend: SimulationBackendEvidence::fromArray($data['backend']),
            frameTimeStepPs: $data['frame_time_step_ps'],
            importedObjectCount: $data['imported_object_count'],
            isDecoded: $data['is_decoded'],
            timeEndPs: $data['time_end_ps'],
            timeStartPs: $data['time_start_ps'],
            trajectory: SimulationInputRef::fromArray($data['trajectory']),
            trajectoryId: $data['trajectory_id'],
            atomCount: $data['atom_count'] ?? null,
            frameCount: $data['frame_count'] ?? null,
            hasTime: $data['has_time'] ?? null,
            residueCount: $data['residue_count'] ?? null,
            supportedMeasurements: $data['supported_measurements'] ?? null,
            topology: isset($data['topology']) ? SimulationInputRef::fromArray($data['topology']) : null,
            topologyFormat: $data['topology_format'] ?? null,
            trajectoryFormat: $data['trajectory_format'] ?? null,
            trajectoryManifest: isset($data['trajectory_manifest']) ? SimulationTrajectoryManifest::fromArray($data['trajectory_manifest']) : null,
            trajectoryManifestObject: isset($data['trajectory_manifest_object']) ? ObjectRef::fromArray($data['trajectory_manifest_object']) : null,
            unitCellFrameCount: $data['unit_cell_frame_count'] ?? null,
            unsupportedMeasurements: $data['unsupported_measurements'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend->toArray(),
            'frame_time_step_ps' => $this->frameTimeStepPs,
            'imported_object_count' => $this->importedObjectCount,
            'is_decoded' => $this->isDecoded,
            'time_end_ps' => $this->timeEndPs,
            'time_start_ps' => $this->timeStartPs,
            'trajectory' => $this->trajectory->toArray(),
            'trajectory_id' => $this->trajectoryId,
            'atom_count' => $this->atomCount,
            'frame_count' => $this->frameCount,
            'has_time' => $this->hasTime,
            'residue_count' => $this->residueCount,
            'supported_measurements' => $this->supportedMeasurements,
            'topology' => $this->topology?->toArray(),
            'topology_format' => $this->topologyFormat,
            'trajectory_format' => $this->trajectoryFormat,
            'trajectory_manifest' => $this->trajectoryManifest?->toArray(),
            'trajectory_manifest_object' => $this->trajectoryManifestObject?->toArray(),
            'unit_cell_frame_count' => $this->unitCellFrameCount,
            'unsupported_measurements' => $this->unsupportedMeasurements,
        ];
    }
}
