<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class StorageSettingsUpdateRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?int $expirationDurationSeconds = null,
        public ?BlobAcl $initialAcl = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            expirationDurationSeconds: $data['expiration_duration_seconds'] ?? null,
            initialAcl: isset($data['initial_acl']) ? BlobAcl::fromArray($data['initial_acl']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'expiration_duration_seconds' => $this->expirationDurationSeconds,
            'initial_acl' => $this->initialAcl?->toArray(),
        ];
    }
}
