<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class StructureAxisProfileData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $atomCount,
        public float $axialSpanAngstrom,
        /** @var array<float>|null */
        public ?array $axisDirection,
        /** @var array<float>|null */
        public ?array $axisPoint,
        /** @var array<\Rafflesia\Resource\StructureAxisProfileBin>|null */
        public ?array $bins,
        public float $maxRadiusAngstrom,
        public float $minRadiusAngstrom,
        public float $minRadiusAxialPositionAngstrom,
        /** @var array<float>|null */
        public ?array $radiusPercentiles,
        public string $schemaVersion,
        public string $structureId,
        /** Table row provenance when the axis was resolved from structure_principal_axes. */
        public ?StructureAxisProfileAxisSource $axisSource = null,
        /** Immutable relation artifact emitted when output_relation is requested */
        public ?RelationArtifactData $relation = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'atom_count',
            'axial_span_angstrom',
            'axis_direction',
            'axis_point',
            'bins',
            'max_radius_angstrom',
            'min_radius_angstrom',
            'min_radius_axial_position_angstrom',
            'radius_percentiles',
            'schema_version',
            'structure_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for StructureAxisProfileData::fromArray()");
            }
        }
        return new self(
            atomCount: $data['atom_count'],
            axialSpanAngstrom: $data['axial_span_angstrom'],
            axisDirection: $data['axis_direction'] ?? null,
            axisPoint: $data['axis_point'] ?? null,
            bins: isset($data['bins']) ? array_map(fn ($item) => StructureAxisProfileBin::fromArray($item), $data['bins']) : null,
            maxRadiusAngstrom: $data['max_radius_angstrom'],
            minRadiusAngstrom: $data['min_radius_angstrom'],
            minRadiusAxialPositionAngstrom: $data['min_radius_axial_position_angstrom'],
            radiusPercentiles: $data['radius_percentiles'] ?? null,
            schemaVersion: $data['schema_version'],
            structureId: $data['structure_id'],
            axisSource: isset($data['axis_source']) ? StructureAxisProfileAxisSource::fromArray($data['axis_source']) : null,
            relation: isset($data['relation']) ? RelationArtifactData::fromArray($data['relation']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'atom_count' => $this->atomCount,
            'axial_span_angstrom' => $this->axialSpanAngstrom,
            'axis_direction' => $this->axisDirection,
            'axis_point' => $this->axisPoint,
            'bins' => $this->bins !== null ? array_map(fn ($item) => $item->toArray(), $this->bins) : null,
            'max_radius_angstrom' => $this->maxRadiusAngstrom,
            'min_radius_angstrom' => $this->minRadiusAngstrom,
            'min_radius_axial_position_angstrom' => $this->minRadiusAxialPositionAngstrom,
            'radius_percentiles' => $this->radiusPercentiles,
            'schema_version' => $this->schemaVersion,
            'structure_id' => $this->structureId,
            'axis_source' => $this->axisSource?->toArray(),
            'relation' => $this->relation?->toArray(),
        ];
    }
}
