<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class StructureInspectData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public int $atomCount,
        /** @var array<\Rafflesia\Resource\ChainSummary>|null */
        public ?array $chains,
        public string $format,
        public bool $hasPlddtLikeBFactor,
        /** True when the response contains only identity/provenance fields because inspection did not complete. */
        public bool $isPartial,
        /** @var array<\Rafflesia\Resource\ObjectRef>|null */
        public ?array $objects,
        public int $residueCount,
        /** @var array<\Rafflesia\Resource\ResidueRange>|null */
        public ?array $residueRanges,
        /** @var array<\Rafflesia\Resource\ResidueSummary>|null */
        public ?array $residues,
        public string $structureId,
        /**
         * Input structure references attempted while resolving this inspection.
         * @var array<string>|null
         */
        public ?array $attemptedRefs = null,
        /** Backend used for inspection, e.g. local_store. */
        public ?string $backend = null,
        public ?CartesianBounds $bounds = null,
        /** Cache state for the structure record, e.g. hit. */
        public ?string $cacheStatus = null,
        /** @var array<float>|null */
        public ?array $centroid = null,
        /** Last completed stage, e.g. record_loaded, object_read, parsed. */
        public ?string $completedStage = null,
        public ?string $confidenceMetric = null,
        /** Elapsed inspection time in milliseconds. */
        public ?int $elapsedMs = null,
        /** @var array<\Rafflesia\Resource\StructureEntityCandidate>|null */
        public ?array $entityCandidates = null,
        /** Inspection status: complete for fully parsed structures, partial for bounded responses. */
        public ?string $inspectStatus = null,
        public ?float $meanBFactor = null,
        public ?float $meanConfidenceValue = null,
        public ?float $meanPlddt = null,
        /** @var array<string, string>|null */
        public ?array $metadata = null,
        /** @var array<\Rafflesia\Resource\StructureRepeatedChainGroup>|null */
        public ?array $repeatedChainGroups = null,
        /** True when the timeout budget elapsed before read/parse completion. */
        public ?bool $timedOut = null,
        /** Timeout budget used for object read and parse. */
        public ?int $timeoutMs = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'atom_count',
            'chains',
            'format',
            'has_plddt_like_b_factor',
            'is_partial',
            'objects',
            'residue_count',
            'residue_ranges',
            'residues',
            'structure_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for StructureInspectData::fromArray()");
            }
        }
        return new self(
            atomCount: $data['atom_count'],
            chains: isset($data['chains']) ? array_map(fn ($item) => ChainSummary::fromArray($item), $data['chains']) : null,
            format: $data['format'],
            hasPlddtLikeBFactor: $data['has_plddt_like_b_factor'],
            isPartial: $data['is_partial'],
            objects: isset($data['objects']) ? array_map(fn ($item) => ObjectRef::fromArray($item), $data['objects']) : null,
            residueCount: $data['residue_count'],
            residueRanges: isset($data['residue_ranges']) ? array_map(fn ($item) => ResidueRange::fromArray($item), $data['residue_ranges']) : null,
            residues: isset($data['residues']) ? array_map(fn ($item) => ResidueSummary::fromArray($item), $data['residues']) : null,
            structureId: $data['structure_id'],
            attemptedRefs: $data['attempted_refs'] ?? null,
            backend: $data['backend'] ?? null,
            bounds: isset($data['bounds']) ? CartesianBounds::fromArray($data['bounds']) : null,
            cacheStatus: $data['cache_status'] ?? null,
            centroid: $data['centroid'] ?? null,
            completedStage: $data['completed_stage'] ?? null,
            confidenceMetric: $data['confidence_metric'] ?? null,
            elapsedMs: $data['elapsed_ms'] ?? null,
            entityCandidates: isset($data['entity_candidates']) ? array_map(fn ($item) => StructureEntityCandidate::fromArray($item), $data['entity_candidates']) : null,
            inspectStatus: $data['inspect_status'] ?? null,
            meanBFactor: $data['mean_b_factor'] ?? null,
            meanConfidenceValue: $data['mean_confidence_value'] ?? null,
            meanPlddt: $data['mean_plddt'] ?? null,
            metadata: $data['metadata'] ?? null,
            repeatedChainGroups: isset($data['repeated_chain_groups']) ? array_map(fn ($item) => StructureRepeatedChainGroup::fromArray($item), $data['repeated_chain_groups']) : null,
            timedOut: $data['timed_out'] ?? null,
            timeoutMs: $data['timeout_ms'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'atom_count' => $this->atomCount,
            'chains' => $this->chains !== null ? array_map(fn ($item) => $item->toArray(), $this->chains) : null,
            'format' => $this->format,
            'has_plddt_like_b_factor' => $this->hasPlddtLikeBFactor,
            'is_partial' => $this->isPartial,
            'objects' => $this->objects !== null ? array_map(fn ($item) => $item->toArray(), $this->objects) : null,
            'residue_count' => $this->residueCount,
            'residue_ranges' => $this->residueRanges !== null ? array_map(fn ($item) => $item->toArray(), $this->residueRanges) : null,
            'residues' => $this->residues !== null ? array_map(fn ($item) => $item->toArray(), $this->residues) : null,
            'structure_id' => $this->structureId,
            'attempted_refs' => $this->attemptedRefs,
            'backend' => $this->backend,
            'bounds' => $this->bounds?->toArray(),
            'cache_status' => $this->cacheStatus,
            'centroid' => $this->centroid,
            'completed_stage' => $this->completedStage,
            'confidence_metric' => $this->confidenceMetric,
            'elapsed_ms' => $this->elapsedMs,
            'entity_candidates' => $this->entityCandidates !== null ? array_map(fn ($item) => $item->toArray(), $this->entityCandidates) : null,
            'inspect_status' => $this->inspectStatus,
            'mean_b_factor' => $this->meanBFactor,
            'mean_confidence_value' => $this->meanConfidenceValue,
            'mean_plddt' => $this->meanPlddt,
            'metadata' => $this->metadata,
            'repeated_chain_groups' => $this->repeatedChainGroups !== null ? array_map(fn ($item) => $item->toArray(), $this->repeatedChainGroups) : null,
            'timed_out' => $this->timedOut,
            'timeout_ms' => $this->timeoutMs,
        ];
    }
}
