<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class StructureAlignMatrixPair implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public bool $executed,
        public string $queryId,
        public string $targetId,
        public ?StructureAlignment $alignment = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'executed',
            'query_id',
            'target_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for StructureAlignMatrixPair::fromArray()");
            }
        }
        return new self(
            executed: $data['executed'],
            queryId: $data['query_id'],
            targetId: $data['target_id'],
            alignment: isset($data['alignment']) ? StructureAlignment::fromArray($data['alignment']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'executed' => $this->executed,
            'query_id' => $this->queryId,
            'target_id' => $this->targetId,
            'alignment' => $this->alignment?->toArray(),
        ];
    }
}
