<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class TargetResolveData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<\Rafflesia\Resource\TargetCandidate>|null */
        public ?array $candidates,
        public string $query,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'candidates',
            'query',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for TargetResolveData::fromArray()");
            }
        }
        return new self(
            candidates: isset($data['candidates']) ? array_map(fn ($item) => TargetCandidate::fromArray($item), $data['candidates']) : null,
            query: $data['query'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'candidates' => $this->candidates !== null ? array_map(fn ($item) => $item->toArray(), $this->candidates) : null,
            'query' => $this->query,
        ];
    }
}
