<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class TrustedSigningKey implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $createdAt,
        public string $fingerprint,
        public string $id,
        public string $organizationId,
        public string $publicKey,
        public string $schemaVersion,
        public TrustedSigningKeyStatus $status,
        public string $updatedAt,
        public ?string $revokedAt = null,
        public string $object = 'registry_signing_key',
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'created_at',
            'fingerprint',
            'id',
            'organization_id',
            'public_key',
            'schema_version',
            'status',
            'updated_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for TrustedSigningKey::fromArray()");
            }
        }
        return new self(
            createdAt: $data['created_at'],
            fingerprint: $data['fingerprint'],
            id: $data['id'],
            organizationId: $data['organization_id'],
            publicKey: $data['public_key'],
            schemaVersion: $data['schema_version'],
            status: TrustedSigningKeyStatus::from($data['status']),
            updatedAt: $data['updated_at'],
            revokedAt: $data['revoked_at'] ?? null,
            object: $data['object'] ?? 'registry_signing_key',
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt,
            'fingerprint' => $this->fingerprint,
            'id' => $this->id,
            'organization_id' => $this->organizationId,
            'public_key' => $this->publicKey,
            'schema_version' => $this->schemaVersion,
            'status' => $this->status->value,
            'updated_at' => $this->updatedAt,
            'revoked_at' => $this->revokedAt,
            'object' => $this->object,
        ];
    }
}
