<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class VariantFeatureNeighbor implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Feature class: exons, pockets, or interfaces. */
        public string $featureType,
        /** Whether the variant overlaps the feature. */
        public bool $overlaps,
        /** Distance in base pairs to the feature (nil when overlapping or unavailable). */
        public ?int $distanceBp = null,
        /** Feature identifier when available. */
        public ?string $featureId = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'feature_type',
            'overlaps',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for VariantFeatureNeighbor::fromArray()");
            }
        }
        return new self(
            featureType: $data['feature_type'],
            overlaps: $data['overlaps'],
            distanceBp: $data['distance_bp'] ?? null,
            featureId: $data['feature_id'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'feature_type' => $this->featureType,
            'overlaps' => $this->overlaps,
            'distance_bp' => $this->distanceBp,
            'feature_id' => $this->featureId,
        ];
    }
}
