<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class VariantQueryData implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $backend,
        public string $file,
        public bool $isExecuted,
        public int $recordCount,
        /** @var array<\Rafflesia\Resource\VariantQueryRecord>|null */
        public ?array $records,
        public string $region,
        /** @var array<string>|null */
        public ?array $command = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'backend',
            'file',
            'is_executed',
            'record_count',
            'records',
            'region',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for VariantQueryData::fromArray()");
            }
        }
        return new self(
            backend: $data['backend'],
            file: $data['file'],
            isExecuted: $data['is_executed'],
            recordCount: $data['record_count'],
            records: isset($data['records']) ? array_map(fn ($item) => VariantQueryRecord::fromArray($item), $data['records']) : null,
            region: $data['region'],
            command: $data['command'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'backend' => $this->backend,
            'file' => $this->file,
            'is_executed' => $this->isExecuted,
            'record_count' => $this->recordCount,
            'records' => $this->records !== null ? array_map(fn ($item) => $item->toArray(), $this->records) : null,
            'region' => $this->region,
            'command' => $this->command,
        ];
    }
}
