<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia\Resource;

readonly class VariantFeaturesRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /**
         * Requested feature codes: plddt, burial, pocket_distance, interface_distance.
         * @var array<string>|null
         */
        public ?array $features,
        /** Structure identifier providing residue coordinates. */
        public string $structureId,
        /**
         * Mapped variants, typically from /v1/proteins/variants/map output.
         * @var array<\Rafflesia\Resource\MappedVariant>|null
         */
        public ?array $variants,
        /** Database name published with the relation */
        public ?string $database = null,
        /** Requested durable relation format; parquet is the initial physical format */
        public ?FoldSearchRequestOutputFormat $outputFormat = null,
        /** Local output path or alias for a durable relation artifact */
        public ?string $outputRelation = null,
        /**
         * Requested physical partition columns
         * @var array<string>|null
         */
        public ?array $partitionBy = null,
        /**
         * Optional caller-provided pockets used for pocket_distance; a warning is emitted when pocket_distance is requested and none are available.
         * @var array<\Rafflesia\Resource\Pocket>|null
         */
        public ?array $pockets = null,
        /** When output_relation is requested, include at most this many rows as a non-pageable preview */
        public ?int $previewLimit = null,
        /** Neighbor radius in Angstroms for burial (default 8). */
        public ?float $radius = null,
        /** Requested logical relation name */
        public ?string $relation = null,
        /** Immutable database release published with the relation */
        public ?string $release = null,
        /**
         * Requested physical sort columns
         * @var array<string>|null
         */
        public ?array $sortBy = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'features',
            'structure_id',
            'variants',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for VariantFeaturesRequest::fromArray()");
            }
        }
        return new self(
            features: $data['features'] ?? null,
            structureId: $data['structure_id'],
            variants: isset($data['variants']) ? array_map(fn ($item) => MappedVariant::fromArray($item), $data['variants']) : null,
            database: $data['database'] ?? null,
            outputFormat: isset($data['output_format']) ? FoldSearchRequestOutputFormat::from($data['output_format']) : null,
            outputRelation: $data['output_relation'] ?? null,
            partitionBy: $data['partition_by'] ?? null,
            pockets: isset($data['pockets']) ? array_map(fn ($item) => Pocket::fromArray($item), $data['pockets']) : null,
            previewLimit: $data['preview_limit'] ?? null,
            radius: $data['radius'] ?? null,
            relation: $data['relation'] ?? null,
            release: $data['release'] ?? null,
            sortBy: $data['sort_by'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'features' => $this->features,
            'structure_id' => $this->structureId,
            'variants' => $this->variants !== null ? array_map(fn ($item) => $item->toArray(), $this->variants) : null,
            'database' => $this->database,
            'output_format' => $this->outputFormat?->value,
            'output_relation' => $this->outputRelation,
            'partition_by' => $this->partitionBy,
            'pockets' => $this->pockets !== null ? array_map(fn ($item) => $item->toArray(), $this->pockets) : null,
            'preview_limit' => $this->previewLimit,
            'radius' => $this->radius,
            'relation' => $this->relation,
            'release' => $this->release,
            'sort_by' => $this->sortBy,
        ];
    }
}
