<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class AccountTest extends TestCase
{
    use TestHelper;

    public function testBilling(): void
    {
        $fixture = $this->loadFixture('account_billing');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->account()->billing(expand: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\AccountBilling::class, $result);
        $this->assertSame($fixture['username'], $result->username);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/account/billing', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
    }
}
