<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class CacheTest extends TestCase
{
    use TestHelper;

    public function testAdmission(): void
    {
        $fixture = $this->loadFixture('envelope_cache_admission_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->admission(estimatedSizeBytes: 1, targetDir: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheAdmissionData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/admission', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame(1, $body['estimated_size_bytes']);
        $this->assertSame('test_value', $body['target_dir']);
    }

    public function testBenchmark(): void
    {
        $fixture = $this->loadFixture('envelope_cache_benchmark_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->benchmark(workload: \Rafflesia\Resource\CacheBenchmarkRequestWorkload::ObjectArtifact);
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheBenchmarkData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/benchmark', $request->getUri()->getPath());
    }

    public function testBenchmarkSuite(): void
    {
        $fixture = $this->loadFixture('envelope_cache_benchmark_suite_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->benchmarkSuite(benchmarks: []);
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheBenchmarkSuiteData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/benchmark-suite', $request->getUri()->getPath());
    }

    public function testExplain(): void
    {
        $fixture = $this->loadFixture('envelope_cache_explain_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->explain(cacheKey: 'test_value', namespace: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheExplainData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/explain', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['cache_key']);
        $this->assertSame('test_value', $body['namespace']);
    }

    public function testStatus(): void
    {
        $fixture = $this->loadFixture('envelope_cache_status_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->status(targetDir: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheStatusData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/status', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['target_dir']);
    }

    public function testSweep(): void
    {
        $fixture = $this->loadFixture('envelope_cache_sweep_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->sweep(targetDir: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheSweepData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/sweep', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['target_dir']);
    }

    public function testWarm(): void
    {
        $fixture = $this->loadFixture('envelope_cache_warm_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->warm(workloads: []);
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeCacheWarmData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/warm', $request->getUri()->getPath());
    }

    public function testWorkloadProfiles(): void
    {
        $fixture = $this->loadFixture('envelope_serverless_workload_profile_list_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->cache()->workloadProfiles();
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeServerlessWorkloadProfileListData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/cache/workload-profiles', $request->getUri()->getPath());
    }
}
