<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class DatabaseJoinNormalizationMeasurementsTest extends TestCase
{
    use TestHelper;

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('envelope_database_join_normalization_measurement_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->databaseJoinNormalizationMeasurements()->create(fromColumn: 'test_value', fromDatabase: 'test_value', fromRelation: 'test_value', fromRelease: 'test_value', fromTransform: \Rafflesia\Resource\IdentifierNormalizationTransform::fromArray($this->loadFixture('identifier_normalization_transform')), toColumn: 'test_value', toDatabase: 'test_value', toRelation: 'test_value', toRelease: 'test_value', toTransform: \Rafflesia\Resource\IdentifierNormalizationTransform::fromArray($this->loadFixture('identifier_normalization_transform')));
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeDatabaseJoinNormalizationMeasurementData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/database_join_normalization_measurements', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['from_column']);
        $this->assertSame('test_value', $body['from_database']);
        $this->assertSame('test_value', $body['from_relation']);
        $this->assertSame('test_value', $body['from_release']);
        $this->assertSame('test_value', $body['to_column']);
        $this->assertSame('test_value', $body['to_database']);
        $this->assertSame('test_value', $body['to_relation']);
        $this->assertSame('test_value', $body['to_release']);
    }
}
