<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class DatabaseJoinPathMeasurementsTest extends TestCase
{
    use TestHelper;

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('envelope_database_join_path_measurement_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->databaseJoinPathMeasurements()->create(edges: [], sources: []);
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeDatabaseJoinPathMeasurementData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/database_join_path_measurements', $request->getUri()->getPath());
    }
}
