<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class EpisodesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_envelope_list_episode');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->episodes()->list(status: 'test_value', rolloutGroupId: 'test_value', environmentReleaseId: 'test_value', limit: 1, startingAfter: 'test_value');
        $this->assertInstanceOf(\Rafflesia\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/episodes', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['status']);
        $this->assertSame('test_value', $query['rollout_group_id']);
        $this->assertSame('test_value', $query['environment_release_id']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('test_value', $query['starting_after']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('envelope_episode');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->episodes()->create(environmentReleaseId: 'test_value', environmentTaskId: 'test_value', execution: \Rafflesia\Resource\ExecutionSpec::fromArray($this->loadFixture('execution_spec')), metadata: [], runtimeProfileId: 'test_value', seed: 1, timeoutSeconds: 1);
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeEpisode::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/episodes', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['environment_release_id']);
        $this->assertSame('test_value', $body['environment_task_id']);
        $this->assertSame('test_value', $body['runtime_profile_id']);
        $this->assertSame(1, $body['seed']);
        $this->assertSame(1, $body['timeout_seconds']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('envelope_episode');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->episodes()->get('test_episode_id');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeEpisode::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/episodes/test_episode_id', $request->getUri()->getPath());
    }

    public function testCancel(): void
    {
        $fixture = $this->loadFixture('envelope_episode');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->episodes()->cancel('test_episode_id');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeEpisode::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/episodes/test_episode_id/cancel', $request->getUri()->getPath());
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_envelope_list_episode');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->episodes()->list();
        $this->assertInstanceOf(\Rafflesia\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
