<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class HomologyDatabaseReleasesTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_envelope_homology_database_release_list');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->homologyDatabaseReleases()->list('test_database_id', limit: 1, startingAfter: 'test_value', endingBefore: 'test_value');
        $this->assertInstanceOf(\Rafflesia\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/homology_databases/test_database_id/releases', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('test_value', $query['starting_after']);
        $this->assertSame('test_value', $query['ending_before']);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_envelope_homology_database_release_list');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->homologyDatabaseReleases()->list('test_database_id');
        $this->assertInstanceOf(\Rafflesia\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
