<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class HomologySearchesTest extends TestCase
{
    use TestHelper;

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('envelope_homology_search');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->homologySearches()->create(databaseId: 'test_value', query: \Rafflesia\Resource\HomologyQuery::fromArray($this->loadFixture('homology_query')));
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeHomologySearch::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/homology_searches', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['database_id']);
    }

    public function testGet(): void
    {
        $fixture = $this->loadFixture('envelope_homology_search');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->homologySearches()->get('test_homology_search_id', includeResults: true);
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeHomologySearch::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/homology_searches/test_homology_search_id', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertArrayHasKey('include_results', $query);
    }
}
