<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class OntologyPathsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('list_envelope_ontology_path_list_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->ontologyPaths()->list(fromRelation: 'test_value', toRelation: 'test_value', safety: \Rafflesia\Resource\DatabaseJoinsSafety::All, maxHops: 1, limit: 1, startingAfter: 'test_value', fromDatabase: 'test_value', fromRelease: 'test_value', toDatabase: 'test_value', toRelease: 'test_value', bridge: [], source: [], evidence: \Rafflesia\Resource\OntologyEvidence::Declared, autoResolveBridges: true, ontologyDigest: 'test_value');
        $this->assertInstanceOf(\Rafflesia\PaginatedResponse::class, $result);
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/ontology_paths', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['from_relation']);
        $this->assertSame('test_value', $query['to_relation']);
        $this->assertSame('all', $query['safety']);
        $this->assertArrayHasKey('max_hops', $query);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('test_value', $query['starting_after']);
        $this->assertSame('test_value', $query['from_database']);
        $this->assertSame('test_value', $query['from_release']);
        $this->assertSame('test_value', $query['to_database']);
        $this->assertSame('test_value', $query['to_release']);
        $this->assertSame('declared', $query['evidence']);
        $this->assertArrayHasKey('auto_resolve_bridges', $query);
        $this->assertSame('test_value', $query['ontology_digest']);
    }

    public function testPaginationBoundary(): void
    {
        $fixture = $this->loadFixture('list_envelope_ontology_path_list_data');
        // Ensure cursors are null (first/last page boundary)
        $fixture['list_metadata']['before'] = null;
        $fixture['list_metadata']['after'] = null;
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->ontologyPaths()->list(fromRelation: 'test_value', toRelation: 'test_value', fromDatabase: 'test_value', fromRelease: 'test_value', toDatabase: 'test_value', toRelease: 'test_value');
        $this->assertInstanceOf(\Rafflesia\PaginatedResponse::class, $result);
        // Verify cursors are null on boundary page
        $this->assertNull($result->listMetadata['before']);
        $this->assertNull($result->listMetadata['after']);
        // Iterating should not throw on null cursors
        foreach ($result as $item) {
            $this->assertNotNull($item);
            break;
        }
    }
}
