<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class RqlContractTest extends TestCase
{
    use TestHelper;

    public function testGet(): void
    {
        $fixture = $this->loadFixture('envelope_rql_contract_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->rqlContract()->get();
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeRqlContractData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/rql_contract', $request->getUri()->getPath());
    }
}
