<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Rafflesia\TestHelper;

class RqlFormatsTest extends TestCase
{
    use TestHelper;

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('envelope_rql_format_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->rqlFormats()->create(sourceText: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeRqlFormatData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/rql_formats', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['source_text']);
    }
}
