<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class SqlCredentialTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('envelope_sql_credential_list_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->sqlCredential()->list(organizationId: 'test_value', environmentId: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeSqlCredentialListData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/sql-credentials', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['environment_id']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('envelope_sql_credential_create_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->sqlCredential()->create(name: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeSqlCredentialCreateResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/sql-credentials', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['name']);
    }

    public function testRevoke(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->sqlCredential()->revoke('test_credential_id', organizationId: 'test_value', environmentId: 'test_value');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/sql-credentials/test_credential_id', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['environment_id']);
    }

    public function testRotate(): void
    {
        $fixture = $this->loadFixture('envelope_sql_credential_rotate_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->sqlCredential()->rotate('test_credential_id', organizationId: 'test_value', environmentId: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeSqlCredentialRotateResponse::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/sql-credentials/test_credential_id/rotate', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['environment_id']);
    }

    public function testUsage(): void
    {
        $fixture = $this->loadFixture('envelope_sql_credential_usage_data');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->sqlCredential()->usage('test_credential_id', organizationId: 'test_value', environmentId: 'test_value', from: new \DateTimeImmutable('2026-01-02T03:04:05+00:00'), to: new \DateTimeImmutable('2026-01-02T03:04:05+00:00'));
        $this->assertInstanceOf(\Rafflesia\Resource\EnvelopeSqlCredentialUsageData::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/sql-credentials/test_credential_id/usage', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('test_value', $query['organization_id']);
        $this->assertSame('test_value', $query['environment_id']);
        $this->assertSame('2026-01-02T03:04:05.000+00:00', $query['from']);
        $this->assertSame('2026-01-02T03:04:05.000+00:00', $query['to']);
    }
}
