<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Tests\TestHelper;

class WebhookEndpointsTest extends TestCase
{
    use TestHelper;

    public function testList(): void
    {
        $fixture = $this->loadFixture('execution_envelope_webhook_endpoint_list');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->webhookEndpoints()->list(status: \Rafflesia\Resource\WebhookEndpointsStatus::Enabled, limit: 1, startingAfter: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\ExecutionEnvelopeWebhookEndpointList::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/webhooks/endpoints', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('enabled', $query['status']);
        $this->assertArrayHasKey('limit', $query);
        $this->assertSame('test_value', $query['starting_after']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('execution_envelope_webhook_endpoint');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->webhookEndpoints()->create(enabledEvents: [], url: 'test_value');
        $this->assertInstanceOf(\Rafflesia\Resource\ExecutionEnvelopeWebhookEndpoint::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/webhooks/endpoints', $request->getUri()->getPath());
        $body = json_decode((string) $request->getBody(), true);
        $this->assertSame('test_value', $body['url']);
    }

    public function testRetrieve(): void
    {
        $fixture = $this->loadFixture('execution_envelope_webhook_endpoint');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->webhookEndpoints()->retrieve('test_endpoint_id');
        $this->assertInstanceOf(\Rafflesia\Resource\ExecutionEnvelopeWebhookEndpoint::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/webhooks/endpoints/test_endpoint_id', $request->getUri()->getPath());
    }

    public function testUpdate(): void
    {
        $fixture = $this->loadFixture('execution_envelope_webhook_endpoint');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->webhookEndpoints()->update('test_endpoint_id');
        $this->assertInstanceOf(\Rafflesia\Resource\ExecutionEnvelopeWebhookEndpoint::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('PATCH', $request->getMethod());
        $this->assertStringEndsWith('v1/webhooks/endpoints/test_endpoint_id', $request->getUri()->getPath());
    }

    public function testDelete(): void
    {
        $client = $this->createMockClient([['status' => 204]]);
        $client->webhookEndpoints()->delete('test_endpoint_id');
        $request = $this->getLastRequest();
        $this->assertSame('DELETE', $request->getMethod());
        $this->assertStringEndsWith('v1/webhooks/endpoints/test_endpoint_id', $request->getUri()->getPath());
    }

    public function testRotateSecret(): void
    {
        $fixture = $this->loadFixture('execution_envelope_webhook_endpoint');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->webhookEndpoints()->rotateSecret('test_endpoint_id');
        $this->assertInstanceOf(\Rafflesia\Resource\ExecutionEnvelopeWebhookEndpoint::class, $result);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/webhooks/endpoints/test_endpoint_id/secret-rotations', $request->getUri()->getPath());
    }
}
