<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Rafflesia;

final class RequestOptions
{
    /**
     * @param array<string, mixed> $query
     * @param array<string, string> $headers
     */
    public function __construct(
        public array $query = [],
        public array $headers = [],
        public ?float $timeout = null,
    ) {
    }
}
